### ISSUE TITLE
Analysis: handle proxies

### ISSUE THREAD

**Issue by marcocastignoli** [ethereum/sourcify#1011]
This is a generic issue to investigate several use cases for handling proxies, I will edit this description to list all of the use cases in the following list:

* When decoding the metadata from an address
  * In [EIP-1967](https://eips.ethereum.org/EIPS/eip-1967) the contracts logic are delegated in a consistent location
  * In [EIP-1167](https://eips.ethereum.org/EIPS/eip-1167) the master contract is a specific location in the bytecode
  * This is an example of implementation in typescript from @thirdweb-dev https://github.com/thirdweb-dev/js/blob/89c821d49e95e9319443acf25748ef614c1af396/packages/sdk/src/evm/common/feature-detection.ts#L334-L367

<sub>View in Huly <a href="https://app.huly.io/guest/w-kaanuzdogan-sourcify-65d30de0-75121c5c6c-fd615e?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWU1N2U1NjhiNmVjZDA0ZDYyZDI1MjUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2FhbnV6ZG9nYW4tc291cmNpZnktNjVkMzBkZTAtNzUxMjFjNWM2Yy1mZDYxNWUiLCJwcm9kdWN0SWQiOiIifQ.3Ajk0xYhw3WY3E7bgN47D1-8YML2pB8tta0bWMX1Fqs">HI-404</a></sub>

**Comment by kuzdogan** [comment]
Closing in favor of #1624
