### ISSUE TITLE
Controller Refactoring and API Documentation Improvement

### ISSUE THREAD

**Issue by marcocastignoli** [ethereum/sourcify#1019]
## Issue description

This issue aims to address the refactoring of the current controllers and improve the API documentation in the project.

### Tasks

1. Define terms and naming conventions

2. Reorganize the filesystem as proposed in the proposal below

3. Evaluate possible improvements and decide which to implement:
   - One file with all the routes
   - Do not create folders /session and /stateless for each feature
   - API documentation automation
   - use express-validator schema

4. Implement the chosen improvements.

5. Update the API documentation to reflect the changes and automate the process:
   - Ensure that the documentation at docs.sourcify.dev is updated automatically
   - Update the Postman collection and ensure it remains in sync with the latest changes

### First we need to define some still undefined naming:

- define session vs non-session APIs, here some proposal:
    - session vs non-session
    - session vs standalone
    - persistent vs transient
    - stateful vs stateless
    - session vs stateless 👈 this is Marco’s favorite
- define as **validator** the part of the routes that validate the request using `express-validator`
- define as **handler** the function connected to a route
- define **************feature************** the category of a sourcify’s functionality: create2, etherscan, ecc…

### I would reorganize the filesystem as follows:

- src/server/controllers
    - repository/
    - verification/
        - create2/
            - stateless/
            - session/
                - handlers.ts
                    
                    ```tsx
                    export function sessionVerifyCreate2(...){...}
                    export function sessionPrecompileContract(...){...}
                    ```
                    
                - validators.ts
                    
                    ```tsx
                    export function sessionVerifyCreate2Validator () {
                    	return body("deployerAddress")
                        .exists()
                        .custom((deployerAddress, { req }) => {
                          const addresses = validateAddresses(deployerAddress);
                          req.deployerAddress = addresses.length > 0 ? addresses[0] : "";
                          return true;
                        }),
                      body("salt").exists(),
                      body("abiEncodedConstructorArguments").optional(),
                      body("files").exists(),
                      body("create2Address")
                        .exists()
                        .custom((create2Address, { req }) => {
                          const addresses = validateAddresses(create2Address);
                          req.create2Address = addresses.length > 0 ? addresses[0] : "";
                          return true;
                        }),
                      body("verificationId").exists()
                    }
                    
                    export function sessionPrecompileContractValidator () {
                    	return body("verificationId").exists()
                    }
                    ```
                    
                - routes.ts
                    
                    ```tsx
                    import { sessionVerifyCreate2, sessionPrecompileContract } from "./handlers"
                    import { sessionVerifyCreate2Validator, sessionPrecompileContractValidator } from "./validators"
                    export function initRoutes(app) {
                    	app.route(["/session/verify/create2"])
                    		.post(
                    			sessionVerifyCreate2,
                    		  sessionVerifyCreate2Validator
                    		);
                    	app.route(["/session/verify/create2/compile"])
                        .post(
                          sessionPrecompileContractValidator,
                    			sessionPrecompileContract
                        );
                    }
                    ```
                    
            - utils.ts
                
                ```tsx
                // code shared between session and stateless handler and validator
                ```
                
    - routes.ts
        
        ```tsx
        import initCreate2SessionRoutes from "./verification/create2/session/routes.ts"
        
        // stateless routes
        initCreate2StatelessRoutes();
        ```
        

Possible improvements:

- **One file with all the routes**
in the main file `routes.ts` we could use a generic function `initRoute("/route", validator, handler)` to init all routes in the same file.
    - PRO: the file will represent the whole APIs ina very intuitive way
    - CON: it is a big file
- **Do not create folders /session and /stateless for each feature**
put both session and stateless handlers in the same file: `src/server/controllers/create2/handlers.ts`
    - PRO: filesystem less deep
    - CON: loss in explicitness
- API Documentation
    - While we are on it, can we maybe automate the API documentation. So that:
        - We don’t need to update [docs.sourcify.dev](http://docs.sourcify.dev) seperately
        - We don’t need to update the [Postman collection](https://github.com/ethereum/sourcify/blob/staging/Sourcify.postman_collection.json), which is out of date
- We can use express-validator [Schema](https://express-validator.github.io/docs/guides/schema-validation)s

**Comment by kuzdogan** [comment]
Done with https://github.com/ethereum/sourcify/pull/1033
