### ISSUE TITLE
Unable to verify the contract imported from Etherscan.

### ISSUE THREAD

**Issue by lolieatapple** [ethereum/sourcify#1025]
Unable to verify the contract imported from Etherscan.
My smart contract was success verified in etherscan explorer: (Avalanche Fuji Network)
https://testnet.snowtrace.io/address/0x8bbefc397fb3cbbd34e2ee582c8aaf863fe1ffc1#code

But it failed when I try to use it to verify in sourcify.

<img width="1297" alt="image" src="https://github.com/ethereum/sourcify/assets/54833180/642997c3-bb72-44e7-9bd8-57b39694ab8c">

**Comment by kuzdogan** [comment]
Hello 

You encountered a contract falling into the case we recently discovered #1017 

Will update you once it's fixed

**Comment by lolieatapple** [comment]
Ok, Thanks!
