### ISSUE TITLE
Import historical contracts

### ISSUE THREAD

**Issue by ligi** [ethereum/sourcify#103]
we need more contracts verified. One way is to make more people use verification.komputing.org. Another one is to try to automatically import historic contracts.
@chriseth did a modification of geth that dumps created contracs with their creation code
Based on this data we can try to fetch the metadata from ipfs/swarm - not sure how much of the metadata is still available (pinned) in the networks - but it is worth a shot.
You can find the output for goerli here /ipfs/QmVt8F1pxph81igv8xt8CNXoSbwZJaG3dQNrHHqudbkUGt
The output for mainnet is currently in creation

**Comment by edisinovcic** [comment]
Will be addressed here: https://github.com/ethereum/sourcify/issues/111
