### ISSUE TITLE
[docs]: Update Immutables docs

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1034]
Since we can comfortably verify contracts with immutables, update the Immutables section in docs.

I'd keep the page for the information purposes but maybe make the old content collapse/hideable. Clearly state at the top that this is not a problem anymore.

**Comment by marcocastignoli** [comment]
I would not focus on the fact that we had problems with immutables, but I would explain how contracts with immutables are verified, @kuzdogan what do you think?

**Comment by marcocastignoli** [comment]
Done
