### ISSUE TITLE
Expose and document verification API

### ISSUE THREAD

**Issue by ligi** [ethereum/sourcify#104]
currently we only provide a web interface to start a verification. Ideally we would also have a API for automation. Then e.g. a 3rd party could do #103 - also this would enable a web-interface accessible via ENS

**Comment by edisinovcic** [comment]
Proposal: https://github.com/ethereum/source-verify/issues/119

**Comment by edisinovcic** [comment]
Will be covered by this issue: https://github.com/ethereum/sourcify/issues/76
