### ISSUE TITLE
Make RPC_TIMEOUT configurable

### ISSUE THREAD

**Issue by sealer3** [ethereum/sourcify#1044]
In lib-sourcify, RPC_TIMEOUT is currently set to 5 secs when verifying contracts at

https://github.com/ethereum/sourcify/blob/9dd1c7c5a63bcb85465f2534260f0d24cab2da0e/packages/lib-sourcify/src/lib/verification.ts#LL34C1-L34C26

Unfortunately I sometimes hit that timeout even though the RPC is still online and I know it will eventually process the request. The maximum timeout could be very long. So, I would like the timeout to be extended somehow, probably by making RPC_TIMEOUT configurable.

I would do it myself and make a PR, but first I wonder if there is a cleaner approach than adding an argument to every function that will call a `get` function (which uses an RPC server) or using an environment variable to set the timeout.

**Comment by kuzdogan** [comment]
Just pushed the env var fix https://github.com/ethereum/sourcify/commit/09fe33ebb3e6992bd206effded67ee0cf2d7969c and it's live on production https://github.com/ethereum/sourcify/pull/1045. 

It might make sense in the future to pass a config object or another way to pass these, as we want `lib-sourcify` to run in the browser. But for now this should solve the problem.

Thanks for the report, keep these coming! :) Also curious about your use case if you'd like to tell us about it. You can reach us out from the channels in the footer https://sourcify.dev

**Comment by sealer3** [comment]
Thank you for such a quick turnaround! Quite amazing. I will reach out eventually
