### ISSUE TITLE
Handle the Hardhat vs Sourcify different bytecode case

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1066]
As laid out in https://github.com/ethereum/sourcify/issues/1065 and in the Solidity issue https://github.com/ethereum/solidity/issues/14250 there's the bug that bytecodes change when additional files are added in the compiler. This will be fixed in the next Solidity releases but older versions are already affected.

This is actually similar to `extra-file-input` bug. We need to check why this did not fell into that and wasn't handled by that case.

Anyway, we need to find a way to notice this pattern and try verifying with all files. This means, however, that we can only verify _partially_ as the all source files wont' be in the metadata file.

**Comment by marcocastignoli** [comment]
fixed with f1be6297bcf53041146691aef709c3635d87df97
