### ISSUE TITLE
compilationTarget not check will cause security dangerous

### ISSUE THREAD

**Issue by lolieatapple** [ethereum/sourcify#1071]
<img width="462" alt="image" src="https://github.com/ethereum/sourcify/assets/54833180/9f12bccc-8bb9-4b25-95bb-886ad2402529">

compilationTarget not check will cause security dangerous.

My contract contains multiple files, one of which can pass verification but is not a compilationTarget. It disguises its code and poses a risk that hackers could use an upgradable contract to mimic an un-upgradable one, leading to security risks.

**Comment by marcocastignoli** [comment]
I tried to replicate the issue, but couldn't make it, maybe I followed the wrong steps. Can you please provide more details?

**Comment by lolieatapple** [comment]
ok.
First, you write a demo upgradeable smart contract such as:
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol"

contract MockToken is ERC20 {
    constructor() ERC20("MockToken", "MT") {}

    function mint(address to, uint256 amount) public {
        _mint(to, amount);
    }
}

```
and then, compile and deploy the MockToken contract first:
address: AAA

after, deploy the TransparentProxy contract with the pre MockToken as the implement logic.
address: BBB

Finally, you can verify MockToken contract use proxy address BBB.

**Comment by marcocastignoli** [comment]
Before actually trying this I should say that Sourcify doesn't support proxies. You cannot use the MockToken source code to verify the proxy contract and vice versa. 

Or in other words, the intended behavior is that: you can verify the proxy contract only by using the proxy source code, and you can verify the MockToken contract only by using the MockToken source code.

**Comment by lolieatapple** [comment]
Yes, you are right. However, the reality is that it has mistakenly provided support.

**Comment by lolieatapple** [comment]
the source of the proxy is the same source with MockToken.sol. is it?

**Comment by lolieatapple** [comment]
and which proxy do you use? is it the TransparentProxy in the proxyAdmin?

**Comment by lolieatapple** [comment]
and have you see this?

such as:

File: Abc.sol
has both contracts:
contract A {}
contract B {}

you can success verified when you try to use File Abc.sol to verify both contract A and contract B.

And you can verify contract A with Abc.sol for B's address. (This is the issue).

**Comment by lolieatapple** [comment]
I can give you my screen snap about it, please wait 5 minutes.

**Comment by marcocastignoli** [comment]
> the source of the proxy is the same source with MockToken.sol. is it?

yes

> and which proxy do you use? is it the TransparentProxy in the proxyAdmin?

```sol
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

import "@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol";


contract TransparentUpgradeableProxy is ERC1967Proxy {
    // implementation
```

> and have you see this?

maybe that's the part I skipped because I didn't get it

**Comment by lolieatapple** [comment]
This is my test code:
<img width="1319" alt="image" src="https://github.com/ethereum/sourcify/assets/54833180/6ce9b8cc-0d82-4a7b-8970-06fa6bd6d887">
First, deploy the MockDemo contract.
<img width="1217" alt="image" src="https://github.com/ethereum/sourcify/assets/54833180/fffbf7de-f62b-4594-b79c-4e354f8c87eb">
Second, switch to the TransparentUpgradeableProxy in the same sol file to deploy.
<img width="1225" alt="image" src="https://github.com/ethereum/sourcify/assets/54833180/244e5b0a-2294-4927-97ff-4ec48648026d">
This is the deploy address:
<img width="1245" alt="image" src="https://github.com/ethereum/sourcify/assets/54833180/f1daccf1-08f7-4942-9c5e-8bf1904664d9">
Download verify files from here, and import them to sourcify.dev
<img width="1211" alt="image" src="https://github.com/ethereum/sourcify/assets/54833180/475cbbea-66aa-492e-bc91-72e152a02999">
and verify the proxy.
<img width="804" alt="image" src="https://github.com/ethereum/sourcify/assets/54833180/9ea7303e-7914-48f0-ab5c-c02ba64ada35">
and verify the mockDemo.
<img width="703" alt="image" src="https://github.com/ethereum/sourcify/assets/54833180/86a61e4a-0fac-4999-bfd7-0f4525fbb8b0">
Important step, verify mockDemo again with proxy address:
<img width="739" alt="image" src="https://github.com/ethereum/sourcify/assets/54833180/d5982cd0-eb70-4c4a-8465-c9da3decad3e">
it shows successed.
and in explorer the source file is:
<img width="964" alt="image" src="https://github.com/ethereum/sourcify/assets/54833180/dd10e9b7-ba0e-4032-97e5-160678681767">
it shows the MockDemo source files in proxy address. and api return the same info.

I think the reason is same json file contains both proxy and mockDemo code in it:
<img width="2085" alt="image" src="https://github.com/ethereum/sourcify/assets/54833180/a8f19232-0862-4978-a400-534d69ae6a6b">

this is my new demo source:
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

import "@openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol";

contract MockDemo {
    address public owner;

    function setOwner(address to) public {
        owner = to;
    }
}

```
and this is the explorer URL, the explorer display info was come from sourcify api. 
https://testnet.wanscan.org/address/0x55a03A27EfE92140c518b6ef677628983030F029

Thanks. please help ~~~

**Comment by marcocastignoli** [comment]
Thanks a lot for the detailed description. I'm looking at it 🙏

**Comment by marcocastignoli** [comment]
ok @lolieatapple I finally replicated it! We are on it

**Comment by Hellobloc** [comment]
Fantastic find, but I see that your browser only takes the contract name part of sourcify's compile target. I am concerned that this may lead to ambiguity, take a look at this [issue](https://github.com/blockscout/blockscout-rs/issues/530).
The good news is that sourcify did a great job removing the extra source files which prevented us from building two source files with the same contract name, but there are still some special cases where extra source files are allowed, such as the point mentioned in this [issue](https://github.com/ethereum/sourcify/issues/618).

**Comment by marcocastignoli** [comment]
I replicated the problem on staging.sourcify.dev and it seems solved. (The output is not clear but the proxy contract files are not being replcaced by the Mock contract sources)

**Comment by mohmmedzalep24** [comment]
كلام جميل جدا جدا جدا
