### ISSUE TITLE
Add Support for EOS EVM Mainnet and Testnet

### ISSUE THREAD

**Issue by michael-sumner** [ethereum/sourcify#1078]
The EOS Network has launched EVM and therefore has valid RPC Server Addresses:
See https://chainlist.org/?search=EOS&testnets=true

1. https://api.testnet.evm.eosnetwork.com
2. https://api.evm.eosnetwork.com

See more about EOS EVM here: https://eosnetwork.com/eos-evm/

**Comment by marcocastignoli** [comment]
Hello, we have this page in the docs for requesting chain support: https://docs.sourcify.dev/docs/chain-support/
