### ISSUE TITLE
Fix verification and monitoring tests

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1084]
Since the last update in [metacoin-source-verify](https://github.com/sourcifyeth/metacoin-source-verify) the verification-e2e and monitoring-e2e test are failing more frequently because of:

```
TypeError: Cannot create property 'gasLimit' on string '0x39ee0f'
```

https://app.circleci.com/pipelines/github/ethereum/sourcify/4273/workflows/1f3a26be-fa95-4973-b1cd-c760422156f7/jobs/23633
https://app.circleci.com/pipelines/github/ethereum/sourcify/4273/workflows/1f3a26be-fa95-4973-b1cd-c760422156f7/jobs/23630
https://app.circleci.com/pipelines/github/ethereum/sourcify/4273/workflows/1f3a26be-fa95-4973-b1cd-c760422156f7/jobs/23632

I believe this can be fixed either by updating the web3 in the project (minimal effort), updating both truffle + web3 (med. effort) or migrating the project to hardhat (higher effort).

**Comment by kuzdogan** [comment]
I believe this is fixed?

**Comment by kuzdogan** [comment]
Hmm maybe no, just got this https://app.circleci.com/pipelines/github/ethereum/sourcify/4429/workflows/5a789cb2-3686-4631-8866-d86c9c26cf53/jobs/24561

**Comment by marcocastignoli** [comment]
Now it should be fixed.
