### ISSUE TITLE
Cannot verify any contracts 

### ISSUE THREAD

**Issue by 57u** [ethereum/sourcify#1115]
Seems some config somewhere is borked, cannot verify any contracts. The Error:

Failed to launch the browser process! undefined [116619:116619:0718/225539.601809:ERROR:zygote_host_impl_linux.cc(100)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180. TROUBLESHOOTING: https://pptr.dev/troubleshooting

**Comment by kuzdogan** [comment]
Hi this should be fixed, can you check?
