### ISSUE TITLE
Use Blockscout APIs instead of scraping

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1118]
The getCreatorTx test for Blockscout has been failing for some time https://app.circleci.com/pipelines/github/ethereum/sourcify/4900/workflows/9399cb33-891b-4a6f-a7aa-947239702ce7/jobs/27949

I wasn't able to find out the reason but seems to be related to Puppeteer we're using for scraping.

For Blockscout AFAIK they have an API for getting the creator tx. For the new Blockscout instances we should use that.

For the old Blockscout instances let's check if there's an API endpoint for that. I suppose not. For those we can use scraping. 

However I suggest we remove Puppeteer altogether from the project as it's a really heavy dependency and has caused problems before. I remember we had to introduce it because the new Blockscout is cleint-side rendered. If we can't think if anything else, let's just do a simple fetch for scraping.

**Comment by marcocastignoli** [comment]
Closed by https://github.com/ethereum/sourcify/pull/1203

- now every blockscout instance that has v2 apis enabled is being used to fetch the contract creation tx via API
- all the others are being scraped without puppeteer.

**Comment by kuzdogan** [comment]
Sorry opening this again

#1203 

Is not removing the puppeteer code?

both the JS dependencies, and the dependencies in the CI are not removed?

**Comment by marcocastignoli** [comment]
removed puppeteer, closing this again
