### ISSUE TITLE
Server crash on nightly `soljson-v0.4.16-nightly.2017.8.11+commit.c84de7fa`

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1146]
`/home/data/solc-bin/soljson/soljson-v0.4.16-nightly.2017.8.11+commit.c84de7fa.js`

**Comment by kuzdogan** [comment]
This was the initial output when we saw the server failing and not sure if this was the cause.

Anyway yes, we should log compiler logs. I'm now leaning more toward logging more than less.

**Comment by marcocastignoli** [comment]
I'd close this, and open it again only if it happens again when we will have more logs
