### ISSUE TITLE
Fetching the compiler from GitHub takes a long time

### ISSUE THREAD

**Issue by marcocastignoli** [ethereum/sourcify#1160]
`@ethereum-sourcify/lib-sourcify: Aborting request https://github.com/ethereum/solc-bin/raw/gh-pages/linux-amd64/solc-linux-amd64-v0.8.19%2Bcommit.7dd6d404 because of timout 10000`

Tests are failing because it takes too long to get the compiler (in the example above more than 10 seconds)

**Comment by kuzdogan** [comment]
Resolved?

**Comment by marcocastignoli** [comment]
Yes solved by d7296a8717c9a9ea5ab5c99428e630f0280bc09b
