### ISSUE TITLE
all my verified contract was missing [CRITICAL]

### ISSUE THREAD

**Issue by lolieatapple** [ethereum/sourcify#1177]
Hi, is there any upgrade these days? all my verified contract become to un-verified!!

such as: 0x2f18e6c132BEBbFfc650003d59800add8d98c10c

**Comment by lolieatapple** [comment]
It is a critical issue!!!

**Comment by kuzdogan** [comment]
Hi @lolieatapple Thanks for bringing this up.

We did a server migration today and it seems we've missed some. 

Don't worry we still have the contracts. We will get them live soon.

However I don't see that contract `0x2f18e6c132BEBbFfc650003d59800add8d98c10c`. Here's the full list of full matches:
```
0x084BDaf5E51A70dAd9398a137a9ab3D8EeAD2Ff8
0x1c9c9B9601BD48D09a7bc5D97D15Df8E36eaD1E2
0x1d38579244ade34812bA7891940a288A13a81055
0x30Cc2a8a83E85A46B5411e585BDCaC615F5B2DE1
0x3AF7B67072A2C6c06F0e3B7c923A91fD5eF47351
0x53173e4e68D87763e488378e2ACa702b4D8925B5
0x55a03A27EfE92140c518b6ef677628983030F029
0x59baf7073B29E6120c0e69D0E09E8Ee844BD4675
0x60571bD42839A635256fa9aD0003384dfa4EFB4A
0x60e8901588E7DE783CC10D664A5df5aa617744BC
0x6158Ac0Df24622335fD57e0e175Ef47819ABFDc6
0x7718e72970872c22935Af06eE9a71C1d973b5aAe
0x7bAD98cEC3bF4c139C19778C9E1043A3b3DF9Bd8
0x7bD210951EA4df63c35b9c7C09791732d2D89b8d
0x7f660d075FaE69AaE16cE67aD3B9bc5182314786
0x851072D92DB88FC02fe1Fe24852Fa741C23e25E7
0x8BCF284FDA33947ffb8E55643AD63C6124Dc92b7
0x8C08c741FD08a5FB26a110841183113077B93e3A
0x8a1eF2Ce7111D65A8d85f1A545e5B6D489B0aF3E
0x909Bc9c9b5A669C7AC6FdF058dF2f407D66543f4
0xA1cd4381e77BBbCACAe8DDf6E0A48c9D39f18063
0xA319D53c0799d9449b3863A8FDD623CD2501D868
0xA5E937C00Bf9E94873151c5478035D88D4f781e4
0xB0b5617CC4841c61341DA78B88557187a6766dda
0xB53ED5751EAa31a09ee4e0f4dbD9d8b5f01a5604
0xC480C9b01697711A428FB11c2dbB5B218DcA9977
0xEB14407Edc497a73934dE08D5c3079BB1F5f145D
0xEf7471ed5A5fAEFa2CA32a0d86e790e80Baf1C3B
0xF1BF4CcA44c8dE54a036a67893D4694853024b90
0xF35917F312e8a567A3750692d4c84CDfB19a0d10
0xFe3359b5C97191c4E2543dC7aC675d8BD947dE57
0xbbEDFE7bd585439095840B2f6D1C084bFF423cC7
0xc1bD2DBa7c569CdC108e34B7C61090d00c6E5cef
0xc98a59dC628768067D6779dfa6b62E2F7ec41fA0
0xce2544a80316119E7b5d613Dff967DF966633b5c
0xd187C38dd1D9Ae9406078C134321849270F67e6f
0xd926543a8b925AF68F7594AD83594963B044A939
0xe2C040c060e783FeacA1Cb2cA1Bf134d17E5aA80
0xe3F5fc07B84445eC49FD2DFc19a98a10534EaB34
0xeA74478a4BBE2343b749F226819457F0D37De9Eb
0xf09134fF1635134F44D7024174fc71f5354539d5
0xfFB69B283A3FB79e3A2dfe6eDbdBeE07e0E31bD0
0xfebC2Bc8B4D069AdB1699Ce5b69c243204573B3D
```

**Comment by lolieatapple** [comment]
Yes, I'm very sure I verified it. and there are other my contracts:
0xeB88B159CF18aFC17852559689A2086E907F6cf0
0xcE62D253750223f36ff81bEC51A51223B036eA92

**Comment by RobbyUitbeijerse** [comment]
Similar problems on Beam chain (4337). Contract `0xe338aA35D844D5C1a4E052380DBFA939e0cce13F` was verified before (one of the first on the chain),

but now the verification status can't be pulled anymore:

https://sourcify.dev/server/check-all-by-addresses?addresses=0xe338aA35D844D5C1a4E052380DBFA939e0cce13F&chainIds=4337

**Comment by kuzdogan** [comment]
We received multiple similar reports and looking into why this happened. It's highly likely related to the server migration we went through on 12 Sep around 3 p.m. CET. In any case we still have the files in the old server so we should be able to transfer those contracts. Just need to look into why this happened and see if there are more contracts missing.

If you have any info about exactly when you verified those contracts that'd be really helpful @RobbyUitbeijerse @lolieatapple  Sorry for this issue.

**Comment by kuzdogan** [comment]
I confirm that this is only an incomplete file migration and the contracts you're mentioning are still in the old server's filesystem. We'll migrate them soon. 

In the meantime, you can continue using Sourcify. This doesn't seem to be a critical bug.

**Comment by lolieatapple** [comment]
> We received multiple similar reports and looking into why this happened. It's highly likely related to the server migration we went through on 12 Sep around 3 p.m. CET. In any case we still have the files in the old server so we should be able to transfer those contracts. Just need to look into why this happened and see if there are more contracts missing.
> 
> If you have any info about exactly when you verified those contracts that'd be really helpful @RobbyUitbeijerse @lolieatapple Sorry for this issue.

Hi, I verify this contract: 0xeB88B159CF18aFC17852559689A2086E907F6cf0 at Spt-6-2023 15:51:25 +UTC ~ 15:55:00

**Comment by kuzdogan** [comment]
All contracts are imported. Closing the issue.

Thanks again for reporting. Feel free to open if you encounter anything else.

**Comment by RobbyUitbeijerse** [comment]
All bueno, thanks a lot @kuzdogan!
