### ISSUE TITLE
Import from GitHub fails with error 415 (UI reports possible CORS error)

### ISSUE THREAD

**Issue by svienot** [ethereum/sourcify#1191]
The `Import from GitHub` method fails while trying to import [from this URL:](https://github.com/ericleponner/hedera-contract-album).
- The UI reports a probable CORS error
- The Console shows that the server returns `415`  (see screenshot)

Note: downloading a zip of this repository and using the `Import from remote` method causes the same error.

<img width="1864" alt="Screenshot 2023-10-12 at 17 41 20" src="https://github.com/ethereum/sourcify/assets/16097111/9a2f4b15-bf6f-4e88-8f2d-6c927efd8f7f">

**Comment by svienot** [comment]
Thanks for the quick fix @marcocastignoli. 
I assume the same fix should be applied to `RemoteInput.tsx`.

**Comment by marcocastignoli** [comment]
Thanks @svienot for pointing that out, I completely forgot about that! Now it's fixed
