### ISSUE TITLE
Fixing the "monitored" chains after standalone monitor

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1192]
With the new standalone monitor we no longer list the "monitored" chains in the `sourcify-chains.ts` file, which in turn gets published at [/server/chains](https://sourcify.dev/server/chains). This has broken some parts where we read which chains are monitored such as https://docs.sourcify.dev/docs/chains/ Missing are "monitored" support type, number of chains monitored etc.

![image](https://github.com/ethereum/sourcify/assets/13069972/5b9ab67e-f2ba-44be-aa43-ca9df9e9eb9b)

Any other places where we were reading this info?

**Comment by marcocastignoli** [comment]
Do we want to keep the support in some ways or simply drop this feature in the docs?

I don't know if it could make sense but we could add two additional APIs in the sourcify server:
1. the monitors can pass information about the monitored chains. We can store this info in memory
2. the server return a list of all the monitored chains (the monitor can check every now and then if the monitored chains are listed, and if not call again the first api)

This could be helpful so we can keep track of every monitored chain also coming from 3rd party monitors.

**Comment by kuzdogan** [comment]
Why not just pull things form the infra repo? There we list the monitored chains

**Comment by kuzdogan** [comment]
Ah sorry not infra but this, master branch https://github.com/ethereum/sourcify/blob/staging/services/monitor/chains.json

**Comment by marcocastignoli** [comment]
just because then we cannot support other 3rd party monitor. But for now, if this is enough I can edit the UI so that it supports `https://github.com/ethereum/sourcify/blob/staging/services/monitor/chains.json` or would you rather return it into the `/server/chains` API?

**Comment by kuzdogan** [comment]
I think better the first option. This way the server output will be separate than the monitor

**Comment by marcocastignoli** [comment]
added the monitor support through the use of a function that can be used to support also other 3rd party monitors

`await addMonitoredSupportFrom('https://raw.githubusercontent.com/ethereum/sourcify/staging/services/monitor/chains.json', chains)`
