### ISSUE TITLE
Research if swarm support can be added (publishing repository to it)

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/sourcify#121]
Won't be implemented for now as swarm doesn't support folders.

**Comment by Jakic007** [comment]
As I see it right now, swarm is still in too early stage to make this happen without too much effort on our side.
Main reasons:
- Impossible to upload directories without archiving the root directory as tar first
- No UI file explorer like IPFS

Closest thing that looks like a solution to our problem is the project called [Fairdrive](https://github.com/fairDataSociety/Fairdrive) but that is not intended for public repos. It is for users to store their private data encrypted with their accounts.

**Comment by Jakic007** [comment]
Update:
It is possible to use [fairOS](https://github.com/fairDataSociety/fairOS) with the sligtly modified UI from the [Fairdrive](https://github.com/fairDataSociety/Fairdrive) to get what we need.
We would have to create our "sourcify" user wtih the generic pod and do a login in our application and serve publicly available URL with the already logged in state. 
It is still not possible to upload directories recursively but we could write a script that would upload file by file in the desired directory structure.
