### ISSUE TITLE
Contract Verify and Lookup Errors

### ISSUE THREAD

**Issue by timmaycastags** [ethereum/sourcify#1239]
Hello I was hoping to verify a contract but I get the following errors for lookup and verify.
![sourcify error verify](https://github.com/ethereum/sourcify/assets/102872759/60165213-0e17-4d17-ae07-cbbb875296c3)
![sourcify error](https://github.com/ethereum/sourcify/assets/102872759/ab47cc13-76df-4965-8333-abca1c8685f1)

**Comment by timmaycastags** [comment]
I think this was my browser problem.  reloading resolved.

**Comment by kuzdogan** [comment]
Thanks for the update. We, unfortunately, had a long server downtime :( That was the reason
