### ISSUE TITLE
Fix UI message when `413 Payload Too Large`

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1242]
The UI is showing the user a message that is not understandable when they upload files larger than what's allowed:

<img width="1842" alt="image" src="https://github.com/ethereum/sourcify/assets/13069972/58c6cf9a-823a-4101-b521-ff762772e60b">

**Comment by MukulKolpe** [comment]
Hey @kuzdogan, can I work on this issue?

**Comment by kuzdogan** [comment]
Awesome sure! 

You should run the UI and server, drop files that are larger than allowed and return a suitable message when `429` is detected.

Double check if you get the same response from sourcify.dev or staging.sourcify.dev because there it could be that the response comes from the nginx server. If that's the case we need to increase the nginx file size limit at least as much as the server setting.

**Comment by leo5imon** [comment]
Hey @kuzdogan, has it been fixed yet ? Can do it otherwise

**Comment by MukulKolpe** [comment]
Hey! Apologies for the delay. Got tied up with some work. @leo5imon Feel free to go ahead and fix the issue. Thanks!

**Comment by Aswanth-c** [comment]
> Awesome sure!
> 
> You should run the UI and server, drop files that are larger than allowed and return a suitable message when `429` is detected.
> 
> Double check if you get the same response from sourcify.dev or staging.sourcify.dev because there it could be that the response comes from the nginx server. If that's the case we need to increase the nginx file size limit at least as much as the server setting.

We already have a generic  middleware function  that returns a customized error message stating "Request entity too large," 
It was returned when I tested locally. picture below 

<img width="1496" alt="Screenshot 2024-02-14 at 3 43 29 PM" src="https://github.com/ethereum/sourcify/assets/57211637/c5373063-0671-4c59-a3a5-c77c96568074">


But In production, I guess  that Nginx file size limit is exceeded before the request reaches Express, resulting in a raw error message from Nginx is shown to user 


And also we have a file size checker in the UI that currently only verifies whether a single file's size exceeds 30 MB.(which is the server max request size limit.)

I can modify this function to check if the total size of all files in the request exceeds the maximum limit, or we could increase the Nginx limit slightly beyond the Express limit  and it will hit the generic middleware function and it will return "Request entity too large" error message.

**Comment by kuzdogan** [comment]
@Aswanth-c  Hmm yes looks like it's set at 15 MB at the nginx server. 

I think we should both increase the limit to 30MB and should regardless check the response status and if it's 413 should return a meaningful message

**Comment by Aswanth-c** [comment]
> @Aswanth-c Hmm yes looks like it's set at 15 MB at the nginx server.
> 
> I think we should both increase the limit to 30MB and should regardless check the response status and if it's 413 should return a meaningful message

Agreed ,
Expressjs already returns a valid error message stating, "entity is too large." We can modify the nginx.conf file to return the error in JSON format
the edit would look like something below 
`error_page 413 @entity_too_large_json;
location @entity_too_large_json {
    default_type application/json; 
    return 413 '{"error": "Request Entity Too Large", "message": "The uploaded file exceeds the maximum allowed size."}';
}
`
This way, when Nginx encounters a  413 error, it returns a JSON-formatted error message aligning with the format, we already use in genericErrorHandler method 

let me know your thoughts.

**Comment by kuzdogan** [comment]
It will take longer to get our hands on the nginx server. For now it's enough if we just handle the `413` statuses on the UI instead of sending user the raw error response.

**Comment by Aswanth-c** [comment]
> It will take longer to get our hands on the nginx server. For now it's enough if we just handle the `413` statuses on the UI instead of sending user the raw error response.

I've addressed the issue by showing HTTP status and HTTP status messages instead of raw error from nginx.

here is the pull request 
https://github.com/ethereum/sourcify/pull/1273

**Comment by alexkubica** [comment]
should probably close https://kleoverse.com/bounty/17522c18-422d-43c4-a462-a56bd393a533 😁
