### ISSUE TITLE
[docs]: Display chains that have "Import from Etherscan" support.

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1254]
There's no straightforward way to check the chains that have an Etherscan instance and that are supported in Sourcify to "Import from Etherscan".

In the docs (https://docs.sourcify.dev/docs/chains/) put a new column called "Import from Etherscan" to the left of the tests. The ones that are supported should have the same green checkmark and the others just empty cell. 

The required information is actually already fetched inside the component. At https://sourcify.dev/server/chains one can see the field `etherscanApi`. The chains that have this field are the ones that have support. The table component's implementation is at https://github.com/sourcifyeth/docs/blob/main/docs/supportedChainsTable.jsx

**Comment by yash251** [comment]
please assign me this issue @kuzdogan

**Comment by kuzdogan** [comment]
@yash251 there you go 🙂

**Comment by yash251** [comment]
I added the column but didn't understand where is the information fetched as you mentioned earlier and how can I render it
<img width="834" alt="Screenshot 2024-02-05 at 3 46 19 PM" src="https://github.com/ethereum/sourcify/assets/47234407/e2e6e7f6-c3d1-4e29-bc99-d9aaf800211f">
<img width="643" alt="Screenshot 2024-02-05 at 3 47 49 PM" src="https://github.com/ethereum/sourcify/assets/47234407/f4ae34cf-38be-421a-bc2f-836b6fd1e54d">

**Comment by kuzdogan** [comment]
@yash251 The information is at the `useEffect` that fetches from `https://sourcify.dev/server/chains`. The supported chains in this JSON have the field `etherscanAPI`. The ones without support don't.

**Comment by kuzdogan** [comment]
Thanks!
