### ISSUE TITLE
How to verify smart-contract for unsupported chains?

### ISSUE THREAD

**Issue by unchase** [ethereum/sourcify#1267]
I have a need to verify a smart contract on the **Scroll Sepolia** network, but I can't do it because:

1. Sourcify does not currently support this network (added PR #1259 to _staging_ branch, waiting for release):
![image](https://github.com/ethereum/sourcify/assets/29679226/36c01cb3-c2ba-435a-b16d-5e530979dbf8)

2. If I use `@nomiclabs/hardhat-etherscan` it returns an error that the package is _deprecated_. And there is no way to verify the smart contract using it:
![image](https://github.com/ethereum/sourcify/assets/29679226/b0aa50a1-be4c-4e63-95d3-b536a1d98593)

**My question is**: is there any way to currently verify a smart contract in **Scroll Sepolia**, so that I don't have to wait for the _staging_ branch in Sourcify to be merged into _main_?

**Comment by unchase** [comment]
@marcocastignoli Could you help me figure this out?

**Comment by unchase** [comment]
I've tried deploying Sourcify locally with adding an unsupported network in a custom config. Verification locally was successful, but the contract remained unverified in Explorer.
![image](https://github.com/ethereum/sourcify/assets/29679226/b6ce82e6-5140-411e-94ae-e2db33b07e02)

P.S. This repo link is empty after verification.

This is most likely due to the fact that the explorer takes data from [repo.sourcify.dev](repo.sourcify.dev), which also does not support the **Scroll Sepolia** network.

Is there any way to configure the local Sourcify instance so that explorer checks verified contracts from it?

**Comment by unchase** [comment]
There is an `hardhat.config.js` configuration:

```js
module.exports = {
  defaultNetwork: "scrolltestnet",
  solidity: {
    version: "0.8.21",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200,
      },
      viaIR: true,
    },
  },
  networks: {
    scroll: {
      chainId: 534352,
      url: "https://rpc.scroll.io",
      accounts: [process.env.PRIVATE_KEY],
      gasMultiplier: 1,
    },
    scrolltestnet: {
      chainId: 534351,
      url: "https://sepolia-rpc.scroll.io",
      accounts: [process.env.PRIVATE_KEY],
      gasMultiplier: 1,
    },
  },
  etherscan: {
    apiKey: {
      scroll: process.env.SCROLL_API_KEY,
      scrolltestnet: process.env.SCROLL_API_KEY,
    },
    customChains: [
      {
        network: "scroll",
        chainId: 534352,
        urls: {
          apiURL: "https://api.scrollscan.com/api",
          browserURL: "https://scrollscan.com/",
        },
      },
      {
        network: "scrolltestnet",
        chainId: 534351,
        urls: {
          apiURL: "https://sepolia.scrollscan.dev/api",
          browserURL: "https://sepolia.scrollscan.dev/",
        },
      },
    ],
  },
};
```

**Comment by marcocastignoli** [comment]
Right now the scroll chain is available only on staging, we'll deploy it on production soon. You can set the sourcify server to be staging.sourcify.dev in hardhat in order to test it. Also notice that we are now officially supported by `hardhat-verify`: https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-verify#verifying-on-sourcify

**Comment by unchase** [comment]
> Right now the scroll chain is available only on staging, we'll deploy it on production soon. You can set the sourcify server to be staging.sourcify.dev in hardhat in order to test it. Also notice that we are now officially supported by `hardhat-verify`: https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-verify#verifying-on-sourcify

@marcocastignoli 
Am I correct that if I make the following settings, the verification should complete successfully from **Scroll Sepolia** smart-contract?

```
sourcify: {
  enabled: true,
  apiUrl: "staging.sourcify.dev"
}
```

Correct, I saw that you are officially supported in the hardhat documentation. 
**Another question remains**: what about those networks that are not in the _staging_ branch as well, like **Blast**?

**Comment by unchase** [comment]
I can add it quickly (without PR) to my local Sourcify instance, but the verification result from it won't get into explorer, right?

**Comment by marcocastignoli** [comment]
> I can add it quickly (without PR) to my local Sourcify instance, but the verification result from it won't get into explorer, right?

correct

**Comment by unchase** [comment]
> > I can add it quickly (without PR) to my local Sourcify instance, but the verification result from it won't get into explorer, right?
> 
> correct

Is it possible to tweak the configuration so that I can, via a local Sourcify instance, perform verification for networks I add to a custom configuration file?

Otherwise, I don't really understand for what purpose I might need a local instance.

**Comment by marcocastignoli** [comment]
Yes check the section `Chain config` here: https://docs.sourcify.dev/docs/running-server/

**Comment by unchase** [comment]
> To support a different set of chains, you can create a `src/sourcify-chains.json` file and completely override the default chains.

I did it, but as I wrote earlier, it gives verify the contract locally, but the result of the verification is not visible in explorer.

Perhaps I am missing some setting to make it so that eventually in explorer the contract is verified and checked?

**Comment by unchase** [comment]
The main result I want to achieve is for the contract to be verified **in explorer**.

**Comment by marcocastignoli** [comment]
What do you mean by explorer? [repo.sourcify.dev](https://repo.sourcify.dev)?

In the "online" sourcify repository you can find only contracts that are supported by Sourcify.

**Comment by unchase** [comment]
> What do you mean by explorer? [repo.sourcify.dev](https://repo.sourcify.dev)?
> 
> In the "online" sourcify repository you can find only contracts that are supported by Sourcify.

No, for example, in https://sepolia.scrollscan.com/ for **Scroll Sepolia**; or in https://testnet.blastscan.io/ for **Blast Sepolia**.

**Comment by marcocastignoli** [comment]
Because we are not verifying also on the explorer. We are verifying only on sourcify

**Comment by marcocastignoli** [comment]
No Etherscan doesn't fetch any data from Sourcify. In order to be verified on the explorer you have to verify on the explorer. Other explorers like blockscout or otterscan use Sourcify as the verification provider

**Comment by unchase** [comment]
The main question now is: how do I get verification here (in etherscan-based explorer) using Sourcify with unsupported yet networks (be custom configuration or something else)?

<img width="540" alt="image" src="https://github.com/ethereum/sourcify/assets/29679226/300da5a0-4e51-476b-bfca-ca0684bc77b3">

**Comment by unchase** [comment]
> No Etherscan doesn't fetch any data from Sourcify. In order to be verified on the explorer you have to verify on the explorer. Other explorers like blockscout or otterscan use Sourcify as the verification provider

Previously, using the depricated package `@nomiclabs/hardhat-etherscan`, there was no difficulty with this. Verification took place immediately in etherscan-based or blockscout-based Explorer. How to achieve this now?

Especially if we have a Transparent Upgradable Proxy contract on an unsupported Sourcify network?

**Comment by marcocastignoli** [comment]
`hardhat-verify`  can be configured to support both sourcify and etherscan/blockscout

**Comment by unchase** [comment]
> `hardhat-verify` can be configured to support both sourcify and etherscan/blockscout

Could you please advise on how to do this properly?
Right now, if I set to `hardhat.config.js` settings:

```
sourcify: {
  enabled: false,
},
```

I get this warning:

![image](https://github.com/ethereum/sourcify/assets/29679226/513765fe-33dd-4d00-9894-a361aac1f589)

If I add `enabled: true` in the `etherscan`:

```
etherscan: {
    enabled: true,
    apiKey: {
      scroll: process.env.SCROLL_API_KEY,
      scrolltestnet: process.env.SCROLL_API_KEY,
    },
    ...
}
```

I get this error:

![image](https://github.com/ethereum/sourcify/assets/29679226/26113a52-3e73-4c5f-86ee-2552b3877805)

In the hardhat documentation itself ([1](https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-verify), [2](https://hardhat.org/hardhat-runner/docs/config), [3](https://hardhat.org/hardhat-runner/docs/guides/verifying)) I couldn't find the information I needed.

**Comment by unchase** [comment]
Is there a separate URL for staging for https://repo.sourcify.dev?
P.S. Like `apiUrl: "https://staging.sourcify.dev/server"` for staging

**Comment by unchase** [comment]
> you have to verify on the explorer

I've tried this in a variety of ways.
![image](https://github.com/ethereum/sourcify/assets/29679226/3a731a8c-7d47-410c-8bc9-323f1e27228d)

1. By **Single file** (flattened code): an error occurs because etherscan does not support the `viaIR: true` parameter in its interface, so it outputs:
![image](https://github.com/ethereum/sourcify/assets/29679226/2143cbe0-853c-43ac-bed8-9394283eac0e)

2. By **Standard-Json-Input**: I don't have among the artifacts a file that doesn't return a verification error.
![image](https://github.com/ethereum/sourcify/assets/29679226/162ab421-7346-4481-bec2-80896f13ebc2)

The only way that has always worked before is the `hardhat verify ....` command for a depricated package `@nomiclabs/hardhat-etherscan`. It is not working now. And using `@nomicfoundation/hardhat-verify` causes all the problems I described earlier.

I'm trying to find a way for me to verify the contract, but can't find it at the moment.

**Comment by marcocastignoli** [comment]
I honestly don't know about much about the problems of verification on the explorer. So I'd close this issue as it seems it's not related to sourcify, right?

**Comment by unchase** [comment]
> I honestly don't know about much about the problems of verification on the explorer. So I'd close this issue as it seems it's not related to sourcify, right?

Hmm... This issue is related to contract verification using Sourcify.

I actually run the command to verify the contract, but the contract does not become verified as it is not displayed in the explorer.

**Comment by unchase** [comment]
I would appreciate it if you could help answer [this question](https://github.com/ethereum/sourcify/issues/1267#issuecomment-1941274680).

Or suggest someone who can answer it.

**Comment by marcocastignoli** [comment]
Sorry I lost that message. In order to properly configure sourcify you need to set:

```
sourcify: {
  enabled: true,
  apiUrl: "https://staging.sourcify.dev/server",
  browserUrl: "https://repo.staging.sourcify.dev",
}
```

Like this it should work.

Regarding etherscan I don't know, I think you are passing the right config.

As I told you, Sourcify verification is a completally different thing from the explorer verification. Sourcify verification works: https://staging.sourcify.dev/#/lookup/0x22832d71B940880572854ddB7c1a11566F8250Dc 

here you can see that the contract you are trying to verify was successfully verified.
