### ISSUE TITLE
Add a warning popup until we fix the session UI issue

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1314]
Until we fix the #1289 and #1270 we should put a info popup telling users to verify in a private/incognito window until we fix the issue.

**Comment by Aswanth-c** [comment]
Hey, I would like to work on this issue.

**Comment by kuzdogan** [comment]
Yup, that'd be enough. A warning that will show up each time until we fix the issue. Just, it would be nice if it isn't the same color as the error popup, if you'll use that.
