### ISSUE TITLE
Support for verification preview

### ISSUE THREAD

**Issue by acuarica** [ethereum/sourcify#1319]
Our verification UI flow would need to call the `/session/verify-checked` and `/session/input-files` API endpoints without actually persisting the result of the verification in the repository. This is required in order to obtain an exact preview of what the result of the verification is going to be for a given contract (from https://github.com/hashgraph/hedera-sourcify/issues/90)

Here's our implementation by introducing a `dryrun` query parameter
- https://github.com/hashgraph/hedera-sourcify/pull/92

Would you consider including this feature?

**Comment by kuzdogan** [comment]
Hi, yes I think this is something we can add.

Just out of curiosity, do you have a specific use case in mind? I can't really see why one would need this except something like debugging on production?

**Comment by acuarica** [comment]
> do you have a specific use case in mind?

We are using this feature to allow the user to preview the result of the verification. For example,

![Untitled](https://github.com/ethereum/sourcify/assets/4592980/1ae0f74d-2d26-46ef-a301-4f6abae9d671)

In our explorer, the user visits a contract's page where the `VERIFY CONTRACT` is available. Upon file selection for verification, the UI already displays the verification result without saving the verification, improving the UX.

I'll send a PR soon to get this implemented. Feel free to assign this to me, or I can self-assign it.
