### ISSUE TITLE
Should run getCreatorTx with regex for Etherscan fails because Base Goerli Testnet is unreachable

### ISSUE THREAD

**Issue by marcocastignoli** [ethereum/sourcify#1325]
```
sourcify-server:   1) Server
sourcify-server:        Unit test functions
sourcify-server:          should run getCreatorTx with regex for Etherscan:
sourcify-server:      AssertionError: expected null to equal '0x15c5208cacbc1e14d9906926b8a991ec986…'
sourcify-server:       at Context.<anonymous> (test/server.js:2082:10)
sourcify-server:       at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

We need to update the test to use a different Etherscan instance

**Comment by kuzdogan** [comment]
I think this is incorrect:
- The chain 84531 does not have etherscanRegex as its `fetchContractCreationTxUsing`. In fact there isn't a single chain that has it. All etherscan instances have an API
- 84531 Etherscan API is still working https://api-goerli.basescan.org/api?module=account&action=txlist&address=0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae&startblock=0&endblock=99999999&page=1&offset=10&sort=asc&apikey=YourApiKeyToken

**Comment by marcocastignoli** [comment]
> The chain 84531 does not have etherscanRegex as its fetchContractCreationTxUsing. In fact there isn't a single chain that has it. All etherscan instances have an API

So we can probably rename this test? With something like "should run getCreatorTx with etherscanApi for Etherscan"

> 84531 Etherscan API is still working 

Last time I checked Base Goerli Testnet was unreachable.

**Comment by marcocastignoli** [comment]
Base Goerli support ended on February 9. We need to change the following test to not use chain Base Goerli (84531)

https://github.com/ethereum/sourcify/blob/ba88ecdedd99b28a960d07f40597e7f9e03238ad/services/server/test/server.js#L2072-L2085

**Comment by kuzdogan** [comment]
The point of that test was to test the function `getCreatorTx` **using a regex**. The replaced test does not do that. 

It's ok to keep it like this for now and postpone it to when we refactor tests. We need to cover those lines that do the regex extraction with a test.
