### ISSUE TITLE
Check which endpoints are commonly used and get rid of the ones not being used

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1329]
While getting rid of the repoV1, we should have a look at the endpoints being used and also get rid of the unused ones to make the migration easier. 

Our endpoints: https://docs.sourcify.dev/docs/api/#/ 

For example, my guess would be, that `/files/tree/` endpoints are not used at all. If we remove this unused endpoint, we wouldn't need to work on how to adapt this for the DB or the repoV2. 

I know this would be a breaking change to the API but if no one's using it, it's more pragmatic to just drop it here. 

The task is to look at our nginx logs and find out the endpoints that were not called or rarely called and report them here.

**Comment by manuelwedler** [comment]
So I just manually went through all API routes and checked the logs. I could only find the `/files/tree/{chain}/{address}` not being used over the last 24 hours. However, the `files/tree/any` endpoint is used. For me it looks like, we cannot really get rid of one of the endpoints.

**Comment by kuzdogan** [comment]
Can you please share the stats or the query you used (i.e the Grafana link)? How much is the "used" one used? Is the unused one used in prev days?

**Comment by manuelwedler** [comment]
I created a dashboard in Grafana (production) for checking the API usage. I thought that makes the most sense, so we can check it frequently. It's called `Sourcify Server API Usage`. Please have a look. The visualizations aggregate the number of API calls for the last 1 minute. 

I also found the `/repository/contracts` endpoint not being used now.
