### ISSUE TITLE
Repository lookup not working with non-checksummed addresses

### ISSUE THREAD

**Issue by acuarica** [ethereum/sourcify#1341]
### Problem description

If the _Contract Address_ in the https://repo.sourcify.dev/select-contract/ form has been verified but is not checksummed, the lookup fails. See below (notice the last `d` is lowercase when it should be uppercase `D` to be properly checksummed)

<img width="300" alt="image" src="https://github.com/ethereum/sourcify/assets/4592980/b40a21f2-fcab-4ab3-bec0-341153ca263d">

### Steps to reproduce

Deploy and verify a contract, _e.g._, https://sepolia.etherscan.io/address/0x1cB976dC3602816CCB7270EdC9eA8B87C9410CD4#code.

When visiting its repository URL https://repo.sourcify.dev/contracts/full_match/11155111/0x1cB976dC3602816CCB7270EdC9eA8B87C9410CD4/ it works fine. Even with a non-checksummed address, _e.g._, https://repo.sourcify.dev/contracts/full_match/11155111/0x1cB976dC3602816CCB7270EdC9eA8B87C9410Cd4/

However, when trying to look it up using the https://repo.sourcify.dev/select-contract/  form, using

- _Contract Address_ 0x1cB976dC3602816CCB7270EdC9eA8B87C9410Cd4 (the last `d` should be uppercase to be checksummed)
- _Chain_ Ethereum Testnet Sepolia
- _Match Type_ Full Match

fails as described above.

Change the last `d` to uppercase `D` and the lookup works as expected.

### Solution

Checksum the address in the form before making the lookup.

We had this same issue in our Sourcify fork https://github.com/hashgraph/hedera-sourcify/issues/91. For reference, we solved it in this PR https://github.com/hashgraph/hedera-sourcify/pull/100.

I can send a similar PR here to solve this.

**Comment by kuzdogan** [comment]
Feel free to shoot a PR if you already have something implemented

**Comment by acuarica** [comment]
Sent a PR to the corresponding repo https://github.com/sourcifyeth/h5ai-nginx/pull/4. Hope it's ok.

**Comment by marcocastignoli** [comment]
Closed by https://github.com/sourcifyeth/h5ai-nginx/pull/4

**Comment by acuarica** [comment]
Should I send another PR to update the commit hash to include the change in the subrepo? https://github.com/sourcifyeth/h5ai-nginx/pull/4#issuecomment-2060772252

**Comment by marcocastignoli** [comment]
We were waiting to merge also another PR: https://github.com/sourcifyeth/h5ai-nginx/pull/3
