### ISSUE TITLE
Add support to enable or disable the "Open repo in Remix" link in repository

### ISSUE THREAD

**Issue by acuarica** [ethereum/sourcify#1385]
> Even if this issue might belong to the submodule https://github.com/sourcifyeth/h5ai-nginx, I opened the issue here for triaging.

The repository service provides a link to open each verified contract in Remix.

However, for public self-hosted Sourcify instances (like in the case of Hedera) the _Open repo in Remix_ link does not work, given the Remix plugin only fetches contracts from https://repo.sourcify.dev.

1. Is it worth to add support to enable/disable this link?
2. Is it worth to customize the Remix plugin to support public self-hosted Sourcify instances?

**Comment by kuzdogan** [comment]
Hello :) 

1. Yes we can add support to enable/disable this link (on the build step). Maybe even better we can add a custom link for that, if it does not take too much effort
2. The Remix plugin wouldn't be worth as we're working on a new unified verification plugin #1331. The new plugin will have custom Sourcify URLs. I'd estimate it to take 2-3 months. Does this timeline work for you?

**Comment by acuarica** [comment]
Hi @kuzdogan,

1. Sounds good. We currently disable this link by patching the contract view. We could apply this strategy conditionally at build time. What do you think? I can send a PR in the subrepo to showcase this.
2. Totally, this works for us.

Thanks!

**Comment by kuzdogan** [comment]
Great feel free to submit a PR :)

**Comment by acuarica** [comment]
Sent the PR here https://github.com/sourcifyeth/h5ai-nginx/pull/5. Let me know if this is a fair solution. I know that patching may be odd, but that's the solution we had to modify the repo cloned inside the container.

**Comment by acuarica** [comment]
PR https://github.com/sourcifyeth/h5ai-nginx/pull/5 has been merged.
