### ISSUE TITLE
[contract-call-decoder] Error on undocumented methods

### ISSUE THREAD

**Issue by lukaw3d** [ethereum/sourcify#1388]
Based on https://www.npmjs.com/package/@ethereum-sourcify/contract-call-decoder#usage this works:
```js
console.log(
  await decodeContractCall(
    {
      to: '0x09aFa1879fa654226D522f7099583d54ee8F18f4',
      // https://sepolia.etherscan.io/tx/0x3780ed8164b23bae3175ee5097e55bbdb42ad743c01d356648fcc499567fc0d2
      data: '0xae7cd3ce0000000000000000000000000000000000000000000000000000000000000001',
    },
    { chainId: 11155111 },
  ),
)
```

but this doesn't
```js
console.log(
  await decodeContractCall(
    {
      to: '0x09aFa1879fa654226D522f7099583d54ee8F18f4',
      // https://sepolia.etherscan.io/tx/0x91933847c8b4c213908371a67a27b0ef0eb8ab35a1ff9090a0dd8c85010f502c
      data: '0x0492c54e0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000003426f62000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000000b416e6f746865722052642e000000000000000000000000000000000000000000',
    },
    { chainId: 11155111 },
  ),
)
```
`TypeError: Cannot convert undefined or null to object` at https://github.com/ethereum/sourcify/blob/c97a4f6ccac3279253e0bd32bc72e640484786a0/packages/contract-call-decoder/src/lib/utils.ts#L66-L67
because `devdoc.methods[selector]` can be undefined https://github.com/ethereum/sourcify/blob/c97a4f6ccac3279253e0bd32bc72e640484786a0/packages/contract-call-decoder/src/lib/ContractCallDecoder.ts#L200

---

Simple fix: handle customFieldsMethod like radspecEvaluatedDetails

**Comment by kuzdogan** [comment]
Hey thanks for the issue. Are you using the contract-call-decoder in any way? We are actually not using it anymore and wanted to deprecate and remove it from our codebase. It was an experimentation at the time.

**Comment by lukaw3d** [comment]
I'm not
