### ISSUE TITLE
Creation matches without creation code in the database

### ISSUE THREAD

**Issue by manuelwedler** [ethereum/sourcify#1407]
While investigating #1405, we found another problem. There are some contracts in the database that are missing the creation bytecode even though there is a hash of the code and they have a `creation_match`. This means in the `code` table, a `code_hash` is set but the `code` is NULL. The cause of this needs to be investigated further. 

As an example, see the contract with id `494` inside `verified_contracts`.

**Comment by manuelwedler** [comment]
I just found that only the sourcify database but not the VerA DB has these entries:
```
select *
from code c 
where c.code is null
```
Returns no rows on VerA, but shows some on Sourcify.

**Comment by marcocastignoli** [comment]
On production:

* 1713 recompiled_creation_code = NULL (hash is not null)
* 32604 onchain_creation_code = NULL (hash is not null)

**Comment by kuzdogan** [comment]
For the first case "recompiled_creation_code = NULL (hash is not null)" why are the contracts getting verified/saved in the DB at all? If we can't compile, this should've failed?

For the second case, you are saying "we could recompile it (code_hash is not null)" but isn't the code_hash we are talking about here the onchain creation bytecode's code_hash? What does it have to do with being able to recompile or not? I would expect maybe the hash values here are the hash of empty string?

**Comment by manuelwedler** [comment]
The hashes should be different and not the one for empty string here, as they are also the key of the table

**Comment by marcocastignoli** [comment]
> For the first case "recompiled_creation_code = NULL (hash is not null)" why are the contracts getting verified/saved in the DB at all? If we can't compile, this should've failed?

I just figure out how it happened. If there is already an existing onchain_creation_code_hash set to NULL with the same code_hash as the recompiled_creation_code_hash, then the existing one is going to be used.

**Comment by marcocastignoli** [comment]
I'm closing this because it's going to be fixed by #1414 + #1408 and resetting the database
