### ISSUE TITLE
Move the contract-call-decoder to sourcifyeth and archive the unused sourcifyeth repos

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1409]
Since we don't use the contract-call-decoder anywhere, let's move it to sourcifyeth and archive it. It was meant to be an experiment and not a package.

Also need to handle the package publications on npm, scripts etc.

Also archive other unused repos at sourcifyeth.

**Comment by marcocastignoli** [comment]
- Removed from monorepo with https://github.com/ethereum/sourcify/commit/b2d41497a764f6b1a918b361f52d45673d35a13f
- Created archived repository: https://github.com/sourcifyeth/contract-call-decoder
