### ISSUE TITLE
Investigate deduplication in `compiled_contracts` table

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1420]
As explained in #1416 the deplucation of the rows seem to be not working in the `compiled_contracts` table. Copying the explanation here:

## Deduplication not working in `compiled_contracts`

When debugging the tests I've noticed the identical test contracts are getting added to the `compiled_contracts` table multiple times. I'd have expected them to be deduplicated because the table has a unique key property in the schema definition:
https://github.com/ethereum/sourcify/blob/653952de199123406cea9c3ebda4eda88cc0652a/services/database/migrations/20231109160022-create-alliance-schema.js#L204

However during testing the contracts get added multiple times:
```SQL
SELECT compiler, "language", creation_code_hash, runtime_code_hash FROM public.compiled_contracts x
```
<img width="757" alt="image" src="https://github.com/ethereum/sourcify/assets/13069972/ce877a1f-5e6a-48de-a1e4-2127b67fb8f2">

Am I missing something or is there something wrong?

### To reproduce

1) add a breakpoint at
https://github.com/ethereum/sourcify/blob/653952de199123406cea9c3ebda4eda88cc0652a/services/server/test/integration/repository-handlers/files.spec.ts#L56

2) Add an `.only` modifier to describe:
https://github.com/ethereum/sourcify/blob/653952de199123406cea9c3ebda4eda88cc0652a/services/server/test/integration/repository-handlers/files.spec.ts#L43

3) run the `Mocha - Server Integration`, deploy and verify multiple contracts, and connect to the test database at `localhost:5431`.

**Comment by manuelwedler** [comment]
I was interested and had a quick look why this happens. It seems like the NULL is treated as a different value each time. See this: https://stackoverflow.com/questions/8289100/create-unique-constraint-with-null-columns

We should be able to easily fix it when recreating the database. We just need:

```
CONSTRAINT compiled_contracts_pseudo_pkey UNIQUE NULLS NOT DISTINCT (compiler, language, creation_code_hash, runtime_code_hash) 
```

**Comment by marcocastignoli** [comment]
Nice! So we need to add this in either the sourcify migration or a new migration (Right now we are not using migrations properly)

```
-- Drop the existing unique constraint
ALTER TABLE compiled_contracts
DROP CONSTRAINT compiled_contracts_pseudo_pkey;

-- Add the new unique constraint with NULLS NOT DISTINCT
ALTER TABLE compiled_contracts
ADD CONSTRAINT compiled_contracts_pseudo_pkey UNIQUE (compiler, language, creation_code_hash, runtime_code_hash) 
NULLS NOT DISTINCT;
```
