### ISSUE TITLE
MetadataFile.json not found when using the API endpoints of sourcify

### ISSUE THREAD

**Issue by saineshnakra** [ethereum/sourcify#1468]
I tried to use multiple calls to do so and I get the following error : "Verification failed: 400, {"error":"Metadata file not found. Did you include \"metadata.json\"?","message":"Metadata file not found. Did you include \"metadata.json\"?"}
"

tried to do it using this json : "{
  "address": "0xBB9bc244D798123fDe783fCc1C72d3Bb8C189413",
    "chain": "1",
  "files": {
    "metadata.json": "{\n  \"compiler\": {\n    \"version\": \"0.4.24+commit.e67f0147\"\n  },\n  \"language\": \"Solidity\",\n  \"output\": {\n    \"abi\": [],\n    \"devdoc\": {},\n    \"userdoc\": {}\n  },\n  \"settings\": {\n    \"optimizer\": {\n      \"enabled\": false,\n      \"runs\": 200\n    },\n    \"evmVersion\": \"byzantium\"\n  },\n  \"sources\": {\n    \"TheDAO.sol\": {\n      \"content\": \"// SPDX-License-Identifier: GPL-3.0\\npragma solidity ^0.4.24;\\n\\ncontract TheDAO {\\n    // Simplified version of The DAO contract\\n    address public owner;\\n\\n    constructor() public {\\n        owner = msg.sender;\\n    }\\n\\n    function contribute() public payable {\\n        // Contribution logic\\n    }\\n\\n    function withdraw() public {\\n        // Withdrawal logic\\n    }\\n}\\n\"\n    }\n  },\n  \"version\": 1\n}",
    "TheDAO.sol": "// SPDX-License-Identifier: GPL-3.0\npragma solidity ^0.4.24;\n\ncontract TheDAO {\n    address public owner;\n\n    constructor() public {\n        owner = msg.sender;\n    }\n\n    function contribute() public payable {\n        // Contribution logic\n    }\n\n    function withdraw() public {\n        // Withdrawal logic\n    }\n}\n"
  }
}"
just to test (This is the DAO contract, didnt reach the verify part simply said metadata doesnt exist)
Am I calling it wrong or is it an issue?
also tried using the web version 
![image](https://github.com/ethereum/sourcify/assets/30744887/2108d3af-da0f-4c34-93e5-e9ef95601a54)

am I doing something wrong or is it a bug?

**Comment by kuzdogan** [comment]
Hey can you please share it as a file (you can add `fileName.json.txt` to upload it here. From what you've pasted the JSON doesn't seem to be a valid one.

**Comment by saineshnakra** [comment]
Okay, I just went through it, the metadata file is not valid. Thank you
