### ISSUE TITLE
Implement the `linkReferences` logic for Sourcify server

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1486]
Instead of placeholders we'll use fully qualified names of libraries as field keys. See https://github.com/verifier-alliance/database-specs/pull/11#discussion_r1684441078

- [x] Update the VerA docs

**Comment by Chator1** [comment]
Abdulhafez 
bdalhafzslah382@gmail.com 
0xFD689e5f2d8d9Aec0aD328225Ae62FdBDdb30328
