### ISSUE TITLE
Reach out to other frameworks to add options to publish metadata

### ISSUE THREAD

**Issue by ligi** [ethereum/sourcify#153]
Currently you can get metadata from - currently yo can get it from truffle and the solidity compiler.
We should contact OpenZeplin and buidler

also if anyone knows other platforms that need integration please mention them here.

**Comment by cgewecke** [comment]
Links:

+ [buidler.dev][2]
  + [PR at buidler to make solc outputs configurable][3]
+ [open-zeppelin-sdk][1]

[1]: https://github.com/OpenZeppelin/openzeppelin-sdk
[2]: https://buidler.dev/
[3]: https://github.com/nomiclabs/buidler/pull/497

**Comment by Jakic007** [comment]
Seems like both buidler and open-zepellin are keeping some kind of metadata.json files in among artifacts after compiling.
Support for both frameworks will be available in the next release.

**Comment by edisinovcic** [comment]
Hardhat now supports this.
