### ISSUE TITLE
Remix plugin: Fix Blockscout explorer links

### ISSUE THREAD

**Issue by manuelwedler** [ethereum/sourcify#1530]
When clicking the link to the contract code on Blockscout, the ~~Blockscout instance blocks the http request~~ browser blocks loading the resource. The URL seems to be fine as copying it to a fresh tab works. I think this might be related to the http request origin. We need to see if it is fixable, or otherwise report it to Blockscout.

**Comment by manuelwedler** [comment]
The issue seems to be that we are opening the link from an sandboxed iframe and the blockscout server sets this http header: `cross-origin-opener-policy: same-origin`

**Comment by Chator1** [comment]
0x84e8277c938102f42FC2D9625Fc75049A86c99Ae
bdalhafzslah382@gmail.com 
Abdulhafez 
0xab633c23e74be2d7d2369f180b7043ac41bf4ec2
0xFD689e5f2d8d9Aec0aD328225Ae62FdBDdb30328

**Comment by Chator1** [comment]
b7ce3e45-b6e2-4008-8a9c-b2ff0e4d3c5b

**Comment by manuelwedler** [comment]
I think this problem will actually not persist once the plugin is a native Remix plugin, because it won't be running inside an iframe anymore. Therefore, I'm closing this issue.

**Comment by manuelwedler** [comment]
Had a look at the problem again and it seems adding `allow-popups-to-escape-sandbox` to the iframe's sandbox attribute would solve it. I will ask the Remix team if it will be possible to add it.

Here is a minimal reproduction btw: https://gist.github.com/manuelwedler/b39f3fe377f39683c2128138c3d4e5a0

**Comment by manuelwedler** [comment]
Implemented a hotfix for this here: https://github.com/ethereum/remix-project/pull/5435

**Comment by manuelwedler** [comment]
Merged
