### ISSUE TITLE
Find and test faster s3 client on GCP

### ISSUE THREAD

**Issue by marcocastignoli** [ethereum/sourcify#1542]
We created a Cloud Run Job on GCP that runs `aws s3 sync`, the upload is very slow. It is worth finding a faster S3 client.

*  https://rclone.org/

**Comment by Chator1** [comment]
0xFD689e5f2d8d9Aec0aD328225Ae62FdBDdb30328

**Comment by marcocastignoli** [comment]
I tried rclone but it seems to be slower than aws:

- rclone: in 3 days synced 17gb
- aws: in 2 days synced 21gb
