### ISSUE TITLE
Scheduling regular Filestore backups

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1552]
GCP Filestore NFS service does not provide regular backups directly as an option. For that we need to create a scheduled job: https://cloud.google.com/filestore/docs/scheduling-backups 

Filestore Backups overview: https://cloud.google.com/filestore/docs/backups

Until we have a regular S3-like sync (#1452), we should have at least daily backups. 

After that, we can have it less frequently, although if it does not take too long and costs much, we can keep doing it. When I took the backup manually, it took only a few minutes.

The owner of this task should read the docs comprehensively and make a decision about the backup schedule.

**Comment by manuelwedler** [comment]
I created a Cloud Scheduler (`sourcify-production-nfs-backup-schedule`) which runs the Cloud Function `sourcify-production-nfs-backup` every day at 7 am to trigger the nfs backup.
