### ISSUE TITLE
Verify reddit's smart contracts for Community Points

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/sourcify#161]
Reddit uses ERC20 for their subbreddits. It's currently deployed on Rinkeby and they have two distinct ERC20 tokens.

https://www.reddit.com/r/CryptoCurrency has _Moon_ tokens (https://rinkeby.etherscan.io/address/0xdf82c9014f127243ce1305dfe54151647d74b27a)
and 
https://www.reddit.com/r/FortNiteBR/ has _Brick_ tokens (no detail where they are).

**Comment by chriseth** [comment]
The deployer created multiple contracts roughly at the same time: https://rinkeby.etherscan.io/address/0x0e95c00dbaa7f7107bb7658d45d53a600547f5c7

**Comment by Jakic007** [comment]
I have contacted reddit user that has announced release of Moon tokens when they came out so I am waiting for his response on verifying sources. I could not find sources by googling so maybe they are not open source.
