### ISSUE TITLE
Support for the new tables `source_codes` and `compiled_contracts_sources`

### ISSUE THREAD

**Issue by marcocastignoli** [ethereum/sourcify#1614]
We are in the process of changing VerA and Sourcify database by creating two new tables: `source_codes` and `compiled_contracts_sources`. The new tables will replace the `compiled_contracts.sources` column.

![Image](https://github.com/user-attachments/assets/572fc691-3094-4569-83a9-27f2166a16e4)

**Comment by kuzdogan** [comment]
Can you paste the final schema image here @marcocastignoli ? The above image is old

**Comment by marcocastignoli** [comment]
> Can you paste the final schema image in the first message @marcocastignoli ? The above image is old

done
