### ISSUE TITLE
Verify sources of nodes / wallets / libraries

### ISSUE THREAD

**Issue by ligi** [ethereum/sourcify#162]
just an idea: maybe it is out of scope but I think it would be an extremely helpful low hanging fruit. And we can piggy bag on the emerging validator pool. They would not only build/validate the on chain contracts but also build/validate node (e.g. geth or nethermind ) or a wallet (e.g. celf or WallETH) A requirement is that the software in question is able to build in a reproducible manner. (would also be a nice side effect to add a forcing function for software to have this property) Then source-verify would map hash(commit,variant) -> hash(binary) . One open problem here is the spamming / DDOS aspect here. With the contract-sources it is less of a problem as the need that the contracts need to be deployed to a chain. Maybe in the beginning the validator set just whitelists projects that can submit builds? Or the projects need to pay for their builds? Also happy about other ideas.
This might be a long shot in the future - not saying we need to do it now - just want to feel the air if you would be on board with widening the scope in this manner.

**Comment by edisinovcic** [comment]
This is definitely an interesting proposal, would this be in the scope of the source verify project or some other is to be discussed. But definitely something that we can talk about on the meeting. Still I feel this is definitely not that near future and there are a lot of questions open on how to do this.
