### ISSUE TITLE
Reducing costs on the staging NFS

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1649]
In our GCP setup we have separate NFS instances for both the staging and prod. Since staging is not critical, we can swap that managed NFS (Filestore) instance with a repurposed VM. We can rent a VM with moderate specs (we can scale up/down) with a large enough disk and serve it as an NFS. There should be tutorials etc. to serve a machine as an NFS.

Then we can turn off the staging NFS instance to reduce unnecessary costs.

So we need to:
- [x] Set up the VM as an NFS
- [x] Copy the files from the managed NFS to the new custom NFS
- [x] Unmount the old NFS and mount the new NFS where it's used: Run jobs, services, VMs 
- [x] Set some minimal backups for the new VM, should be easily doable
- [ ] Turn off and delete the managed Filestore NFS

**Comment by manuelwedler** [comment]
We have set up the NFS on a VM, but it was unstable. Therefore, we just move to a cheaper Google managed NFS option.

**Comment by manuelwedler** [comment]
Fully switched all services to an hdd nfs. We still need to delete the old NFS, but I will wait until end of this week for that.
