### ISSUE TITLE
Renaming all files in RepoV2 with `.sol` extension to without extension

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1651]
In accordance to #1648 we should remove the `.sol` extension of the existing files in the RepositoryV2 retrospectively. This is a basic bash command to run on the repo. Keep in mind the command can take time and should be run on a `tmux` etc.

Steps:
- [x] Merge #1648 
- [x] Run the script on staging
- [x] Run the script on production after the next release
- [x] remove the `.sol` from docs https://docs.sourcify.dev/docs/repository/file-repositories/

**Comment by manuelwedler** [comment]
Ran the script again on production and actually it was already successful when I ran it two weeks ago. It was just not possible to check the result due to the SSH issues.
