### ISSUE TITLE
Update docs and start publishing sourcify-server following the Reusable Server Module

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1661]
The docs need to be updated for #1637 

Besides, should we start publishing the server on npm? cc: @RaoulSchaffranek

**Comment by RaoulSchaffranek** [comment]
Yes, I'm in full support of publishing the server to npm. It makes it easier for downstream tools like our debugger to manage the dependency on Sourcify and stay up-to-date. Another advantage is that npm packages don't need to be rebuilt every time they're installed - which means less messing with manual build steps.

**Comment by kuzdogan** [comment]
As said in #1708 I skipped adding the docs because it's rather complicated to set up a new Server() with options. I tried to do the fixes and it takes a lot of time. I'd postpone it until someone requests it and also until https://github.com/ethereum/sourcify/issues/1665
