### ISSUE TITLE
Import contracts from smart-contract-sanctuary

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1670]
There's the smart-contract-sanctuary repo that is no longer maintained:

https://github.com/tintinweb/smart-contract-sanctuary

It contains flattened verified source codes for contracts on different chains. 

We should be able to run a script over those contracts to import any missing ones in our repository.

**Comment by babamovandrej** [comment]
I'd like to take this up

**Comment by mabsattar** [comment]
Hi @kuzdogan i'd like to tackle this.

**Comment by kuzdogan** [comment]
Thanks @mabsattar ! I will be assigning this to you. Do you need more instructions or is it clear?

**Comment by mabsattar** [comment]
hey @kuzdogan thank you for assigning me, if I understand correctly this repo needs to be updated with new contracts, it used to automatically submit contracts to 4byte.directory but the functionality has stopped working. so we have to update with new contracts that have been deployed on diff chains?

**Comment by kuzdogan** [comment]
No this is a repository of verified contracts and their source codes. The owner stopped updating the contracts there but that's irrelevant. 

What we want to do is to go over all of the sources here, format them properly for Sourcify and submit them for verification to the Sourcify server (sourcify.dev). That way we can increase the number of verified contracts on Sourcify

**Comment by mabsattar** [comment]
@kuzdogan  okay, thanks for the clarification, I'll start working on it.

**Comment by Chirag-S-Kotian** [comment]
i am interested in solving this can i start ??

**Comment by kuzdogan** [comment]
@mabsattar could you share your progress on this?

**Comment by mabsattar** [comment]
hi @kuzdogan  i'm working on it, couldn't work last week, I've run the script today and was able to find some contracts missing in the ETH mainnet, lemme validate, i'll keep you updated on this.

**Comment by kuzdogan** [comment]
@mabsattar Thanks. In that case I'd keep it at @mabsattar to avoid conflicts and double-work @Chirag-S-Kotian

**Comment by Chirag-S-Kotian** [comment]
Okay if you have any other issues to solve please let me know 😊😁.

**Comment by manuelwedler** [comment]
@mabsattar any update on this?

**Comment by mabsattar** [comment]
@manuelwedler hi, I'll get it done soon, sorry was not available last couple of weeks. I've already created a script to find missing Contracts, extract data and format them for sourcify, i'll try to complete it and will update on this soon.

**Comment by manuelwedler** [comment]
@mabsattar Thanks for the update! Let us know when you are done :)

**Comment by manuelwedler** [comment]
sorry to ping again but do you have any update? @mabsattar

**Comment by mabsattar** [comment]
hi @manuelwedler , im facing some challenges trying to compile those contracts to extract metadata for verification, these are alot of contracts and im using foundry's native sourcify verification feature and tried automating the task with bash script but unformately facing issues during compilation process hence im struck there.

**Comment by kuzdogan** [comment]
@mabsattar Also now I realize the dataset does not have compilation settings, right? So it would not actually be possible to verify most of them (except the ones with default settings)

**Comment by mabsattar** [comment]
@kuzdogan yes, almost all of those contracts are missing compilation settings in the dataset, and also the source code of most contracts have Non-ASCII Chars which is crashing compilation due to unexpected characters.

**Comment by kuzdogan** [comment]
@mabsattar Ok I guess we can close this then :( it doesn't seem to be feasible. Thank you for your time. If you still want to work on it and try verifying some, you're welcome and I can re-open the issue.

**Comment by mabsattar** [comment]
@kuzdogan yeah it seems so, but i'll give it a one more try and if I manage to make it work then we will reopen the issue.
