### ISSUE TITLE
"View in Remix" doesn't open verified contract in Remix

### ISSUE THREAD

**Issue by rube-de** [ethereum/sourcify#1730]
If you go on a verified contract on sourcify and click on "View in Remix", Remix does open but instead of the verified contract only the default workspace is loaded.

## Steps to reproduce

1. Go eg on the WETH contract address on sourcify https://sourcify.dev/#/lookup/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
2. Click on "View in Remix"
3. Remix opens with default workspace

## Expected behaviour

After clicking "View in Remix" the verified contract is loaded in Remix

**Comment by manuelwedler** [comment]
thanks for the issue! 

The problem seems to be that the old Sourcify plugin was removed after we released the new verification plugin for Remix. We need to implement this functionality into the new plugin.
