### ISSUE TITLE
Default verification URL is invalid in doc

### ISSUE THREAD

**Issue by L0GYKAL** [ethereum/sourcify#1740]
I tried verifying my contracts on sourcify and read the sourcify doc.
In the doc:
![image](https://github.com/user-attachments/assets/a024ddaf-c25a-499d-81bb-41a132b9d407)
The proposed URL is invalid:
![image](https://github.com/user-attachments/assets/8cd4c3e2-5033-481a-9c9a-3814443e0835)

The actual one is:
https://sourcify.dev/server/

**Comment by kuzdogan** [comment]
You could've omitted the `--verifier-url` flag completely to get the correct URL but yes the URL in the docs is wrong. 

fixed with https://github.com/sourcifyeth/docs/commit/b10dc7236b9a106bea12cb0b5e88214dafad235a

Thanks for reporting!
