### ISSUE TITLE
Investigate failing uptime checks for staging repo and server

### ISSUE THREAD

**Issue by manuelwedler** [ethereum/sourcify#1746]
GCP sent alerts for staging repo quite frequently in the last weeks. I've also seen staging server failing, but less frequently than repo. We should check what is wrong. 

I think this is happening since we switched from the SSD to the HDD google-managed NFS. One idea I have is that it might be related to the `sourcify-staging-repository-archive-gen` job. As far as I checked, the uptime alerts happened at the same time as this job was running. This job is using the NFS heavily, so might be worth to investigate this thought a bit more.

**Comment by kuzdogan** [comment]
## Repo

Upon investigation I wasn't able to fully pinpoint what's happening but I noticed some of the contract views (not static files like `https://.../metadata.json`) take a reaaly long time to load. From what I can see this happens whenever we don't have a contract in the repo but the user asks for the UI nevertheless.

Examples:
https://repo.staging.sourcify.dev/contracts/full_match/80001/0x799a4bcF88a4E01f83cf05cA5Cc3d786248523fc/
https://repo.staging.sourcify.dev/contracts/full_match/44787/0x133e77Aba91A49182C41AD2B7E3e2946D66605fF/

Query to get all repo request that took >15s https://console.cloud.google.com/logs/query;query=SEARCH%2528%22%60repo.sourcify%60%22%2529%20OR%20SEARCH%2528%22%60repo.staging%60%22%2529%0AhttpRequest.latency%20%3E%2015s%0A;cursorTimestamp=2024-12-12T15:51:53.724456Z;duration=P1D?authuser=1&inv=1&invt=Abj72g&project=sourcify-project

Here's a contract we do have in repo:
https://repo.sourcify.dev/contracts/partial_match/1/0x1F98431c8aD98523631AE4a59f267346ea31F984/

And now when we change the chainId it takes too long:
https://repo.sourcify.dev/contracts/partial_match/11155111/0x1F98431c8aD98523631AE4a59f267346ea31F984/

I don't exactly know why this would happen in several cases. It should normally just do a file lookup and return an empty UI.

An overload of such requests might be the reason of the downtimes in repo. I'd drop the investigation for now until we encounter another downtime. I wouldn't spend too much time on fixing these as we intend to replace the repo UI anyway after shipping APIv2.

## Server

I wasn't able to pinpoint to a certain thing but we did have some increased number of requests. The server recovered quite fast from the downtime. So here I'd also not dig deeper.

I'll be closing this but we can open again if we come across the same problems again.
