### ISSUE TITLE
Scrape contracts from chainlens

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/sourcify#175]
Url: https://chainlens.pipeos.one/
Raw files would be nice to get.

**Comment by edisinovcic** [comment]
@loredanacirstea do you have contracts listed in raw format somewhere? :) (.sol and metadata files)

**Comment by loredanacirstea** [comment]
@edisinovcic , I could help you with this after Saturday. Do you plan to upload them to ipfs?

**Comment by edisinovcic** [comment]
Yes, plan is to verify them in sourcify and them publish it to ipfs.

**Comment by loredanacirstea** [comment]
@edisinovcic , is `.sql` (MySQL) ok for you?  I can also export to `.csv`, but from experience, that can be flaky.

**Comment by edisinovcic** [comment]
Sql should be good. All the chains :)

Tnx!

**Comment by loredanacirstea** [comment]
@edisinovcic , you can find all data at https://github.com/pipeos-one/eth-contract-sources

```
mainnet:
60,664 records
401.6 MB zipped
blocks: 6500000 - 9487643

ropsten:
53,574 records
376.5 MB zipped
blocks: 5000000 - 7370581

rinkeby:
31,023 records
389.3 MB zipped
blocks: 3500000 - 5975751

kovan:
8,321 records
120.5 MB zipped
blocks: 9000000 - 16897803

goerli:
3,178 records
31.9 MB zipped
blocks: 50000 - 2213212
```

**Comment by edisinovcic** [comment]
Tnx a lot!
