### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/sourcify#176]
```
Segmentation fault (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 139
npm ERR! source-verify@1.0.0 server:start: `node ./dist/server.js`
npm ERR! Exit status 139
npm ERR! 
npm ERR! Failed at the source-verify@1.0.0 server:start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-28T11_38_12_845Z-debug.log

> source-verify@1.0.0 server:start /home/app
> node ./dist/server.js
```

**Comment by edisinovcic** [comment]
```
FATAL ERROR: NativeModule::AddOwnedCode Allocation failed - process out of memory

<--- Last few GCs --->
GC[18:0x4227f10] 25475649 ms: Mark-sweep 360.1 (369.5) -> 360.1 (369.5) MB, 108.6 / 0.1 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 109 ms) (average mu = 0.003, current mu = 0.003) memory pressure GC[18:0x4227f10] 25475759 ms: Mark-sweep 360.1 (369.5) -> 360.1 (369.5) MB, 109.1 / 0.1 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 109 ms) (average mu = 0.003, current mu = 0.003) memory pressure GC

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x12f030edbe1d]
    1: ConstructFrame [pc: 0x12f030e8d145]
    2: StubFrame [pc: 0x12f0311ac79d]
Security context: 0x099c0fb59fe9 <JSObject>
    3: instantiateSync(aka instantiateSync) [0x34815d660f69] [soljson-v0.6.6+commit.6c089d02.js:1] [bytecode=0x2c3dbc325241 offset=28](this=0x2342765026f1 <undefined>)
    4: asm(aka createWasm) [0x34815d65d6f1] [soljson-v0.6.6+commit.6c089d02.js:1] [bytecode=0x2c3dbc324181 offs...

 1: 0x8fb090 node::Abort() [node]
 2: 0x8fb0dc  [node]
 3: 0xb031ce v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb03404 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0x127f196  [node]
 6: 0x127fbe2 v8::internal::wasm::NativeModule::AddCode(v8::internal::CodeDesc const&, unsigned int, unsigned int, unsigned long, unsigned long, std::unique_ptr<std::vector<v8::internal::trap_handler::ProtectedInstructionData, std::allocator<v8::internal::trap_handler::ProtectedInstructionData> >, std::default_delete<std::vector<v8::internal::trap_handler::ProtectedInstructionData, std::allocator<v8::internal::trap_handler::ProtectedInstructionData> > > >, v8::internal::Handle<v8::internal::ByteArray>, v8::internal::wasm::WasmCode::Tier) [node]
 7: 0xe1baa2 v8::internal::compiler::TurbofanWasmCompilationUnit::FinishCompilation(v8::internal::wasm::ErrorThrower*) [node]
 8: 0x125c21f v8::internal::wasm::WasmCompilationUnit::FinishCompilation(v8::internal::wasm::ErrorThrower*) [node]
 9: 0x125fd84  [node]
10: 0x126acff v8::internal::wasm::CompileToModuleObject(v8::internal::Isolate*, v8::internal::wasm::ErrorThrower*, std::unique_ptr<v8::internal::wasm::WasmModule, std::default_delete<v8::internal::wasm::WasmModule> >, v8::internal::wasm::ModuleWireBytes const&, v8::internal::Handle<v8::internal::Script>, v8::internal::Vector<unsigned char const>) [node]
11: 0x1285ef8 v8::internal::wasm::WasmEngine::SyncCompile(v8::internal::Isolate*, v8::internal::wasm::ErrorThrower*, v8::internal::wasm::ModuleWireBytes const&) [node]
12: 0x129c0ca  [node]
13: 0xb9023b  [node]
14: 0xb921d2 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
15: 0x12f030edbe1d 
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! source-verify@1.0.0 monitor:start: `node ./scripts/run_monitor.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the source-verify@1.0.0 monitor:start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-28T20_14_19_358Z-debug.log

> source-verify@1.0.0 monitor:start /home/app
> node ./scripts/run_monitor.js
```

**Comment by ligi** [comment]
yea - OOM - in this case IMHO it should just retry

**Comment by edisinovcic** [comment]
```
TypeError: Cannot read property 'found' of undefined
TypeError: Cannot read property 'found' of undefined

/home/app/node_modules/solc/soljson.js:1
"use strict";var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_HAS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_HAS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_NODE=ENVIRONMENT_HAS_NODE&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){return Module["locateFile"](path,scriptDirectory)}return scriptDirectory+path}v
abort(TypeError: Cannot read property 'found' of undefined). Build with -s ASSERTIONS=1 for more info.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! source-verify@1.0.0 monitor:start: `node ./scripts/run_monitor.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the source-verify@1.0.0 monitor:start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-30T07_25_48_330Z-debug.log

> source-verify@1.0.0 monitor:start /home/app
> node ./scripts/run_monitor.js
```

**Comment by edisinovcic** [comment]
> yea - OOM - in this case IMHO it should just retry

Yes, I'm just trying to get all the errors that we got so we can get them in the logs also.

**Comment by edisinovcic** [comment]
> ```
> FATAL ERROR: NativeModule::AddOwnedCode Allocation failed - process out of memory
> 
> <--- Last few GCs --->
> GC[18:0x4227f10] 25475649 ms: Mark-sweep 360.1 (369.5) -> 360.1 (369.5) MB, 108.6 / 0.1 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 109 ms) (average mu = 0.003, current mu = 0.003) memory pressure GC[18:0x4227f10] 25475759 ms: Mark-sweep 360.1 (369.5) -> 360.1 (369.5) MB, 109.1 / 0.1 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 109 ms) (average mu = 0.003, current mu = 0.003) memory pressure GC
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
>     0: ExitFrame [pc: 0x12f030edbe1d]
>     1: ConstructFrame [pc: 0x12f030e8d145]
>     2: StubFrame [pc: 0x12f0311ac79d]
> Security context: 0x099c0fb59fe9 <JSObject>
>     3: instantiateSync(aka instantiateSync) [0x34815d660f69] [soljson-v0.6.6+commit.6c089d02.js:1] [bytecode=0x2c3dbc325241 offset=28](this=0x2342765026f1 <undefined>)
>     4: asm(aka createWasm) [0x34815d65d6f1] [soljson-v0.6.6+commit.6c089d02.js:1] [bytecode=0x2c3dbc324181 offs...
> 
>  1: 0x8fb090 node::Abort() [node]
>  2: 0x8fb0dc  [node]
>  3: 0xb031ce v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
>  4: 0xb03404 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
>  5: 0x127f196  [node]
>  6: 0x127fbe2 v8::internal::wasm::NativeModule::AddCode(v8::internal::CodeDesc const&, unsigned int, unsigned int, unsigned long, unsigned long, std::unique_ptr<std::vector<v8::internal::trap_handler::ProtectedInstructionData, std::allocator<v8::internal::trap_handler::ProtectedInstructionData> >, std::default_delete<std::vector<v8::internal::trap_handler::ProtectedInstructionData, std::allocator<v8::internal::trap_handler::ProtectedInstructionData> > > >, v8::internal::Handle<v8::internal::ByteArray>, v8::internal::wasm::WasmCode::Tier) [node]
>  7: 0xe1baa2 v8::internal::compiler::TurbofanWasmCompilationUnit::FinishCompilation(v8::internal::wasm::ErrorThrower*) [node]
>  8: 0x125c21f v8::internal::wasm::WasmCompilationUnit::FinishCompilation(v8::internal::wasm::ErrorThrower*) [node]
>  9: 0x125fd84  [node]
> 10: 0x126acff v8::internal::wasm::CompileToModuleObject(v8::internal::Isolate*, v8::internal::wasm::ErrorThrower*, std::unique_ptr<v8::internal::wasm::WasmModule, std::default_delete<v8::internal::wasm::WasmModule> >, v8::internal::wasm::ModuleWireBytes const&, v8::internal::Handle<v8::internal::Script>, v8::internal::Vector<unsigned char const>) [node]
> 11: 0x1285ef8 v8::internal::wasm::WasmEngine::SyncCompile(v8::internal::Isolate*, v8::internal::wasm::ErrorThrower*, v8::internal::wasm::ModuleWireBytes const&) [node]
> 12: 0x129c0ca  [node]
> 13: 0xb9023b  [node]
> 14: 0xb921d2 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
> 15: 0x12f030edbe1d 
> Aborted (core dumped)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 134
> npm ERR! source-verify@1.0.0 monitor:start: `node ./scripts/run_monitor.js`
> npm ERR! Exit status 134
> npm ERR! 
> npm ERR! Failed at the source-verify@1.0.0 monitor:start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2020-05-28T20_14_19_358Z-debug.log
> 
> > source-verify@1.0.0 monitor:start /home/app
> > node ./scripts/run_monitor.js
> ```

OOM memory is happening due to underlaying resources don't have enough ram. Can't be solved programmatically.



> This one is from solcjs that could be fixed.
> 
> ```
> TypeError: Cannot read property 'found' of undefined
> TypeError: Cannot read property 'found' of undefined
> 
> /home/app/node_modules/solc/soljson.js:1
> "use strict";var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_HAS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_HAS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_NODE=ENVIRONMENT_HAS_NODE&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){return Module["locateFile"](path,scriptDirectory)}return scriptDirectory+path}v
> abort(TypeError: Cannot read property 'found' of undefined). Build with -s ASSERTIONS=1 for more info.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! source-verify@1.0.0 monitor:start: `node ./scripts/run_monitor.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the source-verify@1.0.0 monitor:start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2020-05-30T07_25_48_330Z-debug.log
> 
> > source-verify@1.0.0 monitor:start /home/app
> > node ./scripts/run_monitor.js
> ```

Errors should be catches by https://github.com/ethereum/sourcify/pull/183

**Comment by edisinovcic** [comment]
Solved all except out of memory.
