### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by ligi** [ethereum/sourcify#181]
as discussed just on the call having `contracts` and `partial_matches` on the same level is suboptimal. 2 possible solutions I see:
 * 1 have `/contracts/partial_match` and `/contracts/full_match`
 * 2 have `/partial_match` and `/full_match`

I lean to 1 - but not a strong opinion on this
we need to decide on this before #159 so that from having an initial version in the manifest we have a stable directory structure

**Comment by chriseth** [comment]
Note that there is also "match with deployed bytecode but not with creation bytecode" - or is that the same thing as partial_match?

**Comment by edisinovcic** [comment]
@chriseth all of those should go to partial_match currently but that can also be expanded if needed. Not sure on this part. I'm okay with both 1 and 2 @ligi

**Comment by edisinovcic** [comment]
1

**Comment by edisinovcic** [comment]
It's merged in staging. @ligi please check if format is working for you.

Here is URL to the contractrepo to the manifest.json file.

https://contractrepostaging.komputing.org/manifest.json
