### ISSUE TITLE
Support literal sources

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/sourcify#187]
In the case of gnosis contract there are no ipfs/swarm URLs for sources but sources are actually part of the metadata. 

Support this as a possibly source of verification.

Example: https://raw.githubusercontent.com/gnosis/safe-contracts/prepare_deployment/scripts/GnosisSafeMeta.json

**Comment by ligi** [comment]
In this case it would also be great if the sources would be extracted. Not only for verification - but also for accessibility and normalisation.

**Comment by ligi** [comment]
@rmeissner Just out of curiosity: how was this metadata generated?

**Comment by rmeissner** [comment]
I added the following to the compiler options in the truffle config:
```
{
  "settings": {
    "metadata": { "useLiteralContent": true }
  }
}
```
(see https://github.com/gnosis/safe-contracts/blob/prepare_deployment/truffle-config.js#L57)

Then compiled it and extracted the metadata field from the json truffle generated (this is similar to what is done in the ipfs script of the example app).

You can see this here: 
https://github.com/gnosis/safe-contracts/blob/prepare_deployment/scripts/generate_meta.js

I also try to compile the contract based on the meta and verify it to the con chain code (copied a bunch of code of the server). This gives me a perfect match:
https://github.com/gnosis/safe-contracts/blob/prepare_deployment/scripts/simulate_verify.js

**Comment by edisinovcic** [comment]
the source for reproducing is at https://github.com/axic/eth2-deposit-contract (change the Makefile to include —metadata and run make, also needs the solc 0.6.8 release

it is the altona eth2 testnet: https://goerli.etherscan.io/address/0x16e82D77882A663454Ef92806b7DeCa1D394810f

**Comment by cgewecke** [comment]
Was able to get a partial match by compiling the source at Etherscan with the settings they list there. I think this was a case of mismatched metadata rather than a bug about literal sources.

http://contractrepo.komputing.org/partial_matches/5/0x16e82D77882A663454Ef92806b7DeCa1D394810f/ 

Believe this issue should be closed. Literal sources are supported 🙂

**Comment by cgewecke** [comment]
> it would also be great if the sources would be extracted

@ligi 

I think this is currently being done as you suggest. For example this contract was verified using only a metadata.json with an embedded source literal. 

http://contractrepo.komputing.org/partial_matches/5/0x16e82D77882A663454Ef92806b7DeCa1D394810f/

The source is saved to the repo in the same way it would be if it had been individually submitted.
