### ISSUE TITLE
Add support for contracts with immutable state variables

### ISSUE THREAD

**Issue by haltman-at** [ethereum/sourcify#194]
Related to: #37, #105 

My understanding is that, similar to how linked libraries and the delegatecall guard are currently not supported, Solidity immutables are currently not supported either.  (Those being the one other way that the deployed bytecode for a given contract could vary.)  So, that's something that should be supported.

Thank you!

**Comment by chriseth** [comment]
Both the delegatecall guard and immutables can be solved by comparing the creation code instead of the runtime code - this is something that should be done anyway.

**Comment by edisinovcic** [comment]
We have to decide on which hardware to run this all the time.

**Comment by FabijanC** [comment]
Closing because this seems to be covered with: #421.
