### ISSUE TITLE
UI bugs

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/sourcify#196]

**Comment by edisinovcic** [comment]
@igor-lid

**Comment by Jakic007** [comment]
![issue](https://user-images.githubusercontent.com/32742825/87317876-e2577400-c527-11ea-9665-3ee452a2ba67.png)
Server returns status: "partial" but UI shows same response as for status: "perfect".

**Comment by edisinovcic** [comment]
Show path to the contracts with 
https://contractrepostaging.komputing.org/contracts/full_match
if status is perfect and
https://contractrepostaging.komputing.org/contracts/partial_match/
if status is partial.

**Comment by edisinovcic** [comment]
Add gitter icon to the UI to the 
```
https://gitter.im/ethereum/source-verify.
```
