### ISSUE TITLE
Text and modest UI update for Remix plugin on Verifier section

### ISSUE THREAD

**Issue by ryestew** [ethereum/sourcify#197]
1. All links need to open a new tab - otherwise the site will load in the plugin and the site needs to be reloaded.  IF the link is in md - you need to put it in an "a" tag.
2. See proposed changes and text in the graphic below.

![souce-verifer-issue](https://user-images.githubusercontent.com/6050001/85447353-866e8080-b563-11ea-868a-102747d6dd6b.png)

**Comment by edisinovcic** [comment]
Tnx Rob, will link it in the remix sourcify plugin.

**Comment by edisinovcic** [comment]
Addressed here: https://github.com/ethereum/remix-plugins-directory/pull/71

When it's merged this issue can be closed if you @ryestew agree.
