### ISSUE TITLE
Why metadata is different from json input ?

### ISSUE THREAD

**Issue by wighawag** [ethereum/sourcify#2]
Hey looking at https://github.com/ethereum/source-verify/blob/ce90b0fa9c25f4c3183bca884376480dbbb39bd0/verify.js#L59

and reading https://solidity.readthedocs.io/en/v0.5.11/metadata.html?highlight=swarm#usage-for-automatic-interface-generation-and-natspec

Why is the metadata not the same as the solc json input ?
This would make sense no ?

**Comment by chriseth** [comment]
There are certain things like the compiler version that can neither be considered "inputs" nor "outputs", so there are differences between metadata and input anyway, so we made changes where they made sense but tried to keep it as compatible as possible. The settings, for example, can be copied without changes. On the other hand "output selection" only really makes sense for compiler input but not for metadata, while "compilation target" is only meaningful for the metadata.

Does this answer your questions? Are there specific points where you think metadata could be aligned to the input?

**Comment by wighawag** [comment]
Hi, thanks @chriseth for the answer.

I understand why they are different but I think it would be great if the solc compiler would accept the metadata as input, even if there are extra fields. 

The solc compiler could even refuse to compile if some fields are incompatible : for example if the solc compiler version is defined and does not match the compiler being invoked, it should return an error.

Actually the json input format used to be flexible (it was accepting fields not part of the spec) and I was actually injecting the compiler version into it for caching purpose. Until it refused to do that (forgot which version it switched)

Would it be not possible to bring that back? This way we can simply feed the metadata back as input for compiling the contract again and it should return the same exact file.
