### ISSUE TITLE
Support upload of multiple contracts

### ISSUE THREAD

**Issue by ligi** [ethereum/sourcify#205]
as discussed in https://github.com/sourcifyeth/org/issues/7

hijacked by @chriseth

Suggested UI:
```
VERIFIER

FILE UPLOAD

Files uploaded:

/my/source/code/Contract.sol
/my/other/file.sol
someMetadata.json
/some/file.zip/inside/the/zip/contract.sol
... (scroll list, scroll to newest uploaded files)

Found the following metadata files:

- /my/source/code/Contract.sol:MyContract1
   - source missing: /my/othe/source/Source.sol
   - please use the upload dialog above to add the file


- /my/source/code/Contract.sol:MyContract2
   - all files found, but could not determine address
   - Network: [ Mainnet ]
   - Address: [            ] [SUBMIT]

- /my/source/code/Contract.sol:MyContract4
   - all files found, but could not determine address
   - Network: [ Mainnet ]
   - Address: [            ] [SUBMIT]
   - Bytecode does not match

- /my/source/code/Contract.sol:MyContract3
   - all files found, address determined.
   - successfully verified at: <link>


````

1. Initially, the user is presented just with a file upload element. Files can be added there incrementally, it is not possible to delete files. They will be stored in a session directory on the server which is deleted after X minutes of inactivity.

2. After the files have been uploaded, they are shown in a scroll list (height: about 4 elements), which always shows the latest files (i.e. either scroll down or add at the top)

3. After each file upload, the server processes the files and looks for metadata files. If no metadata file has been found, the user is asked to upload a metadata json file, maybe with a short explanation how to find it. At this point, there is enough screen space to just show this text (and all other error messages) below the list of files.

4. For each metadata file found, a new UI element is added at the bottom, starting with the full name of the contract the metadata file is generated for. Below that, there are the following options:

  4a) one or more source files are missing. List the missing files and tell the user how to upload them

  4b) the address of the contract could not be determined automatically. Provide input fields to select the network and the address. A button will submit this and update the UI element.

  4c) after the address has been manually selected, the verificaiton result is displayed. If there was no match, it is shown somehow and the UI elements to specify network and address are still present and functional

  4d) If everything worked out, a link to the verified contract is displayed.

**Comment by chriseth** [comment]
We just discussed how the UI for verifying multiple contracts at the same time could look like. I updated the main description. One thing we still have to consider is how to handle the situation when the same contract is present at multiple addresses. We should try to verify all of them. The user should also be able to enter multiple addresses after each other.

**Comment by edisinovcic** [comment]
We can have a session id for a each verification session.
Flow should go:
* users sends a request with files without session-id
* backend checks if session-id exists, if not it generates new one (https://www.npmjs.com/package/uuid)
* backend then extracts those files (if zip) or just stores them in /tmp/session-id
* if a session-id was sent then add additional files to the /tmp/session-id, otherwise create new session-id

**Comment by kuzdogan** [comment]
Closing with https://github.com/ethereum/sourcify/pull/708 :tada:
