### ISSUE TITLE
Make explanation on how to extract metadata from Truffle and Remix

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/sourcify#206]

**Comment by edisinovcic** [comment]
@franzihei

**Comment by Jakic007** [comment]
This is not needed anymore since we will be directly supporting Truffle project as a whole (and all other formats) after we merge services branch.

**Comment by chriseth** [comment]
Could still mention this fact on the website.

**Comment by Jakic007** [comment]
I will open another issue to update UI with newly supported formats.
