### ISSUE TITLE
Recreating Solidity's metadata from a subset of the original contracts

### ISSUE THREAD

**Issue by alcuadrado** [ethereum/sourcify#213]
Hi,

I'm opening this issue to better understand how Sourcify works, so that we can eventually integrate it in Buidler. In particular, I need to know if the `metadata` can be recreated without some of the contracts that were compiled together when creating the deployment build.

I think this is easier to explain with an example. So let's suppose this happens:

* I have a project where:
  * `A.sol` defines the contract `A`
  * `B.sol` imports `A.sol` and defines the contract `B`, which extends `A`
  * `C.sol` defines the contract `C`
* Those files are compiled together
* `B` is deployed

Now, if I want to verify them, it's clear that I can extract the `metadata` from the compilation output to do it. But if I loose it and need to recreate it, what would happen in these cases:

1. I only compile `A.sol` and `B.sol`.
2. I compile `A.sol`, `B.sol`, and `D.sol`, a new file that defines `D` and doesn't import `A.sol` nor `B.sol`.
2. I compile `A.sol`, `B.sol`, and `E.sol`, a new file that imports `A.sol` and defines `E`, which extends `A`.

Of course, the same compiler version and settings are used in all the cases.

Would I be able to extract `B`'s `metadata` in those cases and still verify them? Would it be an identical `metadata`?

Thanks!

**Comment by chriseth** [comment]
For each contract, the Solidity compiler deduces a subset of the sources that are required to compile the contract and only includes those in the metadata. So for `C`, you only need `C.sol` and for `B` you need `A.sol` and `B.sol`. How many files you compile together in one run should not matter, but it does matter what files you import: If `B.sol` imports another file, that file is needed even if the contract `B` does not use any of the imported symbols.

Did you take a look at the metadata in each of the cases?

**Comment by alcuadrado** [comment]
Thanks for your reply, Chris! 

I did wrote these test cases, but wasn't sure if that was guaranteed by how the metadata field works, or if it was just incidental because of the compiler internals.

This confirmation was all I needed. Thanks!
