### ISSUE TITLE
Metamask plugin

### ISSUE THREAD

**Issue by cgewecke** [ethereum/sourcify#22]
(Following up from discussion in the Jan 8 source-verify meeting)

In the 'trust gap' slides there's a mockup of a metamask confirmation screen as an example of how 
source-verify could be used. 
![Screen Shot 2020-01-08 at 3 51 56 PM](https://user-images.githubusercontent.com/7332026/72049994-f4a0de80-3274-11ea-82d8-2d74d648ca9e.png)

Below are notes about Metamask's plugin system (in beta).

**Resources** 

+ [Metamask plugin wiki][10] 
+ [metamask-snaps-beta repo][11] 

[10]: https://github.com/MetaMask/metamask-snaps-beta/wiki
[11]: https://github.com/MetaMask/metamask-snaps-beta

The wallet currently decodes some transaction data using Parity's 4Byte registry and an API at [eth-method-registry][13]. It is
+ rendered in the transaction confirmation window's data tab. ([code ref][14]). 
+ a JSON stringified object placed in `<pre></pre>` code block - e.g can be anything. 
+ supplied to the wallet by an api method called `addKnownMethod`, exposed with user permission to the plugin [here][15]

[13]: https://github.com/MetaMask/eth-method-registry#usage
[14]: https://github.com/MetaMask/metamask-snaps-beta/blob/022230f0016efbe3da3e609cc970fed668981564/ui/app/pages/confirm-transaction-base/confirm-transaction-base.component.js#L348
[15]: https://github.com/MetaMask/metamask-snaps-beta/blob/022230f0016efbe3da3e609cc970fed668981564/app/scripts/controllers/permissions/restrictedMethods.js#L17

A source-verify plugin would call the backend with the transaction data of a proposed tx and its target address. Maybe something like:

```javascript
const data = await verifier.parseData(tx.data, address, networkInfo)

{
  name: register,
  function: "register(string name, uint duration)",
  arguments: {
    name: "meetup.berlin.eth",
    duration: "1 year"
  },
  description: "Registers the name meetup.berlin.eth for 1 year"
}

_metamask.addKnownMethod(data.name, data)
```

**Other**
+ No `sources` link, but it's possible to open pull requests on the beta to add UI features. 
+ Small api for "recipient address auditing" with special rendering [described here][17].

[17]: https://github.com/MetaMask/metamask-snaps-beta/wiki/Snaps-API#recipient-address-auditing

**Comment by chriseth** [comment]
By the way, there is already an issue in the metamask repository to make this a non-optional feature of metamask: https://github.com/MetaMask/metamask-extension/issues/7274

We can write a plugin to show how the data can be used, but I would prefer this to not be an (optional) plugin in the end.

Also note (not sure if I understood you correctly) that I think it would be better to not have any "backend" in the sense of something hosted on a server. The parsing should be done by the wallet. At best, it would even verify the hash chain by retrieving the contract bytecode from its trusted eth node and checking that all the hashes of the data in the source verifier repository match up. Re-compiling is optional, though :)

**Comment by cgewecke** [comment]
> By the way, there is already an issue in the metamask repository to make this a non-optional feature of metamask: MetaMask/metamask-extension#7274

> We can write a plugin to show how the data can be used, but I would prefer this to not be an (optional) plugin in the end.

Oh great! 

> Also note (not sure if I understood you correctly) that I think it would be better to not have any "backend" in the sense of something hosted on a server.

Ah, thanks for clarifying this. I understood the monitor as a trusted service or DB that someone can submit an address to and quickly get confirmation that everything was checked at some point.

**Comment by marcocastignoli** [comment]
I'm closing this because we have now a repo: [sourcify-metamask-snap](https://github.com/sourcifyeth/sourcify-metamask-snap)
