### ISSUE TITLE
CLI 

### ISSUE THREAD

**Issue by cgewecke** [ethereum/sourcify#23]
(Following up on discussion in the Jan 8 source-verify meeting)

Source submission could be simplified by publishing a cli utility. Buidler and Truffle both support plugins and collecting the sources / generating the metadata would be easy to implement in that format. 

**Install**
```shell
$ npm install --save-dev source-verify
```

**Configure**
```javascript
// truffle-config.js
module.exports = {
  plugins: ['source-verify'],
  networks: {...}
}
```

**Run**
```shell
$ truffle run source-verify

> Generating metadata... 
> ======================
> - A.sol
> - B.sol
> 
> Uploading
> =========
> Your sources should be verified in a few minutes. Check at:
> Metadata: https://gateway.pinata.cloud/ipfs/QmYVd8qstdXtTd1quwv4nJen6XprykxQRLo67Jy7WyiLMB
> Sources: https://gateway.pinata.cloud/ipfs/QmYVd8qiwendlgdsfnJen6XprykxQRLo67Jy(WyiLMC

$ truffle run source-verify --fetch QmYVd8qstdXtTd1quwv4nJen6XprykxQRLo67Jy7WyiLMB

> {
>  ...metadata
> }
```

**Other**

Check if the local version of a contract matches one on chain (to validate a simulation).
```shell
truffle run source-verify \
  --diff \
  --local build/contracts/ENSRegistry.json \
  --network mainnet \
  --address 0xabc....de \

> - 0.4.23+commit.124ca40d // Mainnet
> + 0.5.12+commit.7709ece9 // Local
```

**Comment by chriseth** [comment]
The minimal requirement here is that truffle uploads the metadata and source files to ipfs or swarm around the time the contract is deployed to mainnet. The monitor service in source-verify will pick it up itself. Of course, truffle can also manually upload that data directly to source-verify. This might be more reliable but can only be done after the contract has been deployed to avoid DoS-ing source-verify (it only accepts metadata files and sources of contract that are on chain).

What we can provide to external services by means of an npm package is the re-compilation: Just the fact that the hash in the bytecode matches the metadata file does not mean that the bytecode itself has been produced by the source files linked from the metadata file. To be 100% sure you have to recompile the sources with the correct compiler version and compare the bytecode.

As you already show in the example, "matching sources" is not the only fact that is necessary - another important aspect is that the used and configured compiler versions are the same, as well as all the compiler settings.

**Comment by edisinovcic** [comment]
Can this be closed now with: https://www.npmjs.com/package/ethereum-sourcify-cli

Verification part is covered. We can also add support for upload to ipfs/swarm to the cli itself if that will make sense?

**Comment by edisinovcic** [comment]
This is seperated into multiple npm modules, core, validation and verification. Closing.
