### ISSUE TITLE
Target any file that has .json extension as potential metadata file in findByAddress

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/sourcify#233]
https://github.com/ethereum/sourcify/blob/0d42c85bdb77a2db38b5f1540f33b7803db59b13/src/utils.ts#L256

Currently, addressPath requires metadata to be named 'metadata.json'. This is incorrect. Please target any .json file.

**Comment by chriseth** [comment]
Why is this so? Isn't the metadata file always stored at this location?

**Comment by edisinovcic** [comment]
Yes, but the name doesn't need to be "metadata.json" :)
