### ISSUE TITLE
Paths in metadata

### ISSUE THREAD

**Issue by cgewecke** [ethereum/sourcify#24]
(Following up on discussion in the Jan 8 source-verify meeting)

Am wondering about how the metadata is hashed and the importance of the source file paths. (Apologies in advance if I've misunderstood this...)

In the solidity docs there is a warning:

> Since the bytecode of the resulting contract contains the metadata hash by default, any change to the metadata might result in a change of the bytecode. This includes changes to a filename or path, and since the metadata includes a hash of all the sources used, a single whitespace change results in different metadata, and different bytecode.

For example, A.sol, compiled with `truffle compile` and deployed using the data in the truffle artifact, has metadata source keys like:

```json
"sources": {
  "/Users/cgewecke/code/ef/sv-truffle/contracts/A.sol": {
   "keccak256": "0xfc68a9ffdb0d7d3ec5456f5e2d2c4f855e684892f6c78fcb0dc1e482696d9bb7",
   "urls": [
    "bzz-raw://4d22457fe6215d956a57fcd0cb63f745d8fd718ba8d85a20d65c72232038779f",
    "dweb:/ipfs/QmPmUahXAjtq5mJTW9Qc6oNUVGEuocxb1un5371zLJAAb5"
   ]
  }
},
```
 
Running `solc --metadata contracts/A.sol` over the same source produces

```json
"sources": {
  "contracts/A.sol": {
   "keccak256": "0xfc68a9ffdb0d7d3ec5456f5e2d2c4f855e684892f6c78fcb0dc1e482696d9bb7",
   "urls": [
    "bzz-raw://4d22457fe6215d956a57fcd0cb63f745d8fd718ba8d85a20d65c72232038779f",
    "dweb:/ipfs/QmPmUahXAjtq5mJTW9Qc6oNUVGEuocxb1un5371zLJAAb5"
   ]
  }
},
```

It seems like the file system context and tooling of the deployment and metadata compilations are not allowed to differ even when the sources are identical.

Not sure this would work but perhaps if the file's keccak hash was used as a key instead, metadata could be matched to sources from anywhere as long as paths were associated with the files when uploading to the service for JSON-IO compilation. 

If metadata was pathless, you could:
+ have a source-verify cli tool set up to run in CI on merge to a release branch
+ have a bot that searched Github for Solidity projects, cloning and compiling them, uploading all the metadata to SV to build a large sources DB.

**Comment by chriseth** [comment]
The compiler core itself does not access the filesystem. It is just given a `filename -> file contents` mapping. The outer part of the compiler, let's call it the "compiler driver" does things like looking up import paths on the host computer's filesystem, but this is optional. You can also directly supply this mapping to the compiler driver and it will not access the filesystem either. So you can use paths that do not exist on the host computer's filesytem.

We do not want source-verify to store all sources that are somewhere on github, because that would allow it to easily spam the whole system. The important measure against spam is the fact that all sources we host must be somehow related to a contract on chain, because it costs real money to put something on chain.

What we could do is store a list of keccak256 hashes of source files together with links to how to obtain them. Then if such a source is referenced from a newly deployed contract, we store it. The problem, though, is that people usually do not store the metadata file and without that file, the sources are mostly worthless. Even if we do not have paths in the metadata, we would have to try out all the different compiler versions and settings (remappings, etc).

**Comment by cgewecke** [comment]
> We do not want source-verify to store all sources that are somewhere on github, because that would allow it to easily spam the whole system. The important measure against spam is the fact that all sources we host must be somehow related to a contract on chain, because it costs real money to put something on chain.

I see..not certain but the economics of this might be worth looking at in more detail. 

About 400 contracts [a week][5] are uploaded to Etherscan. If source-verify was as widely used, the monitor would need to run 24/7 and inspect all transactions.

+ There are [~500k txs/day][4] on mainnet
+ Infura's pricing for that many requests/day is  [~$150/month][3]

Meanwhile storage is inexpensive:
+ Pinata (an IPFS storage & pinning service) charges [.$15 per GB/month][1]
+ A large Solidity project (ex: [Synthetix][2]) is ~350kb. 
+ 1 GB is ~ 2750 large Solidity projects
+ $150/month of Infura reads costs the same as storing 2.75 million Solidity projects/month

If source-verify was a CLI tool, it could delegate the problem of storage to e.g. Pinata which has API tokens and 1GB of free storage per user. You could just wrap that at the command line and ask users to get a token - Pinata would manage this aspect of the spam risk. 

Then, if someone wanted to be 'hosted' in the sense of being included in a special repository of verified sources, they could submit a request for a specific address and re-compilation would proceed only if matches already existed between on-chain & on ipfs. 

In the [comment][7] on #22 it sounds like there's a willingness to trust that the deployer published their metadata in good faith and it's a) the principle that it *could* be verified and b) the availability of the user-doc info etc that matters. Is that accurate? 

[1]: https://pinata.cloud/pricing
[2]: https://github.com/Synthetixio/synthetix
[3]: https://infura.io/pricing
[4]: https://bitinfocharts.com/ethereum/
[5]: https://etherscan.io/contractsVerified
[7]: https://github.com/ethereum/source-verify/issues/22#issuecomment-572510821

**Comment by cgewecke** [comment]
Update: We discussed the question of how intensively the monitor uses Infura resources and the analysis above is wrong - it's possible to get a block with all the transaction objects listed in a single call. This means monitoring mainnet is +/- 5000 requests per day and well under the 100k request limit for Infura's free tier.

**Comment by aaronmboyd** [comment]
> (Following up on discussion in the Jan 8 source-verify meeting)
> 
> Am wondering about how the metadata is hashed and the importance of the source file paths. (Apologies in advance if I've misunderstood this...)
> 
> In the solidity docs there is a warning:
> 
> > Since the bytecode of the resulting contract contains the metadata hash by default, any change to the metadata might result in a change of the bytecode. This includes changes to a filename or path, and since the metadata includes a hash of all the sources used, a single whitespace change results in different metadata, and different bytecode.
> 
> For example, A.sol, compiled with `truffle compile` and deployed using the data in the truffle artifact, has metadata source keys like:
> 
> ```json
> "sources": {
>   "/Users/cgewecke/code/ef/sv-truffle/contracts/A.sol": {
>    "keccak256": "0xfc68a9ffdb0d7d3ec5456f5e2d2c4f855e684892f6c78fcb0dc1e482696d9bb7",
>    "urls": [
>     "bzz-raw://4d22457fe6215d956a57fcd0cb63f745d8fd718ba8d85a20d65c72232038779f",
>     "dweb:/ipfs/QmPmUahXAjtq5mJTW9Qc6oNUVGEuocxb1un5371zLJAAb5"
>    ]
>   }
> },
> ```
> 
> Running `solc --metadata contracts/A.sol` over the same source produces
> 
> ```json
> "sources": {
>   "contracts/A.sol": {
>    "keccak256": "0xfc68a9ffdb0d7d3ec5456f5e2d2c4f855e684892f6c78fcb0dc1e482696d9bb7",
>    "urls": [
>     "bzz-raw://4d22457fe6215d956a57fcd0cb63f745d8fd718ba8d85a20d65c72232038779f",
>     "dweb:/ipfs/QmPmUahXAjtq5mJTW9Qc6oNUVGEuocxb1un5371zLJAAb5"
>    ]
>   }
> },
> ```
> 
> It seems like the file system context and tooling of the deployment and metadata compilations are not allowed to differ even when the sources are identical.
> 
> Not sure this would work but perhaps if the file's keccak hash was used as a key instead, metadata could be matched to sources from anywhere as long as paths were associated with the files when uploading to the service for JSON-IO compilation.
> 
> If metadata was pathless, you could:
> 
> * have a source-verify cli tool set up to run in CI on merge to a release branch
> * have a bot that searched Github for Solidity projects, cloning and compiling them, uploading all the metadata to SV to build a large sources DB.

Right, after days of trying to get around posting my local absolute path to Sourcify, finally found this issue. I even got down to creating metadata manually with the `solc --metadata` command, but I never get it to verify because the deployed bytecode (with truffle) is different, containing a hash of the absolute paths. 

It's very messy and possibly a security and/or privacy leak that many might not be aware of, simply letting truffle generate the build JSON and uploading it. I'm trying to get around it without changing my environment to hardhat.

**Comment by christoph2806** [comment]
One possible workaround is to run truffle in a docker: 
1) Create an empty folder
2) npm init -y
3) npm i truffle
4) create a Dockerfile with the following content: 
```
FROM node:12

# Create app directory
WORKDIR /usr/src/truffle

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

WORKDIR /solc

CMD [ "/usr/src/truffle/node_modules/truffle/build/cli.bundled.js", "compile", "--all" ]
```
5) run the docker container with -v [your contracts folder]:/solc

In the resulting build the source paths are starting with /solc/...
(thx to @chriseth for the tip)

**Comment by christoph2806** [comment]
In the meantime, truffle seems to have updated its metadata generator to create reasonable paths.
