### ISSUE TITLE
Extract sources from github 

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/sourcify#245]
Find a way to extract sources from github repo

**Comment by chriseth** [comment]
Note that these repositories would need to have the build directory included to make it work properly. But even if not, maybe we can have a mode where people specify the github repository for the source files and then upload the metadata files from their local computer.

**Comment by edisinovcic** [comment]
Yes, ideally github repo would contain build. When it doesn't we can show error on the UI as it is now, metadata.json missing, or similar message and then have option to upload additional files. 
We can discuss it in more detail and UI would need to be updated for this in the design.
