### ISSUE TITLE
Workarounds for Solidity's bug #9573

### ISSUE THREAD

**Issue by alcuadrado** [ethereum/sourcify#246]
Hi,

I'm trying to come up with a workaround to this bug: https://github.com/ethereum/solidity/issues/9573

To summarize it: If you have a file `A.sol`, and compile it with an unrelated `B.sol` file, it may result in a different output than compiling `A.sol` alone.

This is especially nasty for this project, as the `metadata` of the contracts in `A.sol` won't include `B.sol`.

An obvious way to avoid this bug is by running one compilation per file `f`, which would only include `f` and all of its transitive dependencies. This is prohibitively expensive and we won't do it in Buidler by default.

I'm creating this issue to discuss alternative workarounds.

The first one that comes to my mind: following the example mentioned above, add `B.sol` to `A.sol`'s contracts' `metadata`. 
Will this consistently work?

Do you have any other ideas?

Thanks

**Comment by chriseth** [comment]
@alcuadrado do you have an indication of how common this problem is? As a workaround, we could provide a standard-json-input file that is not the one that would be created from the metadata file but still results in the correct bytecode being generated.

**Comment by alcuadrado** [comment]
I don't have concrete numbers, but we got a report from a user affected by the bug immediately after we released our new etherscan plugin, so I suspect a nontrivial amount of users are affected. 

It's hard to tell an actual number, as most users only verify on etherscan, and we give them instructions that avoid the problems there. As etherscan uses the standard-json-input it's less affected by this bug.

**Comment by wighawag** [comment]
I think it is quite common
My verification tool always attempt to verify with metadata source first and if a flag is enabled it ll use the full solc input as backup.

It happen on several of my contract and one user told me he had to enable the flag for all his contracts
