### ISSUE TITLE
Validation Script

### ISSUE THREAD

**Issue by chriseth** [ethereum/sourcify#252]
Provide lightweight stand-alone npm package that can be used as a commandline interface and from nodejs scripts that can consume metadata and source files and produces standard-json structures such that people can re-compile contracts to verify them.

Feature list:

- run the script with a list of files as commandline arguments, potentially also directories or zip files
- scan these files for metadata files and return a list of them
  - scan each file in the provided directories
  - if the file is a json file and contains the required keys for metadata files, consider it a metadata file
  - if the file is not a json file / is too large / a binary file, then scan for `"{\"compiler\":{\"version\".*?},\"version\":1}"`, un-quote this and consider this as a metadata file
- each metadata file is / can be identified by the contract it represents (and should be reported to the user like that): `metadata['settings']['compilationTarget']' - there should be a single key that contains the file name and the value is the contract name. The file name can be used to disambiguate if there are multiple contracts of the same name.
- for each metadata file / contract file look for the referenced source files

For each metadata file / contract, we can have a success (all files found) or a failure case (not all files found, or something malformatted).

Output (given for the commandline interface, suitably formatted as json if used via nodejs directly - the instructional texts are only given on the commandline):

```
MyContractName (my/file/name):
  Error: Malformed json

MyContractName2 (my/file/name):
  Error: Missing sources:
  The following files were not part in the list of files and directories provided.
  Please retrieve the files (potentially via ipfs) and re-run the script.
    - my/sourcefileA.sol (keccak256: 0x1234... bzzr://... ipfs://...)
    - my/otherfile.sol (keccak256: 0x1234... bzzr://... ipfs://...)
  7 other source files were found successfully.
 
TheOtherContractName (my/file/othername):
  Success!
  Compiled with Solidity 0.6.5
  https://solc-bin.ethereum.org/wasm/soljson-v0.6.6+commit.6c089d02.js
  https://solc-bin.ethereum.org/linux-amd64/solc-v0.6.6+commit.6c089d02
  To re-compile, use:
  echo "{...}" |   solc --standard-json -
  ...
```

**Comment by Jakic007** [comment]
> if the file is not a json file / is too large / a binary file, then scan for "{\"compiler\":{\"version\".*?},\"version\":1}", un-quote this and consider this as a metadata file

@chriseth What is the case when metadata is inside a file that is not json parsable? We are not checking for the extension, we are trying to JSON.parse the file to pull out metadata out of it.

**Comment by chriseth** [comment]
For the scan for `"{"compiler":{"version".*?},"version":1}"` it is not a requirement that the file itself is json parseable. Just do this as a second step if the file is not json parseable or does not conform to metadata itself.

**Comment by FabijanC** [comment]
@chriseth As discussed yesterday, it should be possible for a user to simply pipe the solc-friendly JSON output, if that is the format the user specifies. However, the result of the validation program might be more than just one JSON, depending on the number of metadata files detected. So, would it make sense to enable the pipeable output when only one metadata is detected? And what do you suggest would be the best behavior if such output format is specified, but multiple metadata files are found?

**Comment by chriseth** [comment]
I imagined it work as follows:
```
# sourcify-validation path/to/file1 path/to/file2 path/to/dir path/to/zip
Savings (browser/Savings.sol):
  Success!
  Compiled with Solidity 0.6.11
  https://solc-bin.ethereum.org/wasm/soljson-v0.6.11+commit.5ef660b1.js
  https://solc-bin.ethereum.org/linux-amd64/solc-linux-amd64-v0.6.11+commit.5ef660b1
  Use ``sourcify-validation --standard-json browser/Savings.sol:Savings path/to/file1 path/to/file2 path/to/dir path/to/zip | solc --standard-json -`` to recompile.
OtherContract (browser/OtherContract.sol):
  Success!
  Compiled with Solidity 0.6.11
  https://solc-bin.ethereum.org/wasm/soljson-v0.6.11+commit.5ef660b1.js
  https://solc-bin.ethereum.org/linux-amd64/solc-linux-amd64-v0.6.11+commit.5ef660b1
  Use ``sourcify-validation --standard-json browser/OtherContract.sol:OtherContract path/to/file1 path/to/file2 path/to/dir path/to/zip | solc --standard-json -`` to recompile.
```
Not totally happy with the naming of the option, though. Also, if there is only one contract, it would be nice to allow the contract name to be omitted.

**Comment by FabijanC** [comment]
Ok, thank you for the clarification, makes sense. And regarding the naming of the option, I had already chosen the same one (-j, --standard-json); guess I might want to think of something else.
