### ISSUE TITLE
Dialog box not completely visible if the message is too long

### ISSUE THREAD

**Issue by FabijanC** [ethereum/sourcify#258]
![image](https://user-images.githubusercontent.com/28579396/95212677-3eabf600-07ee-11eb-8257-36487de3d19c.png)

The dialog box containing information about validation/verification of the uploaded files isn't displayed optimally. It is expected that the amount of text will increase because the server is planned to return information about each problematic file.
The screenshot was made while using Google Chrome (Version 85.0.4183.121 (Official Build) (64-bit)) on a 15.6'' laptop, and the issue remains in Mozilla Firefox. The issue is not present when using a larger monitor (23'').

**Comment by ligi** [comment]
why the discussion label here? Also we should add https://github.com/ethereum/sourcify/labels/discussion to our weekly calls
