### ISSUE TITLE
Research sourcify support for layer 2 solutions

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/sourcify#277]
Solutions that are interesting in this area:
* optimism (https://optimism.io/)
* xDAI (https://www.xdaichain.com/)

**Comment by edisinovcic** [comment]
@Jakic007 can you do a quick research on optimism and how can we support it via sourcify.
I will do one on xdai.

**Comment by ligi** [comment]
xDAI should be easy - just another chain/chainId - can be treated like we treat the other networks as far as I see
with optimism I would wait until they really launch.

**Comment by edisinovcic** [comment]
https://www.xdaichain.com/for-developers/developer-resources#json-rpc-endpoints

**Comment by Jakic007** [comment]
Optimism has still not launched mainnet and they are currently only doing some small private testnets.
I am following them on their discord server to see when they launch.
