### ISSUE TITLE
Research truffle-plugin-verify

### ISSUE THREAD

**Issue by Jakic007** [ethereum/sourcify#289]
https://github.com/rkalis/truffle-plugin-verify

**Comment by FabijanC** [comment]
To better understand the implementation, one can refer to: [How Truffle plugins should look](https://www.trufflesuite.com/docs/truffle/getting-started/writing-external-scripts#creating-a-custom-command-plugin).
The implementation relies on Etherscan API, with required parameters available at: [link](https://etherscan.io/apis#contracts).
Given a contract name, this is what the plugin does, assuming all the Truffle artifacts are present in the usual Truffle hierarchy:
- get metadata and other build info from the corresponding .json file
- perform a GET request to Etherscan API to retrieve constructor arguments that were used when the contract was built
- perform a POST request to Etherscan API with the address, source code and constructor arguments of the contract
- every 1000 ms try and see if the contract has been verified and published to [Etherscan Verified Contracts](https://etherscan.io/contractsVerified).

Notable differences between Sourcify and Truffle Plugin Verify, apart from the obvious fact that the plugin supports only contracts built using Truffle:
- constructor arguments fetching prior to verification
- solc is not directly used; this is delegated to Etherscan
- does not rely on a repository of its own, but [the one used by Etherscan](https://etherscan.io/contractsVerified).
