### ISSUE TITLE
Make checkByAddress case insensitive

### ISSUE THREAD

**Issue by Jakic007** [ethereum/sourcify#295]
Ethereum addresses are in HEX and they are case insensitive. Right now we are storing contracts inside our repository named by exact address that was sent to the server and later checks will not return match if we replace some capitals with lower cases or the other way around.

Proposed solution to this problem:

In findByAddress method list a tree for the desired chain and try to match case insensitive address.

**Comment by ligi** [comment]
yea it should be normalized. Maybe normalizing to ERC-55 is another option. This is what we do in ethereum-lists/chains

**Comment by Jakic007** [comment]
@ligi Thats what I did in the end. Seems like the best solution because there is already provided method in the web3 library that converts any address to checksumAddress. 
https://web3js.readthedocs.io/en/v1.2.11/web3-utils.html#tochecksumaddress
