### ISSUE TITLE
UX: error dialog should be scrollable 

### ISSUE THREAD

**Issue by ligi** [ethereum/sourcify#302]
currently cannot scroll the error - it scrolls the background 
![Selection_269](https://user-images.githubusercontent.com/111600/98156066-8d28df00-1ed7-11eb-8d5e-b93e3f665031.png)

**Comment by FabijanC** [comment]
This has already been addressed here: https://github.com/ethereum/sourcify/issues/258

**Comment by ligi** [comment]
cool - but unfortunately not addressed - just described. But I would maybe even keep both open - on says that it should be scollable (here) and one says it should be fully visible. Also then it is more on the top the other one approaches a month of staleness ;-)

**Comment by FabijanC** [comment]
Yeah, thanks for bringing this topic up.
