### ISSUE TITLE
Stats endpoint

### ISSUE THREAD

**Issue by Jakic007** [ethereum/sourcify#303]
Create an endpoint on server that returns number of verified contracts per chain.

**Comment by ligi** [comment]
wonder if we need an endpoint or we can make it part of the metadata in the repository

**Comment by edisinovcic** [comment]
> wonder if we need an endpoint or we can make it part of the metadata in the repository

so the users would then fetch a file instead of the api?

And again we would need to calculate whole statistics every time we save a file and update a timestamp?

**Comment by ligi** [comment]
> so the users would then fetch a file instead of the api?

yea - IMHO this can be more decentralized

> And again we would need to calculate whole statistics every time we save a file and update a timestamp?

this is one way. But how would you do it with the endpoint - you also need to cache it right - you do not want to count on invocation of this endpoint I guess

**Comment by Jakic007** [comment]
We can use the manifest file to keep the stats about the repository which can be fetched by GET request to http://contractrepo.komputing.org/manifest.json
