### ISSUE TITLE
Research Gnosis wallet

### ISSUE THREAD

**Issue by Jakic007** [ethereum/sourcify#313]
We have to see how this wallet interacts with contracts and figure out what is the best way to add sourcify as a plugin to it.
Goal is to show to user if contract that he is trying to interact with is verified or not.
If it is, he can fetch the source files from the ipfs repository.

**Comment by Jakic007** [comment]
https://help.gnosis-safe.io/en/articles/3738081-contract-interactions

**Comment by edisinovcic** [comment]
Research has been done and implementation with transaction builder has been built.
