### ISSUE TITLE
Improve @ethereum-sourcify/core utils methods

### ISSUE THREAD

**Issue by Jakic007** [ethereum/sourcify#315]
All of the methods that are converting chain IDs to chain names and vice versa inside `utils.ts` are using network parameter from the `chains.json` file that is not unique across different chains.
This could start being problematic once we increase the number of supported chains.
Also, we have to be careful making changes to these methods because that could introduce some breaking changes to our server API.

**Comment by FabijanC** [comment]
Closing this issue because the `networkID` parameter is not used, only `chainID`.
