### ISSUE TITLE
Support verification with source only

### ISSUE THREAD

**Issue by ligi** [ethereum/sourcify#323]
I think it could be nice if the verification-ui would support verification if you only have the solidity files. Means it would run solc in the browser like remix is doing. 
UX for it could look like this:
 * in the message "metadata.json not found" offer the option (generate in browser)
 * ask for solidity version and optimization settings
 * compile in the browser
 * verify with the generated metadata

Had this idea when verifying the beacon chain. I had no metadata - just the solidity file and the settings. So there was a bit of a barrier (downloading the correct solitity version, compiling, splitting the metadata) I think this workflow could be improved like described above and the barrier to verifying contracts could be lowered this way.

**Comment by kuzdogan** [comment]
Related to this I think https://github.com/ethereum/sourcify/issues/319 Closing
