### ISSUE TITLE
Consider validating files on the client side

### ISSUE THREAD

**Issue by Jakic007** [ethereum/sourcify#328]
The idea is to start validating dropped files immediately and notify user if something is missing before sending request to the server.
That would lower the load on the server side but possibly degrade performance in the browser when user drops big compressed files.
To support that, validation service should be enhanced with better input file checks and stop the flow for certain files and situations.

**Comment by edisinovcic** [comment]
Currently it seems that UI rewrite will be done and this will not be needed. Reopen if it changes.
