### ISSUE TITLE
Contracts that verify on etherscan but do not on sourcify

### ISSUE THREAD

**Issue by wighawag** [ethereum/sourcify#329]
these 2 contracts on rinkeby :
0x68332DE350a4348A31Cfea48E42a31862abB5d7d  : https://gist.github.com/wighawag/c29271d95720d83550343d53ad1dd72c
0xAA407a403d38cEB8f47964d8aaF2De9C5EDFDF7e :  https://gist.github.com/wighawag/207a0eb14db34495b50b1b097f400b35

fails to verify on sourcify. but they verify fine on etherscan with the same metadata.

**Comment by FabijanC** [comment]
I used [this decompiler](https://ethervm.io/decompile) on the bytecode deployed at 0x68332DE350a4348A31Cfea48E42a31862abB5d7d and on the bytecode generated by recompiling [the provided metadata file](https://gist.github.com/wighawag/c29271d95720d83550343d53ad1dd72c). There seem to be slight differences in the source files that were originally compiled and the ones you provided in the metadata. Maybe you can compare the real sources with those from metadata. Perhaps use [this diff](https://gist.github.com/FabijanC/0e79c7a158ce710d683cb5c748d33ff9) for clues.

**Comment by wighawag** [comment]
@FabijanC Thanks, the diff is actually very useful, The issues seems to be that sourcify does not support `immutable` state var.

the diff  matches exactly the constructor arguments that are used to set these immutable values

Note that the metadata string comes directly from solc and is saved as is. I can regenerate it  anytime. the repo is https://github.com/wighawag/transfer-gateway.

**Comment by Jakic007** [comment]
Yes, it is true that we don't support immutable state variables but it is something that we are planning to do in the near future.
Issue is already here so you can subscribe to see when it will be resolved: https://github.com/ethereum/sourcify/issues/194

**Comment by wighawag** [comment]
@Jakic007 thanks, that explains it
