### ISSUE TITLE
Return different status for the already verified contract through /verify API endpoint

### ISSUE THREAD

**Issue by vbaranov** [ethereum/sourcify#334]
Currently, `/verify` API endpoint returns 

```
{
    "result": [
        {
            "address": "0x...",
            "status": "perfect"
        }
    ]
}
```

even if someone tries to verify with wrong verification data already verified contract.

I suppose this API endpoint should return a different status, kinda `"status": "already verified"`, in case of contract has been previously verified.

**Comment by Jakic007** [comment]
That is correct. If the contract with the provided address is already verified and its sources are present in the repository, server will not recompile and recheck provided sources from the request. 
I agree that this status "perfect" is misleading in this case. Thanks for your submission, we will make some changes after we discuss what is the best approach.
