### ISSUE TITLE
UI Iteration

### ISSUE THREAD

**Issue by franzihei** [ethereum/sourcify#345]
As discussed, I thought about how we could iterate on the UI. 

I think it would make sense to separate more clearly between:
- About / What is Sourcify info
- Verifier
- Fetcher
- Important links
- Other stuff

I started to brainstorm alternatives in the [Figma file](https://www.figma.com/file/IJi7BaUuvAfhrB8rUsFTIy/sourcify?node-id=0%3A1). 

![image](https://user-images.githubusercontent.com/41991517/103654897-caa4f980-4f66-11eb-806f-414e2ff20801.png)

To properly outline everything and make sense of where what needs to go I need a better understanding of all the possible outcomes / errors during the verification process (a bit like a flow chart). Happy to simply jump on a call to collect all possible user flows and then implement it further in case this direction makes sense. 

I think in any case it would be very useful to come up with a user flow chart to have the same understanding of the process. Happy to create one as soon as I have all the knowledge. :)

**Comment by Jakic007** [comment]
@franzihei Could you please upload this picture somewhere else and share the url? Github compressed it so some text is not visible for me.

**Comment by franzihei** [comment]
it's in the figma file if that helps? :) @Jakic007

**Comment by Jakic007** [comment]
Yes, I have realized that immediately after posting that comment so I have removed it :+1: 
Thanks :)

**Comment by franzihei** [comment]
Adding the user flow we discussed today for the verifier here for archive purposes. :) 

![image](https://user-images.githubusercontent.com/41991517/103784263-065cc380-503a-11eb-9ffe-8a093e25f345.png)

**Comment by franzihei** [comment]
Updated the UI in the Figma, feel free to have a look and let me know your thoughts or if you have any questions. :)

**Comment by franzihei** [comment]
Updated the [figma file](https://www.figma.com/file/IJi7BaUuvAfhrB8rUsFTIy/sourcify?node-id=0%3A1) according to what we discussed yesterday. :) 

Just missing the "stats/graphs" part, but I can work on something as soon as I have some numbers to play with. Could you send me some numbers (e.g. contracts verified with time stamps (over time)) etc.?

Let me know if there's anything else I am missing!

![image](https://user-images.githubusercontent.com/41991517/104307972-38ee3c80-54d0-11eb-8703-487f9f35a2ce.png)

**Comment by Jakic007** [comment]
Right now we just have the number of full matches and partial matches in different networks.
You can see that here: [stats.json](https://repo.sourcify.dev/stats.json)

So with those stats we can only have something like this:
![Screenshot from 2021-01-12 12-54-04](https://user-images.githubusercontent.com/32742825/104311378-67224b00-54d5-11eb-98a3-3a88eea979de.png)

We can discuss this next time, but I think that it would be great to have regular line graph that would show the number of contracts verified per day for the last month or three months for all supported networks. 
We would have to research how to implement that but it should be possible.

**Comment by chriseth** [comment]
Is there a way to comment on figma? Could you make the "drop zone" a little smaller and add the list of uploaded files below it?

**Comment by franzihei** [comment]
Yes you can comment by switching into comment mode in the top nav bar (click on the speech bubble) and then clicking on the element where you want to leave a comment: 

![image](https://user-images.githubusercontent.com/41991517/104428184-757b7000-5584-11eb-8c34-9905c9d1deb8.png)

I created a draft for what you were suggesting, but I don't think it will look that good design wise... Or did I not understand you correctly?

![image](https://user-images.githubusercontent.com/41991517/104430554-1bc87500-5587-11eb-88fe-794ac9ec706b.png)
