### ISSUE TITLE
Replace the repository URL in the UI

### ISSUE THREAD

**Issue by Jakic007** [ethereum/sourcify#360]
URL is still pointing to https://contractrepo.komputing.org/ instead of https://repo.sourcify.dev/

**Comment by FabijanC** [comment]
in README.md as well?

**Comment by Jakic007** [comment]
Yes

**Comment by FabijanC** [comment]
and what about `monitor_ci.js`?

**Comment by Jakic007** [comment]
We can change it there too but that is not as important since it is only used internally. Old URL will still work.
