### ISSUE TITLE
Use unmodified chains.json

### ISSUE THREAD

**Issue by Jakic007** [ethereum/sourcify#363]
It would be easier for maintenance to use unmodified https://chainid.network/chains.json and use only networkID as identificator instead of network names.
Also, we can have another `supported.json` that will define which chainID will be monitored or supported for verification.

**Comment by ligi** [comment]
Please don't use the networkID - use chainID

**Comment by Jakic007** [comment]
Yes, sorry. I was thinking of chainID but I wrote incorrectly.

**Comment by ligi** [comment]
No need to be sorry as long as we use the chainID ;-)

**Comment by FabijanC** [comment]
Related: https://github.com/ethereum/sourcify/issues/315
