### ISSUE TITLE
Save fetched solc to /tmp directory

### ISSUE THREAD

**Issue by Jakic007** [ethereum/sourcify#370]
How to reproduce:
Desired solc version is available locally but server does not have permission to read it.
You can replicate that by using `chmod` and removing all permisions while still keeping the original file name.

Solution:
Instead of throwing error, fetch the correct solc from github.
![Screenshot from 2021-02-03 12-55-49](https://user-images.githubusercontent.com/32742825/106744044-7c475100-661f-11eb-9aa1-fe88e4f6ea1a.png)

**Comment by FabijanC** [comment]
How about using `chmod` within the program? [appropriate fs function](https://nodejs.org/api/fs.html#fs_fs_chmodsync_path_mode)

**Comment by Jakic007** [comment]
Update:
This is happening only when our server is run with docker-compose because it has read-only flag for volume mount to prevent modifying host system in any way.

Solution:
If `solc` is available and accessible, use it. If we need to fetch it, fetch it to the `/tmp` directory. It is okay to write there for all users.
