### ISSUE TITLE
Failing verification "Cannot read property '<contractPath>' of undefined"

### ISSUE THREAD

**Issue by wighawag** [ethereum/sourcify#407]
This was reported on hardhat-deploy repo : https://github.com/wighawag/hardhat-deploy/issues/78

hardhat-deploy do not preprocess the metadata in any way and since the issue is actually an error from sourcify, the error must come from somewhere in sourcify.

you can try to submit the same details on https://sourcify.dev/ 

you get :

`Cannot read property 'contracts/RandomNumberConsumer.sol' of undefined`

Network: Mumbai Matic Testnet
metadata file : https://cloudflare-ipfs.com/ipfs/QmY7bQE2ctHxqdUibQGr3ZiShfdPx8LbH4bsA57vygoWNT
Contract address: 0x7c90F0C9Eb46391c93d0545dDF4658d3B8DF1866

**Comment by FabijanC** [comment]
Explanation: https://github.com/wighawag/hardhat-deploy/issues/78#issuecomment-786918858
