### ISSUE TITLE
Comparing metadata hash as a means of bytecode matching

### ISSUE THREAD

**Issue by FabijanC** [ethereum/sourcify#420]
Contracts compiled with solc have a CBOR-encoded metadata hash (IPFS or Swarm) at the end of the resulting bytecode (unless explicitly specified not to include any metadata hash). Currently, Sourcify compares the recompiled and deployed bytecode (including the metadata hashes) and marks a *full match* **only if** the metadata hashes are equal. If bytecodes are equal, but their metadata hashes differ, this is a *partial match*.

Is there a case when two bytecodes have equal metadata hashes, but not the same bytecode? If this is never the case, then a mere metadata hash comparison would suffice in determining whether the recompiled contract fully matches the deployed contract. 

Also, this would enable detecting a *full match* even in the case of a contract with immutable variables (#194, #111), because the recompiled contract has the same metadata hash (if specified), despite not having immutable variables initialized.

This would not cover the case of *partial matches*, but Sourcify as a project has always put more emphasis on *full matches* (e.g. server endpoints at /verify and /check-by-addresses (used by UI) only consider full matches when checking if a contract is already verified).

**Comment by chriseth** [comment]
This should be true, unless someone wants to deliberately fool us, so I think we should still do the full comparison.
