### ISSUE TITLE
Can't verify a contract from matic using the hardhat-deploy plugin - "Recompilation error"

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/sourcify#422]
```
hardhat --network  maticTest sourcify
verifying Fellowship (0xaB40451ee33160c2B88aC0a2ab1B66Db0baB12EB on chain 80001) ...
{"error":"Recompilation error"}
```

Here is the meta file

https://github.com/krasi-georgiev/fellowship/blob/deployment-plugin/deployments/maticTest/solcInputs/4e8148b38abdbfc2f152ac1be48d8544.json
https://github.com/krasi-georgiev/fellowship/blob/deployment-plugin/deployments/maticTest/Fellowship.json

getting the same error when using https://sourcify.dev/

**Comment by wighawag** [comment]
Note the metadata file itself is embeded in the json mentioned above, see : https://github.com/krasi-georgiev/fellowship/blob/751910111f7df90432f0725270b5ab37cad4e8fd/deployments/maticTest/Fellowship.json#L619

**Comment by FabijanC** [comment]
Thank you for pointing out this issue, it seems to be caused by corrupt binaries of Solidity compiler for versions 0.8.0 and higher. This issue will be overtaken by #423.
