### ISSUE TITLE
Upgradeable contracts support

### ISSUE THREAD

**Issue by Jakic007** [ethereum/sourcify#448]
Check if we support contracts that are using upgradeable openzepellin libraries.

 https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable#use-upgradeable-libraries

**Comment by FabijanC** [comment]
I deployed a couple of dummy contracts on Rinkeby; both were successfully verified, with Sourcify repo links provided:
- [The first](https://repo.sourcify.dev/contracts/full_match/4/0xE449F5B7b959315806812F7cE43Ca7F13DA036d0/sources/contracts/) holds a reference to an IERC20Upgradeable token
- [The second](https://repo.sourcify.dev/contracts/full_match/4/0x494e1D48dcD8423D7E02089372b1E0DEb9352B57/) implements IERC20Upgradeable

Still unsure if this was the objective of this little research.

**Comment by chriseth** [comment]
So you performed and upgrade and both the version before the upgrade and after the upgrade was verifiable?
I guess the main problem here is to recognize proxies as such at the point of transaction validation and display the correct natspec and source to the user, i.e. the one that the proxy contract points to. But maybe this is a bit out of scope for now.
