### ISSUE TITLE
contract verification for Polygon/Matic in Hardhat

### ISSUE THREAD

**Issue by AuroraLantean** [ethereum/sourcify#475]
Hi, I was referred to Sourcify by Hardhat support team about contract verification on Polygon/Matic
https://github.com/wighawag/tutorial-hardhat-deploy

How can I use this to verify deployed contracts in command line?
Here is what I did:
$ yarn hardhat --network polygonmumbai sourcify
... yarn run v1.22.5
.../node_modules/.bin/hardhat --network polygonmumbai sourcify
verifying Token (0x81931C659f14219110475a28EB57c656f0f1255e on chain 80001) ...
 => contract Token is now verified
Done in 9.79s.

https://explorer-mumbai.maticvigil.com/address/0x81931C659f14219110475a28EB57c656f0f1255e/contracts
BUT it is still not verified!

Here is my repo: https://github.com/AuroraLantean/hardhatDeploy
I cloned https://github.com/wighawag/tutorial-hardhat-deploy , then used it to deploy and try to verify my contract on PolygonMumbai. Please help. Thank you!

**Comment by FabijanC** [comment]
When you verify a contract on Sourcify, its sources are published in [the Sourcify repository](https://repo.sourcify.dev) which can be checked from [the Sourcify UI](https://sourcify.dev). [The explorer which you are using](https://explorer-mumbai.maticvigil.com) is not connected to Sourcify, so it doesn't know when a contract was _sourcified_.
