### ISSUE TITLE
Migrate h5ai to sourcifyeth org

### ISSUE THREAD

**Issue by Jakic007** [ethereum/sourcify#482]
From: https://github.com/blockchain-it-hr/h5ai-nginx/tree/cd5d75735a0f734b3346bbd41d38444b7dd2e9c5

**Comment by kuzdogan** [comment]
Is this still relevant?

**Comment by Jakic007** [comment]
Here: https://github.com/ethereum/sourcify/blob/staging/.gitmodules
You can see that it still fetches that submodule from the blockchain-it oranization. You can just fork that under sourcifyeth and change the URL for the submodule.

**Comment by kuzdogan** [comment]
See https://github.com/ethereum/sourcify/commit/26495b143f9270bf8897d2e6d261c7b5003e7e91
