### ISSUE TITLE
Link to smart contract repo is broken with a security error

### ISSUE THREAD

**Issue by shoenseiwaso** [ethereum/sourcify#484]
This link: https://contractrepo.komputing.org/

Found in this blog post: https://blog.soliditylang.org/2020/06/25/sourcify-faq/

Leads to this:

![image](https://user-images.githubusercontent.com/5861379/122396783-5067af00-cfb3-11eb-9449-17184c3f22b0.png)

**Comment by shoenseiwaso** [comment]
Ah, maybe it's supposed to point here instead: https://repo.sourcify.dev/

**Comment by Jakic007** [comment]
Yes, it is old URL. Please use https://repo.sourcify.dev/ now.
