### ISSUE TITLE
Sourcify repository Dappnode package

### ISSUE THREAD

**Issue by DeFiYaco** [ethereum/sourcify#496]
To improve decentralization and availability of our repository, we can create a DNP that anybody can install on their dappnode machine and have the entire sourcify repository on their local machine. It will regularly fetch new contracts and repin the repository to make it available for others.

Features:
- one click install service
- auto pinning ipfs repository
- contract fetcher

**Comment by ligi** [comment]
for context: https://github.com/ethereum/sourcify/issues/163

**Comment by marcocastignoli** [comment]
I actually discussed about the same thing with a guy from Dappnode druing DEVCON VI. He told me that there is already a pinning service on Dappnode and we discussed about having a list of "ethical" repo, that incentivizes the users to pin those files. Ofc one of the repos will be Sourcify
