### ISSUE TITLE
Research Filecoin Plus Program Conditions and How to Apply

### ISSUE THREAD

**Issue by FabijanC** [ethereum/sourcify#506]
https://docs.filecoin.io/store/filecoin-plus/

**Comment by kuzdogan** [comment]
Is here the idea to add Filecoin chain support or to make use of the Filecoin network for storage?

**Comment by FabijanC** [comment]
Not sure, this is where it was first mentioned: https://github.com/sourcifyeth/org/issues/63

**Comment by kuzdogan** [comment]
cc: @franzihei @ligi

**Comment by franzihei** [comment]
It's about the latter, making use of the Filecoin network for storage. Apparently, we could apply for the filecoin plus program (since our data is valuable) and, if accepted, would get an "allowance" that we could spend on the Filecoin network to have our data hosted there, similar to IPFS.

**Comment by franzihei** [comment]
It looks like rather a complex governance process to get there though, so we should imo only do it if we can't solve the IPFS issues. https://github.com/filecoin-project/notary-governance/issues
