### ISSUE TITLE
Periodically check RPC node availability in Monitor

### ISSUE THREAD

**Issue by FabijanC** [ethereum/sourcify#510]
Currently (actually just on `staging` branch, but soon to be merged to `master`), this check is performed only when starting the monitor on each chain. A check could be performed e.g. every hour that would see if a more preferable node has become available. With current implementation, one would need to restart the containers in order to potentially change the node used.

<sub>View in Huly <a href="https://app.huly.io/guest/w-kaanuzdogan-sourcify-65d30de0-75121c5c6c-fd615e?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWU1N2RjZjhiNmVjZDA0ZDYyZDFlNTQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2FhbnV6ZG9nYW4tc291cmNpZnktNjVkMzBkZTAtNzUxMjFjNWM2Yy1mZDYxNWUiLCJwcm9kdWN0SWQiOiIifQ.m6Y_bsB7UJrkeskKD81YNtmcsUtEB07AgPppWjLQmJY">HI-282</a></sub>

**Comment by kuzdogan** [comment]
Closing as now we instead request from all multiple RPCs available and return the first response https://github.com/ethereum/sourcify/blob/da07f8612eea5614536adf7e7b627d9a56192bdb/services/verification/src/utils.ts#L65
