### ISSUE TITLE
increase receive buffer size

### ISSUE THREAD

**Issue by ligi** [ethereum/sourcify#518]
digging a bit more into our IPFS problem I saw this in the logs:
`2021/09/03 13:10:15 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.`

should not be our core problem here - we should still address it

**Comment by kuzdogan** [comment]
Can we check the buffer sizes on the servers? `sudo sysctl net.core.rmem_max`

IPFS error asks for 2 MB and the issue recommends a ~2.5 MB buffer `sudo sysctl -w net.core.rmem_max=2500000`

https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size

**Comment by ligi** [comment]
seems on komputing it was even larger before:
```
root@komputing:/home/ligi# sudo sysctl net.core.rmem_max
net.core.rmem_max = 10485760
root@komputing:/home/ligi# sudo sysctl -w net.core.rmem_max=2500000
net.core.rmem_max = 2500000
```
on gather it was actually increased this way:
```
root@gather:/home/gather# sysctl net.core.rmem_max
net.core.rmem_max = 212992
root@gather:/home/gather# sysctl -w net.core.rmem_max=2500000
net.core.rmem_max = 2500000
```

**Comment by kuzdogan** [comment]
Closing as the warning is no more shown on container start in gather, thanks
