### ISSUE TITLE
"Adding support for new chains"-Policy

### ISSUE THREAD

**Issue by franzihei** [ethereum/sourcify#525]
## Problem

We are receiving an increasing amount of requests to add support for more chains to the Sourcify service. Since that has an impact on our server capacities and UI limitations etc. we should think of a consistent policy of how we want to deal with new chain requests coming in.

## Solution

- [ ] Come up with a transparent policy which chains we support and how. 
- [ ] Give other chains an easy way and comprehensive docs to set up their own customized Sourcify instance.

**Comment by ligi** [comment]
advantages of being radically inclusive:
 - visibility for sourcify
 - no need to decide and maybe argue why a chain is not incuded
 - _maybe_ contributions upstream - chances are at least higher they contribute upstream when we run their chains then when they run some forks

disadvantages:
 - more compute/storage/bandwidth required in our infra
 - maybe UX implications (but should be able to be mitigated)

I would tend to be radical inclusive here - so any chain that fulfills some basic requirement - e.g. RPC that respects some spec (maybe we can even be a forcing function here) should be included.

**Comment by jyap808** [comment]
Option 1 would be satisfactory.

Speaking on behalf of other networks, we don’t have Etherscan Verify so would like to utilize Sourcify for public verification. Text file hosting costs should be minimal with just option 1.

A lot of services in the crypto industry favor and service only the most highly funded chains. Would like to see Sourcify not go this route.

PR #524

Thanks for the follow up comments @ligi

**Comment by kuzdogan** [comment]
It would also be nice to have a semi-structured onboarding process such as providing the steps how to have the chain included: which files to change and how to open a PR + providing test contracts (with address+source+metadata) etc. This would fit whichever route we decide to take.

**Comment by kuzdogan** [comment]
Added how others can [request chain support](https://docs.sourcify.dev/docs/chain-support/) in a structured way with tests, as well as how to [run Sourcify](https://docs.sourcify.dev/docs/run-locally/) to docs. 

I guess we settled on not rejecting networks as long as they can provide a test contract and their network + the RPC works. Closing.
