### ISSUE TITLE
UI / Website Kickoff Workshop

### ISSUE THREAD

**Issue by franzihei** [ethereum/sourcify#536]
## Problem?

- The current UI we have at sourcify.dev is outdated and does not have an optimal UX verification flow.
- We have no proper product website where we explain what Sourcify is, and how it works.
- There already has been done some work to improve it, but the team has changed and issues and figma files are outdated / not specific enough.

## Solution

Let's have a workshop where we talk about:

- What content should go on the "product website" and who is responsible
- How the product website will look like / rough structure
- How the verification flow UI will look like (logic and design)
- How the "fetching" flow UI will look like (logic and design)

## Outcome

- Direct outcome of the workshop: Have a joint understanding what we want to build and what is needed.
- Indirect outcome: After the workshop, have one unified document (figma file) which shows what we want to implement.
- Indirect outcome: After the workshop, have clear issues which define how to implement the new product website and UI.

### Related Issues

https://github.com/ethereum/sourcify/issues/336
https://github.com/ethereum/sourcify/issues/345
https://github.com/ethereum/sourcify/issues/264

### Related Figma Files

- Old UI flow (and first ideas how to update it): https://www.figma.com/file/N59JoAXcaAZVHPXG1ayEfg/sourcify?node-id=0%3A1
- Product website and UI draft by Franzi: https://www.figma.com/file/IJi7BaUuvAfhrB8rUsFTIy/sourcify?node-id=0%3A1
- Improvement ideas by Kaan: https://www.figma.com/file/zH3nKg20GhVtw1m7wKJrJZ/Untitled?node-id=0%3A1

**Comment by kuzdogan** [comment]
Also noting: The contract creation feature and its interface will be depending on the UX and the flow #507

**Comment by franzihei** [comment]
## Summary of the Workshop

### What information should be displayed on the product website (aka landing page)?

- Hero section with tagline (short subtile) and visualization/graphic
- CTAs / Buttons to the core product
  - Verifier
  - Fetcher
  - Contract repository
- Long form info about Sourcify
- Status page
- Matrix of chains and what is supported on which chain (maybe combined with status monitor)
- Stats/counter for verified contracts
- Showcase and links of projects using Sourcify
  - Wallets
  - Popular verified contracts
  - Libraries and tools
- FAQs
- Highlight section on how to use Sourcify programmatically / API
- Links:
  -  Contact info
  - Socials (Twitter, chat)
  - Github repos
  - Contract repo
  - IPFS/IPNS gateway
  - Developer docs
  - Talks and blog posts

### UI flows (to be translated into Figma wireframe)

![image](https://user-images.githubusercontent.com/41991517/135263018-4127c06d-d190-42ee-8024-a6c71e1240dc.png)
![image](https://user-images.githubusercontent.com/41991517/135263031-84b7c06c-3760-45e8-b84b-daf8d977959f.png)

### Other photos

![image](https://user-images.githubusercontent.com/41991517/135263009-3c689a01-9dd8-44f5-8e89-95834aca74f6.png)

## Next steps

**Product website/landing page**
- [ ] Translate product website items into wireframe on Figma

**UIs**
- [ ] Translate verification UI flow into wireframe on Figma
- [ ] Start backend adjustments for verification flow
- [ ] Translate fetcher UI flow into wireframe on Figma
- [ ] Start backend development/adjustments for fetcher functionality
- [ ] Discuss structure/UI for contract repository

**Comment by kuzdogan** [comment]
Links to hi-res images:
https://photos.app.goo.gl/nDi4cRJeak1Qj8fa9
https://photos.app.goo.gl/aQQrtNXPtE6Dywqc8
https://photos.app.goo.gl/92wXujEyn6pZUizKA
