### ISSUE TITLE
Implementing an npm module for contract call decoding

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#538]
Idea
-----------------------
Implement an npm module for decoding a contract call into a more human-readable format using the ABI and userdoc ([NatSpec](https://docs.soliditylang.org/en/latest/natspec-format.html)) in the metadata of the contract.

The main functionality would take raw tx input data and contract address as input and human-readable contract call as output. If available, show the parameters with the NatSpec 

Initial implementation and development is at branch [contract-call-decoder](/ethereum/sourcify/tree/contract-call-decoder)

Example
----------------
Example on contract [0x7492F518e41D8610a677Fe84b39223b746449979](https://rinkeby.etherscan.io/address/0x7492F518e41D8610a677Fe84b39223b746449979) on Rinkeby.:
```solidity
/// @notice Creates `_amount` token to `_to`. Must only be called by the owner (MasterChef).
    function mint(address _to, uint256 _amount) public onlyOwner {
        _mint(_to, _amount);
        _moveDelegates(address(0), _delegates[_to], _amount);
    }
``` 

Calling `mint('0xAA6042aa65eb93C6439cDaeBC27B3bd09c5DFe94', 1000000000000000000)`

Tx input data in hex
```
0x40c10f19000000000000000000000000aa6042aa65eb93c6439cdaebc27b3bd09c5dfe940000000000000000000000000000000000000000000000000de0b6b3a7640000
```

if userdoc is not available should return something like:
```
calling function mint(address _to, uint256 _amount) with:
{
  _to: '0xAA6042aa65eb93C6439cDaeBC27B3bd09c5DFe94'
  _amount: 1000000000000000000
}
```

If available, should return also the documentation in addition to above: 
```
Creates 1000000000000000000 token to 0xAA6042aa65eb93C6439cDaeBC27B3bd09c5DFe94. Must only be called by the owner (MasterChef).
```

Usage
-------------------
The module can be a class that takes two parameters in constructor: an RPC and an optional IPFS/Swarm Gateway (can default to ipfs.io/ipfs/ and swarm-gateways.net).
```js
import Decoder from 'contract-call-decoder'

const decoder = new Decoder('https://rinkeby.infura.io/v3/<Access-Token>', { ipfs: 'https://ipfs.infura.io/ipfs/' })
const decodedTx = decoder.decodeContractCall('0x40c10f19000000000000000000000000aa6042aa65eb93c6439cdaebc27b3bd09c5dfe940000000000000000000000000000000000000000000000000de0b6b3a7640000', '0x7492F518e41D8610a677Fe84b39223b746449979')
```

- [x] Extract the IPFS/Swarm hash of metadata file from the hex tx input
- [x] #539 
- [x] #541
- [x] #542
- [ ] #590 590

**Comment by marcocastignoli** [comment]
I would close this and move the discussions on the repo: [sourcifyeth/sourcify-metamask-snap](https://github.com/sourcifyeth/sourcify-metamask-snap)
