### ISSUE TITLE
very long loading times for repo

### ISSUE THREAD

**Issue by ligi** [ethereum/sourcify#552]
I think it is coming from the sidebar and tbh I do not see many use cases for switching between chains/contracts here anyway. Maybe we can speed things up by removing it or setting the root to the contract?

![image](https://user-images.githubusercontent.com/111600/136661737-53390029-84af-4ec6-8a79-9259ea2140a7.png)

**Comment by kuzdogan** [comment]
I tried removing the sidebar (Inpect --> Delete DOM Element) and still it is taking too long to when I click say `contracts/full_match/1`. There are over 20k directories and I think we need some kind of lazy loading or paging. I will look if it is possible with the `h5ai` library we are using or if there's another library that is better suited for our use case.

**Comment by kuzdogan** [comment]
Should have been resolved with 6753be6165c0770b7337ea949b084bd0df3b6356

See example https://repo.sourcify.dev/contracts/full_match/1/0x805880F4C528842984c4f6E1931d9448b26bB4eA/
