### ISSUE TITLE
Have more IPFS nodes providing our content

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#560]
We are currently the only provider for the IPFS repo for most of the content, except those cached or pinned by gateways.

It would be nice if we also pin the content via Filecoin for redundancy. Check how much it would cost and how to do it.

[Pinata costs](https://www.pinata.cloud/pricing) $0.15/gb monthly.

<sub>View in Huly <a href="https://app.huly.io/guest/w-kaanuzdogan-sourcify-65d30de0-75121c5c6c-fd615e?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWU1N2U0MjhiNmVjZDA0ZDYyZDI0Y2IiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2FhbnV6ZG9nYW4tc291cmNpZnktNjVkMzBkZTAtNzUxMjFjNWM2Yy1mZDYxNWUiLCJwcm9kdWN0SWQiOiIifQ.cSDxxHJNdROy2OfBIM8kFYvEF1hH9hHPpiwoymRqSKk">HI-386</a></sub>

**Comment by wmitsuda** [comment]
Something a little unrelated, but that is worth being mentioned, Sourcify updates the IPNS hash hourly, and due to contracts being verified constantly, the root hash also changes constantly.

Even if you pin by ipns, I'm pretty sure it actually solves the name and pin the hash at **THAT** moment (couldn't find any doc saying the opposite). It means that people wanting to mirror Sourcify entire repo must ensure they put some cron job to pin the name frequently.

But even if they don't, it actually helps spread the data because the existing objects get replicated.

**Comment by kuzdogan** [comment]
I looked into this a bit and there's actually a service for these purposes [ipfs cluster](https://cluster.ipfs.io/). I am just trying to better understand the permissions of clusters. [CRDT](https://cluster.ipfs.io/documentation/guides/consensus/) consensus seems to be a better option where Sourcify is a publisher node and others are followers.

Also when we are publishing a new top-level CID we are not unpinning the older CIDs. I don't know to what extent this may cause bloat. Maybe we should start unpinning the old CIDs.

The good thing is, when the top-level CID changes 99% of the files will be the same so if someone regularly pins our new CID they just need to download a few files only. One can then unpin the old CID recursively and pin the new one before everything is garbage collected. I found [this basic script](https://github.com/justicenode/node-ipns-pin) to be run as a cron job. Also here's the [Reddit discussion](https://www.reddit.com/r/ipfs/comments/m94t1j/does_an_ipns_pin_update_itself_automatically_on/grl0tl8/) that lead me to the script.

**Comment by Fluffynorth** [comment]
I maybe be able to help with this. We have a plethora of servers on hostnoc velia etc. All are on latest version of ubuntu. We have roughly a petabyte of storage.

**Comment by kuzdogan** [comment]
> I maybe be able to help with this. We have a plethora of servers on hostnoc velia etc. All are on latest version of ubuntu. We have roughly a petabyte of storage.

Thanks for the offer. We still don't offer an interface or an ipfs-cluster but we do pin to estuary.tech and web3.storage. If you'd like to pin yourself and contribute you can have a look here: https://github.com/otterscan/otterscan/blob/develop/docs/ipfs.md#pinning-sourcify-locally Note that the repo gets updated regularly and ideally you should update the new root CID too. Even if not, most of the times when updated 99.99% contracts will be the same so you'll still be contributing to the availability of the files.
