### ISSUE TITLE
Implement working address db

### ISSUE THREAD

**Issue by cgewecke** [ethereum/sourcify#58]
Tracking issue for [comment][1] in #53 

[1]: https://github.com/ethereum/source-verify/pull/53#discussion_r383613109

**Comment by cgewecke** [comment]
NB: both the injector and react UI currently require an address input.

**Comment by edisinovcic** [comment]
Would it make sense to use same database for this and creation bytecode? 

https://github.com/ethereum/source-verify/issues/111

**Comment by edisinovcic** [comment]
This is implemented here: https://github.com/sourcifyeth/sourcify-monitoring

**Comment by edisinovcic** [comment]
Addressed here: https://github.com/ethereum/sourcify/issues/111
