### ISSUE TITLE
Revisit how and when we extract constructor arguments

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#582]
Currently, Sourcify checks for constructor arguments when the bytecodes of the recompiled contract and onchain contract don't match but they have the same length (e.g. with immutable placeholders to be replaced on deploy time). Ideally, we check and document the constructor arguments whenever possible. 

However, the current workaround is literally scraping the block explorers to extract the constructor arguments. For the chains we are keeping creation bytecodes, we should use our own data, and for the rest we should match recompiled vs onchain code excluding the immutabe fields as these will be placeholders in the recompiled bytecode.

We should also document and communicate the differences of a creation bytecode match, runtime bytecode, and runtime bytecode with immutables.

**Comment by arwer13** [comment]
Am I correct at the moment Sourcify does not provide any validation information on constructor arguments (if no immutable state variables involved)?

Here is an example to illustrate the issue. 
This contract https://goerli.etherscan.io/address/0x142575b7602fbdd427a1121f8ef9c8a0a8ace8b7 was created with value 3 for the single argument of it's constructor.

This is the same contract verified on Sourcify https://repo.sourcify.dev/contracts/full_match/5/0x142575b7602Fbdd427a1121f8EF9c8A0A8ace8b7/

To verify I uploaded two files: HelloWorld.json (solc out json) and HelloWorld.sol. But in HelloWorld.json in creation bytecode the constructor argument's value was replaced from 3 to 4. Namely `3000....` to `4000...` in creation bytecode.
Thus uploaded bytecode doesn't match the one on chain but Sourcify reports "Contract successfully verified!"

The files mentioned:
[HelloWorld-sol-and-json.zip](https://github.com/ethereum/sourcify/files/7534425/HelloWorld-sol-and-json.zip)

**Comment by kuzdogan** [comment]
Hello @arwer13 

Yes, correct. However, we check against the deployed bytecode which does not contain constructor arguments information. This is only found in the contract creation transaction and not in the deployed bytecode. So uploaded bytecode actually matches the one on chain. You'll also see for these contracts we don't have any `constructor-args.txt`. 

In your example, the constructor argument, hence the creation bytecode changes but the deployed bytecodes will be the same. The source code you provided will compile to the same deployed bytecode onchain, but the deployments will be different. Therefore you can verify the contract with the same source code and the metadata.
