### ISSUE TITLE
Api without metadata.json ?

### ISSUE THREAD

**Issue by NameItNow** [ethereum/sourcify#585]
Hi,

First of all, thank you for providing such a vital tool and for all the amazing work you're putting into the project!
I want to use your api to verify contracts for users on my platform but I'm facing a problem.
Getting the metadata.json file is not that intuitive for everyone, my users are used to the etherscan process where the items asked to perform a verification are the abi file, the source files, the solidity version, and the optimization.

How, with these specific data, do I perform verification?
Do I have to generate a metadata.json file on the fly? Could the generated metadata be sent in the body as json instead of a file since the api would be called from the browser?

**Comment by kuzdogan** [comment]
Hello and thank you!

We are ultimately a "metadata and source code repository" so the metadata file is essential for a full match, a full match meaning the source code is byte-by-byte the same out of the contract author's hands, and the metadata which explains the compilation is also exactly the same out of the author's hands. 

For not a metadata is still required unlike Etherscan. But if you aim for a "partial match", you can generate the metadata on the fly, and we'll check for bytecodes without the metadata hashes. Which means as in Etherscan, the source code compiles to the onchain bytecode but might have been different with comments, different variable names etc.

You can always pass the metadata file as a string using `application/json` header: https://github.com/ethereum/sourcify/blob/master/docs/api/server/verification1/verify.md#attempt-contract-verification

**Comment by NameItNow** [comment]
@kuzdogan Ok thank you for this detailed explanation. I will stick with the metadata.json verification as it seems it is the safest way to fully match a contract.
But is there any way to have this metadata.json without calling solc directly? In my case, I'm using hardhat and no metadata.json is generated on compilation.

**Comment by kuzdogan** [comment]
With the [v2.6.8](https://github.com/nomiclabs/hardhat/releases/tag/hardhat%402.6.8) a week ago the build-info output has metadata by default. I will have the metadata for all source files. You need to find the main/target contract you deployed and extract the metadata field in a new file. In the json it is under the field: `output.contracts.<ContractPath>.<ContractName>.metadata`. Just copy-paste this into a separate file and Sourcify should handle the rest. 

We are working on to enable simply providing the hardhat output and do the verification without any manual extraction etc.

**Comment by NameItNow** [comment]
Hey,

There is no `metadata` field in my build-info.
But the path `output.contracts.<ContractPath>.<ContractName>` exists, should I go with what is contained at this path instead?

**Comment by kuzdogan** [comment]
Are you using the latest hardhat v2.6.8? Otherwise you need to manually add metadata to the outputSelection in `hardhat-config.js` as such I think:
```
{
...
solidity: {
  settings: {
        optimizer: optimizerConfig,
        outputSelection: {
          "*": {
            "*": [
              "abi",
              "evm.bytecode",
              "evm.deployedBytecode",
              "evm.methodIdentifiers",
              "metadata",
            ],
            "": ["ast"],
          },
        },
      },
  }
}
```

**Comment by NameItNow** [comment]
Yes, it's doing the job thank you very much!
