### ISSUE TITLE
Fix backup

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#587]
Following the project handover, the S3 backup bucket is no longer working. 
- [x] Update S3 credentials with our own. Start backing up again.
- [x] ~~Rsync the Gather server to Komputing for backup.~~ (edit: ?)
- [ ] ~~Take a physical HD backup of the contract repository~~

Once the backups are established we can try converting the ipfs node to `badgerds` from `flatfs`

**Comment by Spacelee123** [comment]
#563 #563
