### ISSUE TITLE
Handle non-checksummed address paths on repo

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#588]
Currently url's to non-checksummed address paths result with a 404. This became evident in #586. The fix works for that case but as a more general solution, the server should redirect to the path with the checksummed address.

Maybe this can be done in the nginx config through a perl script https://stackoverflow.com/questions/3666003/how-i-can-translate-uppercase-to-lowercase-letters-in-a-rewrite-rule-in-nginx-we/11170826#11170826 following the [EIP-55 specs](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md)

Example
---
The address https://repo.sourcify.dev/contracts/full_match/3/0xc4599061a811ce1c527209ba610525cb01a17722/

should be redirected to 

https://repo.sourcify.dev/contracts/full_match/3/0xc4599061A811CE1c527209bA610525cB01A17722/

**Comment by marcocastignoli** [comment]
lets check if we can do it in h5ai in php

**Comment by kuzdogan** [comment]
I see. Then let's do it ourselves I'd say. The checksum algorithm is fairly simple: https://eips.ethereum.org/EIPS/eip-55 Should be some fun Perl programming 😄

**Comment by marcocastignoli** [comment]
Here is also a working ts snippet
```ts
import { arrayify, kekkak256, Transaction } from '../../utils';

export const getChecksumAddress = async (addr: string): Promise<string> => {
  const address = addr.toLowerCase();
  const chars = address.substring(2).split('');
  const hashed = arrayify(await kekkak256(chars.join('')));
  for (let i = 0; i < 40; i += 2) {
    if (hashed[i >> 1] >> 4 >= 8) {
      chars[i] = chars[i].toUpperCase();
    }

    if ((hashed[i >> 1] & 0x0f) >= 8) {
      chars[i + 1] = chars[i + 1].toUpperCase();
    }
  }
  return `0x${chars.join('')}`;
};
```

**Comment by marcocastignoli** [comment]
Here is the script in PERL

```
#!/usr/bin/perl

use Data::Dumper;
use Crypt::Digest::Keccak256 qw( keccak256_hex );

$address = "0xD4B081C226Bc8aBdaf111DEf54c09E779ad29428"; 

sub Hello {
	$addressLowerCase = lc $address;
	$addressWithout0x = substr($addressLowerCase, 2);
	$addressHex = keccak256_hex($addressWithout0x);

	@chars = unpack("(A1)*", $addressWithout0x);
	@hashed = unpack("(A2)*", $addressHex);
	
	foreach(my $i = 0; $i < 40; $i+=2){
		print "\n";
		if (hex(@hashed[$i >> 1]) >> 4 >= 8) {
      @chars[i] = uc @chars[i];
    }
		if ((hex(@hashed[$i >> 1]) & 0x0f) >= 8) {
				@chars[$i + 1] = uc @chars[$i + 1]
		}
	}

	print @chars;

	print "\n";
}

Hello();
```

**Comment by kuzdogan** [comment]
I missed the part we need to keccak the address before... Can we do that in nginx 😬😬😬

**Comment by marcocastignoli** [comment]
I think yes, it's an external library, as long as it is readable by perl...

...I hope :crossed_fingers:

**Comment by marcocastignoli** [comment]
At the end I couldn't find a way to attach the function I made in PERL with nginx. So I decided to do the url_rewrite in PHP, not ideal but it works
