### ISSUE TITLE
Support both CommonJS and ESM in the npm package

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#590]

**Comment by marcocastignoli** [comment]
@kuzdogan @ligi 
How do we want to proceed about this?
1) have packages in different repositories under the sourcifyeth namespace, so remove every package from this sourcify repo.
2) have all the packages inside this repository, maybe we can consider having a /packages folder in which we move everything, in particular:
  * bytecode-utils
  * contract-call-decoder
  * radpsec (if we will carry it on)

**Comment by kuzdogan** [comment]
Difficult decision but I'd say for now keep the packages the whole sourcify.dev service needs in ethereum/sourcify (e.g. byecode utils that will be used also by the Sourcify server) and others in sourcifyeth (e.g. Metamask snap, decoder). The structure is overall still a little weird. I'm hoping it will get clearer once and if we start working on a Sourcify package for edge verification.

Also closing this issue as it's stale and the contract-call-decoder discussion is moved
