### ISSUE TITLE
update IPFS to 0.11.0

### ISSUE THREAD

**Issue by ligi** [ethereum/sourcify#610]
from the changelog this seems it will be important to us (regarding UnixFS sharding)  - but also for the security fixes - just updated on komputing - but we should also update on the containers

https://github.com/ipfs/go-ipfs/releases/tag/v0.11.0

**Comment by kuzdogan** [comment]
Resolved by https://github.com/ethereum/sourcify/commit/8b1371f2b695fb64f8e44b1de4980b47c2998962
