### ISSUE TITLE
Handle Solidity `v0.6.12` and `v0.7.0` extra files bytecode mismatch

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#618]
Thanks to @lastperson we figured out a Solidity bug that affects Sourcify verification: https://github.com/ethereum/solidity/issues/12281

The bug is caused by extra source files input to the Solidity compiler that won't be used by the target contract. It affects the AST IDs which are allocated one after another which in turn results with a different bytecode if immutables are present. The resulting metadata will omit the extra source files so there will be no way to know these files during Sourcify recompilation. The metadata hashes of the deployed bytecode will match with Sourcify's recompiled bytecode, but the bytecodes will be different.

The effected contract was https://explorer.celo.org/address/0x923182024d0Fa5dEe59E3c3db5e2eeD23728D3C3/contracts at https://github.com/moolamarket/moola-v2/commit/9725017d8fc008e22b6633bc92ec5861569bf754 with the attached metadata [moola-metadata.txt](https://github.com/ethereum/sourcify/files/7729221/moola-metadata.txt). The user circumvented the issue by not inputting extra files apart from those under the `sources` field of the metadata, compiled, deployed, and verified the same contract at https://explorer.celo.org/address/0x29b4923d64B3196AFd81D5f91185D693330cDB7a/contracts.

As a remedy I can think of two things
If the versions are the effected versions `v0.6.12` or `v0.7.0` and optimizer is enabled:
1. If the metadata hashes of the recompiled and deployed bytecode match but not the whole bytecode, warn the user about the issue and link to documentation about the issue.
2. Ask the user to provide all source files they provided at the time of compilation and use them in compilation. Currently, Sourcify only makes use of the source files marked in the metadata. Or shall we use all provided source files all the time regardless of the version?

**Comment by lastperson** [comment]
Hey, any updates on this? I think the solution proposed by @kuzdogan is good.

**Comment by kuzdogan** [comment]
We are currently more focused on rolling out the new UI so unfortunately, I don't think this will be handled earlier than in 2-3 weeks.

**Comment by kuzdogan** [comment]
Finally implemented this with #717 If the above case was detected (bytecodes don't match but metadata does + affected versions) it tries to verify itself once again with all files input. Sorry for the delay.

I made it work with the example you provided but I won't disclose it before you try as I want to see if you'll be able to get a perfect match without knowing how. 

Could you please try and let me know how it goes at https://staging.sourcify.dev ? I'll explain afterwards :)

**Comment by kuzdogan** [comment]
Also added tests with https://github.com/ethereum/sourcify/pull/722. Closing
