### ISSUE TITLE
Unable to verify large project from hardhat build-info

### ISSUE THREAD

**Issue by sirpy** [ethereum/sourcify#727]
I have a large project and hardhat creates a 7MB build-info file, trying to upload it returns an error that file is too large.
i've tried smaller files and they worked

**Comment by kuzdogan** [comment]
The file size limit is actually larger and I'm not sure why you are getting the error. Can you maybe share the file?

**Comment by sirpy** [comment]
i've actually solved it by zipping and uploading a zip. the file size was 70mb not 7:)
