### ISSUE TITLE
Verify contracts w/ immutables

### ISSUE THREAD

**Issue by prestwich** [ethereum/sourcify#749]
~~is any sourcify maintainer in here?~~ edit: sorry this was copied from a telegram chat 😅 

It seems like sourcify can't handle contracts
- with immutables 
- that are deployed by other contracts (internal create call)

I believe this because (from a read of the sourcify source code) it appears sourcify does the following in order:
- [check full match](https://github.com/ethereum/sourcify/blob/master/services/verification/src/services/Injector.ts#L231-L234) (deployedBytecode w/ metadata is identical)
- [check partial match](https://github.com/ethereum/sourcify/blob/master/services/verification/src/services/Injector.ts#L231-L241) (deployedBytecode w/o metadata is identical)
- attempt to verify via the creation-time code by
    - [retrieve the deploying tx's input data](https://github.com/ethereum/sourcify/blob/1b87ab3e36bfa4b5c4da42e64cedbfa415672fc7/services/verification/src/services/Injector.ts#L309-L319)
        - [by querying the chain for `tx.input`](https://github.com/ethereum/sourcify/blob/1b87ab3e36bfa4b5c4da42e64cedbfa415672fc7/services/verification/src/utils.ts#L364-L366)
    - [check for full/partial match on creation-time code](https://github.com/ethereum/sourcify/blob/master/services/verification/src/services/Injector.ts#L250-L265)

so a contract w/ immutables that was deployed by another contract 
- will fail full & partial checks (as the immutables are zeroed in the recompiled code)
- fall back to scraping and verifying creation-time code in`tx.input`
  - fail because the tx input is not a deploy tx, but a function call that triggers a create call in a contract

I want to check my understanding here. It's difficult for me to see a remediation that doesn't involve a tx trace or simulation of running user-provided creation code 🤔

cc @odyslam from our team :)

**Comment by kuzdogan** [comment]
Updated the docs: https://docs.sourcify.dev/docs/immutables/ Let me know if you have any feedback

**Comment by odyslam** [comment]
Thanks @kuzdogan for the information!

**Comment by kuzdogan** [comment]
Just came across this while searching and wanted to point out we added the simulation of the compiled creation-bytecode with user-provided "context variables":
- constructor args
- msg.sender (needed if contract sets `_owner=msg.sender` for example). 
- (any other variables you are aware of? like block number etc?)

At the time I didn't really have the understanding but independently I've reached the same solution :) Sorry for letting this go stale.
