### ISSUE TITLE
Organize documentation

### ISSUE THREAD

**Issue by cgewecke** [ethereum/sourcify#76]
At some point it could make sense to have a simple ReadTheDocs explaining
+ What metadata is
+ How the services / endpoints work
+ What tools are available to help upload sources & metadata to the repository
+ How to access and consume data in the repository
  + perfect matches vs. partial_matches
+ How to deploy your own version of the service

**Comment by edisinovcic** [comment]
Should we publish this as a part of github pages? From readme on master?

**Comment by cgewecke** [comment]
@edisinovcic Not sure, when I've used RTD before I've just had a link in the README to their hosted subdomain. I think Solidity is like this as well...

https://solidity.readthedocs.io/en/v0.6.0/metadata.html

What are you imagining re: Github pages?

**Comment by edisinovcic** [comment]
RTD looks better generally so yes it's a better option. 
Example of github pages: https://blockchain-it-hr.github.io/ink-remix-plugin/

**Comment by edisinovcic** [comment]
Addressing: https://github.com/ethereum/sourcify/issues/104

**Comment by edisinovcic** [comment]
https://github.com/ethereum/sourcify/issues/154

**Comment by kuzdogan** [comment]
Closing, see https://docs.sourcify.dev
