### ISSUE TITLE
repo.sourcify.dev SSL certificate expired

### ISSUE THREAD

**Issue by tbcd** [ethereum/sourcify#760]
Might already be aware of this, but the certificate for `repo.sourcify.dev` expired 2022-06-12, 02:41:25 (around 4 days ago).

As this happened recently for `sourcify.dev` as well, could be worth mentioning that `repo.staging.sourcify.dev` also expires soon: 2022-06-25, 23:44:16 (about 6 days from now).

**Comment by tbcd** [comment]
Well, that was hilarious timing.

Looks like the renewed cert for `repo.sourcify.dev` was activated while I was still typing out the issue. :laughing:

**Comment by kuzdogan** [comment]
Yes it seems that happened exactly when we renewed it. Also renewed the staging certs. Thanks for the heads up :)
