### ISSUE TITLE
Cannot fetch creation data on BSC

### ISSUE THREAD

**Issue by pumpurum2** [ethereum/sourcify#776]
During verification contracts on BSC getting such error:
```
Contract name: VaultParameters. Cannot fetch creation data via 
https://bscscan.com/address/0xd614ABFcbE25788C6c07e50eb0eFf7d5a61e9Cb2
on chainId 56 of contract 0xd614ABFcbE25788C6c07e50eb0eFf7d5a61e9Cb2
```

address https://bscscan.com/address/0xd614ABFcbE25788C6c07e50eb0eFf7d5a61e9Cb2 is exists, contract is verified here.
Also I verified this contract in other networks, worked fine everywhere except BSC.
Issue not only this contract, but with many other from my project on BSC

**Comment by kuzdogan** [comment]
Contracts with [immutables](https://docs.sourcify.dev/docs/immutables/) require fetching the tx that created the contract and its creation data. We work around this by scraping the block explorers for this data. 

This is likely an issue with bscscan requiring a CAPTCHA when scraping and unfortunately there is not much that we can do. 

We run weekly tests to see on which network the "normal" and "immutable" verifications run successfully: https://docs.sourcify.dev/docs/chains/ Unfortunately there is no test specified for BSC mainnet.

However if you'd like to share the contract metadata and source files I can add this contract as a test case. This will not change the outcome of your verification but will just fill a missing test case
