### ISSUE TITLE
Publish Sourcify repos' ipns on DNS

### ISSUE THREAD

**Issue by wmitsuda** [ethereum/sourcify#777]
See: http://docs.ipfs.tech.ipns.localhost:8080/concepts/dnslink/#publish-content-path

The idea is to publish the staging/production ipns paths on DNS, so instead of doing:

```
ipfs pin add /ipns/blablabla-something-I-never-remember
```

people can do something like that:

```
ipns pin add /ipns/repo.sourcify.dev
ipns pin add /ipns/staging.repo.sourcify.dev
```

It doesn't requires changes on current IPFS infra, it just adds another higher level pointer, so:

DNS -> IPNS -> IPFS

Please, do that, I can't stand checking the docs anymore to be sure I'm pinning the right ipns string. It also would help reduce the friction for new people who wants to pin it, much easier to remember, it fits in one tweet :)

**Comment by kuzdogan** [comment]
It works 🎉 thanks for suggestion
https://ipfs.io/ipns/repo.sourcify.dev
https://ipfs.io/ipns/repo.staging.sourcify.dev
