### ISSUE TITLE
Add support for Polygon Mumbai Testnet in Remix

### ISSUE THREAD

**Issue by oceans404** [ethereum/sourcify#784]
Sourcify supports smart contract verification on the Polygon mainnet, but not the Mumbai testnet. Add support for Mumbai so that builders can verify within Remix.

<img width="392" alt="Screen Shot 2022-08-31 at 11 12 44 AM" src="https://user-images.githubusercontent.com/91382964/187749796-8481af16-9a5f-46cb-9af8-76624c811bbf.png">

**Comment by kuzdogan** [comment]
It should be available as "Mumbai" in the list because it's "name" is set so in chainid.network/chains.json but let's show the full title @marcocastignoli

**Comment by oceans404** [comment]
@marcocastignoli @kuzdogan 

Created a PR for this: https://github.com/ethereum/sourcify/pull/786

**Comment by oceans404** [comment]
@marcocastignoli @kuzdogan New PR to update Remix network label source from name to title property https://github.com/sourcifyeth/remix-sourcify/pull/70

**Comment by marcocastignoli** [comment]
@kuzdogan can we close this? Or first we publish the plugin update?

**Comment by kuzdogan** [comment]
Let's close after we publish the update. Can you check the plugin update instructions in the plugin repo?

**Comment by marcocastignoli** [comment]
Update published
