### ISSUE TITLE
Upload from Windows machines can not be processed properly

### ISSUE THREAD

**Issue by xiaohanzhu** [ethereum/sourcify#787]
This is an issue that keeps coming back.  On the sourcify frontend, if we upload a json file or zip file from Windows machines, it will complain "Metadata files missing".  If we upload the same file from Mac, everything works fine.
If we use API to upload a file, the bug will not be triggered.  However if we upload a zip file with a directory structure from Windows, the API will complain can not find the file after we select the contract.

**Comment by kuzdogan** [comment]
Is it exactly the same file or a Windows formatted file? Can you maybe share them?

I will get my hands on a Windows machine next week and will update you.

**Comment by xiaohanzhu** [comment]
correct.  The file is the same.  The only difference is uploading from Windows 11 (chrome/edge) vs MacOS (Safari).  
[contracts.zip](https://github.com/ethereum/sourcify/files/9478880/contracts.zip)

**Comment by xiaohanzhu** [comment]
Is the zipFile.js running in the frontend or backend?  If we upload a zip file with directory structures through the API, the same issue will happen, although zip file without directory structure works for API

**Comment by kuzdogan** [comment]
It is running on the backend. That's good and interesting info and I'll add that in the bug report. But we'll likely replace `adm-zip` completely. Thanks.

**Comment by kuzdogan** [comment]
The issue seems to persist on the jszip library as well. Similarly the error is on reading directories at https://github.com/Stuk/jszip/blob/eaacc682fad834b1e280b58a728704b216c74510/lib/zipEntries.js#L156 not reading fiels

**Comment by xiaohanzhu** [comment]
one more piece of information that maybe useful.  The contents of the zip file is created on a Linux vm instead of windows.

**Comment by kuzdogan** [comment]
Turns out the issue was simpler. Windows was sending a different MIME type we were not checking https://github.com/ethereum/sourcify/commit/92d864d5a3ea1b35ebe29bbf83b5f9cdbe92fbaf

**Comment by kuzdogan** [comment]
It's released, can you please check?

**Comment by xiaohanzhu** [comment]
Yes all good now
