### ISSUE TITLE
Sourcify Versioning

### ISSUE THREAD

**Issue by marcocastignoli** [ethereum/sourcify#793]
We need to start using semantic versioning to rapresent releases of Sourcify, we need to make some decision:
* Do we want to use some library to manage versioning in node.js?
* Do we want to publish to production after a new version? (Or we keep following master?)
* UI, Monitor and server will follow the same versioning, or we want one for each of them?

The version 1.0.0 will contain:
- [x] Prune the repo from unused parts of the code
- [x]  Remove legacy UI
- [x]  Get docs up-to-date
- [x]  API versioning #458

**Comment by kuzdogan** [comment]
- Have global consistent syntax with linting

**Comment by marcocastignoli** [comment]
> * Have global consistent syntax with linting

About this I wonder how to manage having a consistent linting since we have a React project that uses `eslint-config-react-app/base`, can we use it also for the rest of the project?

**Comment by kuzdogan** [comment]
We can use eslint for the rest of the project and have a consistent/similar linting for the rest of the code. Need to look a little deeper how this is usually handled

**Comment by marcocastignoli** [comment]
I ran lint --fix on all code here https://github.com/ethereum/sourcify/commit/102445180a60a9fbcdaa463ddefa00a1f8c15e9e

**Comment by marcocastignoli** [comment]
> API versioning https://github.com/ethereum/sourcify/issues/458

Instead of API versioning, we will go with an API namespace. The new API endpoints will be as follow:

## Not session based

### Verify
/
/verify

### Verify from Etherscan
/verify-from-etherscan
/verifyFromEtherscan

### Check all by addresses
/check-all-by-addresses
/checkAllByAddresses

### Check by addresses
/check-by-addresses
/checkByAddresses


## Session based

### Session data
/session/data
/session-data `deprecated`

### Input files
/session/input-files
/input-files `deprecated`

### Restart
/session/clear
/restart-session `deprecated`

### Verify validated
/session/verify-validated
/verify-validated `deprecated`

### Verify from Etherscan
/session/verify-from-etherscan
/verify-from-etherscan `deprecated`

**Comment by marcocastignoli** [comment]
Updated the docs following the new API nomenclature https://github.com/sourcifyeth/docs/commit/3b1d8c4c64f0a33c32784e2fc13b79cced85d9cd

**Comment by marcocastignoli** [comment]
@kuzdogan update both /verify/etherscan and /session//verify/etherscan in the docs

**Comment by kuzdogan** [comment]
Running Sourcify docs are also up to date.

**Comment by marcocastignoli** [comment]
Released [v1.0.0 ](https://github.com/ethereum/sourcify/releases/tag/v1.0.0)
