### ISSUE TITLE
Add Etherscan API docs

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#799]
We recently added "Add from Etherscan" endpoints to the API. Let's add its documentation to https://docs.sourcify.dev

Would be nice to add the warning that the endpoint can easily reach its rate limit of the API key

**Comment by marcocastignoli** [comment]
Fixed here: https://github.com/sourcifyeth/docs/commit/09827df94aa4daa8a64f9133d15722b21aeaed02
