### ISSUE TITLE
eth-brownie Metadata support

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#804]
Brownie framework (Python) does not output the metadata in its build artifacts. It is used [fairly commonly](https://twitter.com/solidity_lang/status/1490724256765857797). We already opened an issue https://github.com/eth-brownie/brownie/issues/1591 about this but it seems the repo is not really actively maintained. 

It should be straightforward to add the metadata to the build artifacts. Basically, we need to add it to the default standard JSON output and include the metadata in the repo where the build artifacts are written. Bonus for adding a simple test to check if metadata is included by default.

Maybe if we open a PR it will be merged instead of the issue.

**Comment by marcocastignoli** [comment]
I created this draft PR https://github.com/eth-brownie/brownie/pull/1620

**Comment by marcocastignoli** [comment]
I wrote also on the discord group, but seems no one is answering..
