### ISSUE TITLE
Truffle Plugin

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#806]
Similar to the Etherscan plugin [truffle-plugin-verify](https://github.com/rkalis/truffle-plugin-verify) we should be providing a plugin to verify easily on Sourcify e.g. `truffle run sourcify ContractName`

[Article: truffle-plugin-verify](https://kalis.me/verify-truffle-smart-contracts-etherscan/)
Prev. issue about this https://github.com/ethereum/sourcify/issues/289

This could potentially be a Gitcoin bounty

**Comment by marcocastignoli** [comment]
I started this fork of _truffle-plugin-verify_: https://github.com/marcocastignoli/truffle-plugin-verify

I removed all the code strictly necessary to Etherscan and added the code necessary to Truffle. I didn't even try running it.

**Comment by marcocastignoli** [comment]
Npm package: https://www.npmjs.com/package/truffle-plugin-sourcify

**Comment by kuzdogan** [comment]
Opening this again as discussed to PR to the existing plugin https://github.com/rkalis/truffle-plugin-verify

**Comment by marcocastignoli** [comment]
We'd like to have the [truffle-plugin-verify](https://github.com/rkalis/truffle-plugin-verify) support for Sourcify. That means the plugin verifies the contract on Sourcify by default and verifies on Etherscan if an Etherscan key exists.

@rkalis (Rosco), the author, agreed to change the plugin in this functionality.

**Comment by rkalis** [comment]
Hey @marcocastignoli thanks for the tag. I looked at your code in truffle-plugin-sourcify and am working on integrating that into truffle-plugin-verify. Feel free to assign this issue to me.

**Comment by marcocastignoli** [comment]
@rkalis implemented it here https://github.com/rkalis/truffle-plugin-verify/pull/187
