### ISSUE TITLE
Allow deeplinking of verified contract

### ISSUE THREAD

**Issue by ligi** [ethereum/sourcify#811]
it would be great if: https://sourcify.dev/#/lookup has a way to deeplink to a contract

someone shared this:

> This is the RSociety contract if anyone wants to take a final look  https://optimistic.etherscan.io/address/0xfbf562a98ab8584178efdcfd09755ff9a1e7e3a2#code

and I wanted to provide an alternative sourcify link - but in the current flow it is not obvious (or possible) to deeplink to a contract in sourcify - only to the repo (but then you miss other possible chains or the remix integration) - so I think it would be nice when looking up that the contract becomes part of the URL to be able to deeplink

**Comment by kuzdogan** [comment]
Agreed 👍 Works better as a query parameter if we just want to show this UI since we don't do server-side rendering. 

<img width="1784" alt="image" src="https://user-images.githubusercontent.com/13069972/192822937-58ce0e7e-39c8-4178-bb50-030c26b73328.png">
