### ISSUE TITLE
Bug: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by orenyomtov** [ethereum/sourcify#812]
Reproduction steps:
```bash
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d 'address=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48&chainId=1' https://sourcify.dev/server/verify-from-etherscan
```

Result:
```
{"error":"Cannot convert undefined or null to object"}
```

**Comment by orenyomtov** [comment]
I seems to be originating from this line:
https://github.com/ethereum/sourcify/blob/staging/services/verification/src/utils.ts#L142

When the solc output is:
```json
{"errors":[{"component":"general","formattedMessage":"Invalid EVM version requested.","message":"Invalid EVM version requested.","severity":"error","type":"JSONError"}]}
```

Thus not having the `contracts` property passed here:
https://github.com/ethereum/sourcify/blob/staging/services/verification/src/services/VerificationService.ts#L28

**Comment by kuzdogan** [comment]
Thanks @orenyomtov!

It seems the evmVersion is not properly pulled but `istanbul` is hardcoded https://github.com/ethereum/sourcify/blob/2735d2300fd2bfa79e69340ccfa0b91da2e02b98/src/server/controllers/VerificationController.ts#L160-L161

**Comment by kuzdogan** [comment]
https://github.com/ethereum/sourcify/commit/d65d3bbd8aeb00757c28cb57211da570a8fb8b6f
