### ISSUE TITLE
"Contract has no files" when trying to verify the same contract from Etherscan

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#816]
When the same contract from Etherscan is imported from the UI, an error: "Contract has no files" is shown.

To reproduce:
- Import a contract from Etherscan e.g. https://goerli.etherscan.io/address/0x325eBdFf6809D945A38a1412f8849c28007c90Cb#code
- After verification add the same contract

**Comment by marcocastignoli** [comment]
The error message is wrong, and it should not be an error but an alert saying "The contract didn't add any new file"

**Comment by marcocastignoli** [comment]
Since we have never handled warning response, I'd just change the error message for now, @kuzdogan ok?
