### ISSUE TITLE
504 Gateway timeout on verification

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#817]
As @orenyomtov brought up, users are almost always receivig a `504 Gateway Timeout` error when verifying contracts. This happens regardless if verifying from Etherscan or manually by adding files. 

I was able to figure out that this is happening due to a timeout when pinning the newly verified contracts to IPFS after writing them to the disk at https://github.com/ethereum/sourcify/blob/0f4c8422c332f03ed496779a33f2846414de4cde/services/verification/src/services/Injector.ts#L648. This used to happen in a reasonable amount of time but now it seems it is taking too long. I can see from logs that this succeeds at some point but since the IPFS API has a 1 min timeout, the users receive the timeout response. You can also easily see the is contract verified even after the users receive 504 by checking the contract at the Lookup.  

I temporarily switched off the IPFS pinning by removing the API env. var in https://github.com/ethereum/sourcify/commit/0f4c8422c332f03ed496779a33f2846414de4cde. This means newly verified contracts won't be pinned to IPFS but the IPFS repository as it is should be accessible as usual, since the IPFS node will be running. It should temporarily fix the issue.

Nevertheless we need to find a feasible way to pin newly verified contracts under our repo. Previously we were doing a complete new `ipfs add` periodically on the repository directory. This was taking too much time, consuming a lot of resources, as well as potentially causing a lot of SSD r/w. We switched to make use of the Mutable File System (MFS) of IPFS https://github.com/ethereum/sourcify/commit/8c048316cd688b23cf0eca6d8bc641f757a0f5a8 to add each new verified contract directory to MFS and update the IPNS periodically with the new root CID of the repository, instead of a whole `ipfs add` of the root directory. 

Additionally, we really need some comprehensive logging and log monitoring in the codebase. This issue would have been much easier to debug if we had some basic logging.

**Comment by marcocastignoli** [comment]
Instead of awaiting for the response from addToIpfsMfs, we simply run the command async

**Comment by kuzdogan** [comment]
Re-opening this again to keep track if the issue is resolved. Running it async only lets users get a positive response but adding to IPFS still took a long time.

Needs further exploration, potentially changing the way we operate and interface with the IPFS node

**Comment by marcocastignoli** [comment]
I added a script `scripts/verify-massively.mjs` that can massively verify a whole chainId folder. I tested it on staging and this error did not showed up.
