### ISSUE TITLE
Can't open assets in contract repo after verification

### ISSUE THREAD

**Issue by AlissonRS** [ethereum/sourcify#820]
Hi everyone!

I used Remix to deploy my contract. I'm using Remix Sourcify plugin to verify the contract after deployment. When doing so, I get the following:

![image](https://user-images.githubusercontent.com/4753901/193646141-f4834d3e-71e5-4a1b-bc68-f6c10990157f.png)

The contract repo link leads to: ipns://repo.sourcify.dev/contracts/full_match/9001/0x2135dd372227Eb22522289ff237f3348b7F20E44

but I get this message:

> ipfs resolve -r /ipns/repo.sourcify.dev/contracts/full_match/9001/0x2135dd372227Eb22522289ff237f3348b7F20E44: no link named "0x2135dd372227Eb22522289ff237f3348b7F20E44" under QmNwXRaQaSxzsnr4A21CbW5rck9DJ9VvYhHKCQJ63A4PpJ

If I open just `ipns://repo.sourcify.dev/contracts/full_match/9001` indeed I can't find my contract address there, so I'm assuming the Remix Sourcify Plugin is falsely saying _"Contract successfully verified"_, but I'm not sure.

Could anyone give me any directions?

**Comment by marcocastignoli** [comment]
You cannot reach it directly on IPFS right now (I'll let you know why soon), but it is accessible from https://repo.sourcify.dev/contracts/full_match/9001/0x2135dd372227Eb22522289ff237f3348b7F20E44/
