### ISSUE TITLE
Update chains.json (outdated Canto RPC)

### ISSUE THREAD

**Issue by tster** [ethereum/sourcify#836]
The Canto community is having issues verifying contracts with immutables. After quite a bit of debugging, we have tracked the issue down to a web3 call that is failing in /services/verification/src/utils.ts.

The reason for this is that chains.json contains an old RPC URL for Canto which is unreliable. However, the RPC URL supplied at ethereum-lists/chains was updated 27 days ago: https://github.com/ethereum-lists/chains/commit/d5fe555d8fa5c53089dd0e490b5c61943715dc3a

Would it be possible for the Sourcify team to update chains.json to reflect this change?

Thank you

**Comment by kuzdogan** [comment]
Updated with https://github.com/ethereum/sourcify/commit/d47fb8f8c860442f15f35beeb255eb64d85c0321 

Will be available on production with the next release. For now you can check it on https://staging.sourcify.dev

**Comment by kuzdogan** [comment]
Likely next Monday
