### ISSUE TITLE
Improve IPFS infra

### ISSUE THREAD

**Issue by marcocastignoli** [ethereum/sourcify#845]
- [ ] https://github.com/ethereum/sourcify/issues/817
- [x]  Change in `Injector.addToIpfsMfs`
    ```tsx
    ipfs add (--pin=false)
    ipfs.files.cp
    // remove this 
    // await this.ipfsClient.files.write(mfsPath, fileBuffer, { create: true });
     ```

- [x]  Remove the `--enable-gc` setting
- [ ] _postponed_  ~Have two different nodes for pin and fetch~
- [ ] _postponed_ ~Upon having two different nodes, add an “explicit connection” between them~

**Comment by kuzdogan** [comment]
- [ ] Check if it makes sense to use the official Docker image instead of us building ourselves each time
  - Relevant are the init, entrypoint, and publish scripts. 
  - Might not be worth the effort.
  
- [ ] Check the provide time with `ipfs stats provide`

**Comment by marcocastignoli** [comment]
For now I close this issue, I summarize here what I did:
* updated sourcify to 16
* tried online vs offline `ipfs add`: seems like online `ipfs add` is using a lot of cpu
* realized that we cannot do offline `ipfs add` because otherwise we would stay a long time (8hrs) without an ipfs daemon running
* also heathcheck doesn't work if we use offline `ipfs add`
* moved the `/repository` folder outside of `~/.ipfs/`
* added a `DEBUG` env variable to prevent remote pinning, publishing on ipns
* added again `await` in the `addToIpfsMfs` function
* used `ipfs add`,`ipfs files cp` instead of `ipfs files add` in the `addToIpfsMfs` function
