### ISSUE TITLE
[playground]: Sepolia (#11155111) RPC not connecting

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#853]
Current RPC rpc.sepolia.dev is not responding and it's stuck like this 
![image](https://user-images.githubusercontent.com/13069972/203561793-a9d5f97b-3167-4814-96a9-d96caf2f001a.png)

Edit: 
- [ ] It makes sense to iterate over the RPCs in general for cases like this. Sepolia, like many networks, has multiple RPCs specified.

**Comment by ligi** [comment]
you can fallback to https://remix-sepolia.ethdevops.io for now
rpc.sepolia.dev does not seem to be under ethdevops control - will discuss it with @parithosh when he is back from holiday tomorrow

**Comment by kuzdogan** [comment]
This pulls the chainid.network/chains.json file so it might then make sense to change the RPC there. This also means anyone adding Sepolia to their wallet from a website based on this list will use this endpoint. Also similar to Görli's RPCs, Infura can be added there, now that it supports Sepolia.

**Comment by parithosh** [comment]
I've pinged the guys about the RPC being down, but this URL is not under devops control at all and we shouldn't probably use it more than necessary. 

We're considering setting up an EF Devops supported RPC, but we aren't sure if we want to undertake the require obligations that entails. Perhaps using a centralized provider as a default is a good stop gap for now.

**Comment by kuzdogan** [comment]
Closing as it works
