### ISSUE TITLE
[ui]: Lookup does not include deprecated chains

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#860]
Because we **deleted** the deprecated chains (Ropsten, Kovan etc.) the UI does not ask for verified contracts (`/checkAllByAddress`) for them. Even if we have deprecated them, we should include them and mark them `supported: false`. The underlying reason is not with the UI per se, but with `sourcify-chains.ts`.

Also in the future, it might make sense to have an endpoint to look for all chains without `checkByAddress` requiring all chains to be passed.

Example

[0x136f0cC844A873B61E4adF46f885D4e112D3fC20](https://repo.sourcify.dev/contracts/full_match/3/0x136f0cC844A873B61E4adF46f885D4e112D3fC20/) can be seen in the repo.sourcify.dev but in the UI it is not found

**Comment by marcocastignoli** [comment]
Do we have a complete list of the deleted chains? If not I can make it looking at the ´sourcify-chains´ file's history

**Comment by kuzdogan** [comment]
No we haven't stored it anywhere. 

AFAIK it is only the deprecated Ethereum testnets. Instead of looking all the way to the file history, you can check the chainId's that exist in the file system (`full_match` and `partial_match`) but not in `sourcify-chains.ts`. For example Kovan (42) and Ropsten (3).

**Comment by marcocastignoli** [comment]
I compared the production repo with the sourcify-chains.ts, these are the networks that were removed:

* 421611
* 69
* 42
* 3

**Comment by kuzdogan** [comment]
Looks like this broke a test

**Comment by marcocastignoli** [comment]
> Looks like this broke a test

which test? circleci's node-16-test are working

**Comment by kuzdogan** [comment]
The tests were broken with [2c54874](https://github.com/ethereum/sourcify/commit/2c54874db5ddbc48692bad76a9be7381557b2b91) but seems to be back with [35be29d](https://github.com/ethereum/sourcify/commit/35be29dab36ea3d588b930c6df42be54a365b55c).

However I see an extra "View in Sourcify Repository" link to chainId=0 

See https://staging.sourcify.dev/#/lookup/0x1F98431c8aD98523631AE4a59f267346ea31F984

**Comment by marcocastignoli** [comment]
It isn't what we wanted with https://github.com/ethereum/sourcify/issues/869 ?

**Comment by kuzdogan** [comment]
It is what we want if it is create2 verified. 

I see the link even if the contract is not create2 verified 
<img width="1493" alt="Screenshot 2023-05-04 at 14 41 17" src="https://user-images.githubusercontent.com/13069972/236207783-f73eb085-3956-4eb5-8775-7d3a1ee90254.png">

**Comment by marcocastignoli** [comment]
Oh sorry I didn't noticed it, now it's clear

**Comment by marcocastignoli** [comment]
fixed with the commit https://github.com/ethereum/sourcify/commit/f464ef6ce8a81256aeec44c30bf5d2eb9ce2e0f3
