### ISSUE TITLE
[contract-call-decoder]: Radspec throws for "Undefined binding"

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#874]
When evaluating a NatSpec expression the radspec evaluation throws when there's an expression without a value.

For example for this function's `@dev` field

```
    /// @notice Chooses the person at index `_index` as the favorite person 
    /// @dev Has to be called by the `owner`. `_index` can't be larger then the people array length.
    /// @param _index The index of the favorite person
    /// @return Newly chosen favorite Person
    /// @return The index of the new favorite Person
    /// @custom:status production-ready
    function chooseFavoritePerson(uint256 _index) public returns (Person memory, uint) {
```

when the `decodeContractCall` was called it will throw with: `Undefined binding "owner"` since `owner` has no value in the contract call, unlike `_index`.

There are a lot of contracts documented in this way and I guess this will be a common error. This should now throw but be handled gracefully by not trying to replace the value with the expression but keeping the expression in the output. So the `detail` output for `chooseFavoritePerson(3)` should be

```
Has to be called by the `owner`. 3 can't be larger then the people array length.
```

Note that this still is not the perfect way and a better way would be to keep the `_index` for this specific comment. However there is no way to make this distinction.

I know this is something caused by the radspec library and needs a change there. One quick fix if there's an "Undefined binding" could be to fall back to the unevaluated expression e.g. `Has to be called by the `owner`. `_index` can't be larger then the people array length.`.

Edit: Adding source code and metadata [StorageNatSpec.sol.txt](https://github.com/ethereum/sourcify/files/10239303/StorageNatSpec.sol.txt) [SimpleStorageNatSpec_metadata.json.txt](https://github.com/ethereum/sourcify/files/10239304/SimpleStorageNatSpec_metadata.json.txt)

<sub>View in Huly <a href="https://app.huly.io/guest/w-kaanuzdogan-sourcify-65d30de0-75121c5c6c-fd615e?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWU1N2UxMzhiNmVjZDA0ZDYyZDIyZTQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2FhbnV6ZG9nYW4tc291cmNpZnktNjVkMzBkZTAtNzUxMjFjNWM2Yy1mZDYxNWUiLCJwcm9kdWN0SWQiOiIifQ.6I-QJr25rnBGC5sK6OM1ZC3fStywjhu-MY3gDDgQNHw">HI-342</a></sub>

**Comment by marcocastignoli** [comment]
Makes sense to fall back. Maybe we could include also a message field when these kinds of errors happens
