### ISSUE TITLE
[contract-call-decoder]: Unexpected decodedParam

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#875]
When decoding the below transaction the `decodedParam` has the unexpected output 1n.

```
    decodedParams: [
      1n,
    ],
```

This is due the variable being a `bigint`

```
typeof decoded.method.decodedParams[0]
// 'bigint'
```

Is this the expected behavior for uint's? If so this should be documented, otherwise this seems to be a bug.

To reproduce:

```
const decoded = await decodeContractCall(
  {
    to: "0x09aFa1879fa654226D522f7099583d54ee8F18f4",
    data: "0xae7cd3ce0000000000000000000000000000000000000000000000000000000000000001",
  },
  { chainId: 11155111 }
);

console.log(decoded.method.decodedParams[0]) // 1n
```

The contract is https://repo.sourcify.dev/contracts/full_match/11155111/0x09aFa1879fa654226D522f7099583d54ee8F18f4/ and the method called was `chooseFavoritePerson(1)`

<sub>View in Huly <a href="https://app.huly.io/guest/w-kaanuzdogan-sourcify-65d30de0-75121c5c6c-fd615e?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWU1N2UxMjhiNmVjZDA0ZDYyZDIyZGYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2FhbnV6ZG9nYW4tc291cmNpZnktNjVkMzBkZTAtNzUxMjFjNWM2Yy1mZDYxNWUiLCJwcm9kdWN0SWQiOiIifQ.IukP7luMPFldZ-Nh1pgAjaeE-CAalrzWgqnS-ZWAWIA">HI-341</a></sub>

**Comment by marcocastignoli** [comment]
Yeah it is expected. I completally forgot to docuement it, also I'm using a library which returns different implementations of BigNumber depending on the platform. For example on latest browser it returns Xn
