### ISSUE TITLE
Use contract-call-decoder in the Metamask snap

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#881]
The template Snap is using an older version of the contract-call-decoder from the marcocastignoli/contract-call-decoder. Update the library and update the code since the API and the function names have changed.

**Comment by marcocastignoli** [comment]
see https://github.com/sourcifyeth/sourcify-metamask-snap/commit/8954b460e2df01324a56c80f9ed5f8b6cbf932ff
