### ISSUE TITLE
Naming Match quality/status/type consistently

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#893]
Right now we have two different names for representing a Match including the bytecode `auxdata`. It's both "full" and "perfect". This creates confusion and inconsistency.

Let's have a single name for this. I'd suggest just using "perfect"

<sub>View in Huly <a href="https://app.huly.io/guest/w-kaanuzdogan-sourcify-65d30de0-75121c5c6c-fd615e?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWU1N2UyZThiNmVjZDA0ZDYyZDI0NjciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2FhbnV6ZG9nYW4tc291cmNpZnktNjVkMzBkZTAtNzUxMjFjNWM2Yy1mZDYxNWUiLCJwcm9kdWN0SWQiOiIifQ.Z47t4Xje9tW_Y73klQax_izRgqU7kINln88BosYHy0c">HI-366</a></sub>

**Comment by marcocastignoli** [comment]
Regarding this topic, I add that more than 1 person during devcon suggested us to give better naming / colors to the two states of verification. From their point of view users should not feel threatened when interacting with a partially verified contract. I honestly feel like they should do, but that said I believe we must focus on a more explenatory naming for the verification statuses.

I already told you that I would go for a name that explicitly explains that the metadata is also verified, and the other one that makes it clear that only the execution bytecode is verified. My proposal is the following:
* metadata and execution-bytecode verified
* execution-bytecode verified

Of course the main problem with this naming is that the names are not short and most people will not understand them. But I believe that Sourcify's target are not the final users. **From my point of view wallets will be the one thinking about good terminology to explain the users what's going on, our focus should be on giving clear and complete information to the wallets developers.**

**Comment by kuzdogan** [comment]
Coming back to this, I'd say we want to keep a suggestive naming as pushing for full matches is also a goal of this project. In our perspective, a partial match is indeed inferior to a full match. It does not necessarily imply being "unsafe" but for us it's not the desired way to verify. 

If they want to, wallets or applications can choose to convey this to their users differently, e.g. not mentioning full/partial at all and just say verified.

**Comment by kuzdogan** [comment]
Also about the "full" ve "perfect", to go to "perfect" only would require changing the repo structure and potentially other changes. If we were to go this route, we can add a `contracts/full_match` to `contracts/perfect_match` redirect.
