### ISSUE TITLE
Remove Sapphire Testnet configuration

### ISSUE THREAD

**Issue by matevz** [ethereum/sourcify#894]
Sapphire does not support verification of immutable smart contracts, if the request is not authorized, since the constructor parameters are confidential. When the Testnet support was added (https://github.com/ethereum/sourcify/pull/883) the CI was broken and the PR accidentally went through.

I suggest we retract the support for Oasis Sapphire Testnet for now, until we find a proper way to handle immutable smart contracts.

**Comment by kuzdogan** [comment]
Interesting.. Thanks for bringing this up. Looking into what might have caused the CI to accidentally succeed.
