### ISSUE TITLE
Add ENS to the landing page example verified contracts

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#897]
AFAIK there are ENS contracts verified on Sourcify. Find the main contract verified and add it to the featured contracts in the UI `featured.js`. 

ENS Contracts: https://etherscan.io/accounts/label/ens

**Comment by yash251** [comment]
This is the base contract of ENS - 
https://etherscan.io/address/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85
