### ISSUE TITLE
Verification of contracts with immutables not set by the constructor arguments

### ISSUE THREAD

**Issue by marcocastignoli** [ethereum/sourcify#916]
```solidity
contract EntryPoint is IEntryPoint, StakeManager {
    SenderCreator private immutable senderCreator = new SenderCreator();
}
```
In this example the sender creator immutable variable is filled at creation time with the value of the address of the contract SenderCreator deployed in the same transaction that created EntryPoint

EntryPoint: https://goerli.etherscan.io/address/0x0576a174D229E3cFA37253523E645A78A0C91B57
SenderCreator: https://goerli.etherscan.io/address/0x932a3a220ac2cd48fab18118954601f565f19681

We currently don't support this kind of verification. Not even with the simulation, infact we don't have a way to provide the information of the created contract. 

@kuzdogan and I think that one solution would be to implement a verification like simulation but that runs in a fork of the chain at the block before the deployment of the contract.

**Comment by kuzdogan** [comment]
Can you check if this is fixed by `immutableReferences`?

**Comment by marcocastignoli** [comment]
No, it's not fixed. The `immutableReferences` object is empty. I'm wondering how can we handle it.

**Comment by kuzdogan** [comment]
Weird. Can you look into why that's the case? Maybe because the immutable is private?

**Comment by marcocastignoli** [comment]
I can confirm that the reason for this is the property being private and not accessed. When I attempted to add a function for accessing the variable, it became available in the immutableReferences. A similar outcome occurred when I set the property to public.

**Comment by marcocastignoli** [comment]
The identical pattern occurs in both runtime and creation bytecodes; if the property is private and never accessed, it will NOT be present. I am closing this issue, as the variable's presence in the runtime/creation bytecode also implies its inclusion in the `immutableReferences` object.

**Comment by kuzdogan** [comment]
Ok, but this means these contracts can't be verified right? Because this contract was not created by an EOA, meaning we can't `matchWithCreatorTx`. If that's the case we haven't really found a solution and let's not close this issue.

Can you please create a simple example contract that we can share with the Solidity team? We can then question the reasoning behind this and if there are any workarounds

**Comment by kuzdogan** [comment]
My bad, I thought it is "NOT present in `immutableReferences`. The immutable variable is NOT present in the **bytecode** i.e. to my understanding if the variable is not accessed, the compiler just ignores it.

Indeed the contract is verified perfectly: https://repo.sourcify.dev/contracts/full_match/5/0x0576a174D229E3cFA37253523E645A78A0C91B57/

Closing 🎉
