### ISSUE TITLE
Replace Etherscan scraping with the API endpoint

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#941]
We are scraping the block explorer interfaces to get the creator tx of a contract. This, in turn, is used to check if that tx's input is the contract's creation code, which would match the source code.

Sometimes scraping fails because of CAPTCHA's, as in the case with the [failing immutable tests of Ethereum networks](https://docs.sourcify.dev/docs/chains/). Here the tests fail because Etherscan asks a CAPTCHA to CircleCI IPs. Thankfully it works fine on our own server, but the tests are consistent.

Etherscan finally provides an API endpoint to query the contract's creator address and tx: https://docs.etherscan.io/api-endpoints/contracts#get-contract-creator-and-creation-tx-hash 
 
We should use this endpoint instead of scraping. I'm not sure if all Etherscan instances have this e.g. the Optimistic Etherscan, which seems to be running the older version https://docs.optimism.etherscan.io/api-endpoints/contracts. For the chains that have this, we can update and follow other chains later with the same pattern.

**Comment by wmitsuda** [comment]
I was randomly looking at opened issues and came across this one.

May I offer a suggestion? Otterscan has an API to get the creator tx, it is available in every Erigon node, just enable the "ots" namespace on Erigon start params (ex: `--http.api "eth,net,web3,erigon,debug,txpool,trace,ots"`).

It doesn't require any extra disk space, it calculates it using data already available in Erigon DB.

Ex: locating the DAI contract creator:

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0", "id": 1, "method":"ots_getContractCreator","params":["0x6b175474e89094c44da98b954eedeac495271d0f"]}' http://127.0.0.1:8545

{"jsonrpc":"2.0","id":1,"result":{"hash":"0x495402df7d45fe36329b0bd94487f49baee62026d50f654600f6771bd2a596ab","creator":"0xb5b06a16621616875a6c2637948bf98ea57c58fa"}}
```

it gives you the 0x4954... which is the tx, and the 0xb5b0... is the deployer contract which created the contract (NOT the "from" in the tx, but the internal creator).

it is Erigon only (should work on mainnet, all testnets, gnosis, polygon), but it should help to reduce the dependency on Etherscan if you happen to have some spare Erigon node at EF office :)

**Comment by wmitsuda** [comment]
gentle bump/reminder of this issue because it just happened that today ape released a new version and they started using the same API for the same purpose.

see: https://github.com/ApeWorX/ape/issues/1593

**Comment by marcocastignoli** [comment]
Hey @wmitsuda, we just refactored this part of sourcify, sorry for the late response but I was waiting to finish this https://github.com/ethereum/sourcify/pull/1203

Now I'll start asking our team that manages the eth nodes if we support that functionality and start using it for fetching the contract creation transaction

**Comment by wmitsuda** [comment]
no prob sir!
