### ISSUE TITLE
sourcify-chains.ts missing?

### ISSUE THREAD

**Issue by Altcoin-Cash** [ethereum/sourcify#944]
I'm trying to add a chain request, but [sourcify-chains.ts](https://github.com/ethereum/sourcify/services/core/src/sourcify-chains.ts) are not found in staging?

**Comment by kuzdogan** [comment]
We did a refactoring but didn't update the docs sorry. Here it is https://github.com/ethereum/sourcify/blob/staging/src/sourcify-chains.ts
