### ISSUE TITLE
Set an environment variable for solc compiler platform

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#955]
Right now, when compiling contracts we are trying to use the solc compiler binaries, which are set as the `linux-amd64` binaries. While it works for the servers it doesn't work in Apple M-chips (from my experience) and possibly on other platforms such as Windows. 

An environment variable should be set to let users choose which solc platform they want to use as in https://github.com/ethereum/solc-bin. 

Question: Should it contain multiple platforms @marcocastignoli ? I think it doesn't make sense as you likely choose only one so not, or would there be a case? I don't know much about the emscripten
```
SOLC_PLATFORMS=linux-amd64,emscripten-wasm32
```
or
```
SOLC_PLATFORM=linux-amd64
```

It should always fall back to `solc-js`, which means when the var is empty, it would always use `solc-js`.

This also requires us to change the current `SOLC_REPO` variable to the parent directory and save the downloaded binaries in respective folders:

Currently:
```
SOLC_REPO=/home/data/solc-bin/linux-amd64
```

After
```
SOLC_REPO=/home/data/solc-bin
```
and save the binary in `/home/data/solc-bin/linux-amd64/solc-linux-amd64-v0.4.12+commit.194ff033
```

This should be followed after this is resolved:
https://github.com/ethereum/sourcify/issues/954

**Comment by kuzdogan** [comment]
The final verdict is:
- Check the platform from node with `os.platform()` or similar, and choose the relevant binary. So that we don't have to introduce a new env var.
  - As a note in the future for compatibility: What does it return in browser?
- If it's not available use solc.js

**Comment by marcocastignoli** [comment]
> As a note in the future for compatibility: What does it return in browser?

it will depend on the bundler we'll use because process / os is not a global variable in the browser

**Comment by marcocastignoli** [comment]
we decided to auto detect the environment
