### ISSUE TITLE
"Unexpected number" when compiling contracts with solc-js `v0.5.14+commit.1f1aaa4`

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#975]
When debugging, I've encountered a compiler version that when compiled with `solc-js` throw the Error `Unexpected number` when importing at this line:
https://github.com/ethereum/sourcify/blob/a34072832abbbeb4f44b7e0f65065be53d4be1ef/packages/lib-sourcify/src/lib/solidityCompiler.ts#L211

Since I was suspecting this to be related to https://github.com/ethereum/sourcify/pull/964 I've also tested another "symlinked" compiler version in [solc-bin](https://github.com/ethereum/solc-bin/tree/gh-pages/bin): `v0.3.5+commit.5f97274`, and yes that also throws the same error.

I have tested contracts will the following versions:
- `v0.6.0+commit.26b70077`
- `v0.5.17+commit.d19bba13`
- `v0.5.16+commit.9c3226ce`
- `v0.5.15+commit.6a57276f`
- Affected version: `v0.5.14+commit.1f1aaa4`
- `v0.5.13+commit.5b0b510c`
- Affected version `v0.3.5+commit.5f97274`

### With`v0.5.14`:
- https://etherscan.io/address/0xA64BD6C70Cb9051F6A9ba1F163Fdc07E0DfB5F84#code
- https://etherscan.io/address/0xE1FDD398329C6b74C14cf19100316f0826a492d3
- https://etherscan.io/address/0x1690686ff0dc4b94778e3a4125d066d700a38b07#code

### With `v0.3.5`:
- https://etherscan.io/token/0x302ef9993efdceed5dea53ef1f0704d913038c65#code

## Remarks
I can observe two issues here:
1. I suspect this is can be because of symlinking of the compiler, due to an incorrect commit naming as laid out here https://github.com/ethereum/sourcify/pull/964 v0.5.14+commit.1f1aaa4
2. The same error is also thrown in staging, which should actually have used the platform-specific binary and not the `solc-js`. I can see that the binary is not being downloaded under `linux-amd64/`. Is the PR https://github.com/ethereum/sourcify/pull/964 not working as intended? We must further investigate before a prod. release

**Comment by marcocastignoli** [comment]
Calling the generated link that `fetchAndSaveSolc` creates (https://raw.githubusercontent.com/ethereum/solc-bin/gh-pages/bin/soljson-v0.5.14+commit.1f1aaa4.js), you get:
```
soljson-v0.5.14+commit.01f1aaa4.js
```

If you call it again you finally get the right soljson-v0.5.14 implementation.

https://raw.githubusercontent.com/ethereum/solc-bin/gh-pages/bin/soljson-v0.5.14+commit.01f1aaa4.js

So the fix would be to handle this cases in which the url doesn't return the soljson-v0.5.14 implementation but the name to the right file.
